README.md, SentryReactNative.podspec, docs/index.rst, ios/RNSentry.h, package.json
~~This is currently on hold because there are a few open issues with react-native itself.
https://github.com/facebook/react-native/pull/12089#issuecomment-276654535
Waiting for 0.43 release.~~
=> Cocoapods support

docs/manual-setup.rst, package.json, scripts/postlink, scripts/postunlink, sentry.gradle
This changes react-native-foo to react-native foo
=> new react-native commands for sentry-cli

ios/RNSentry.m
=> Fix wrong framecount

README.md
Just one of my silly pet peeves
[Also here's a comic to help you remember the spelling and also make your day slightly brighter](http://hyperboleandahalf.blogspot.com/2010/04/alot-is-better-than-you-at-everything.html)
=> Fix spelling of "a lot"

lib/Sentry.js, lib/raven-plugin.js
=> Fix nativeClient available checks

ios/RNSentry.m
=> Use userdefaults instead of sentry extra for stacktrace merging

SentryReactNative.podspec, ios/RNSentry.m
Fixes https://github.com/getsentry/sentry/issues/5792
=> Make userId optional, Bump sentry-cocoa to 3.5.0

ios/RNSentryEventEmitter.m
=> fix: Check valid JSON object before calling postnotification

docs/config.rst, lib/RavenClient.js, lib/Sentry.d.ts, lib/Sentry.js
=> feat: Add setShouldSendEvent callback

appium/fastlane/Fastfile, docs/manual-setup.rst, sentry.gradle
=> fix: Check for gradle properties

ios/RNSentry.h, ios/RNSentryEventEmitter.m
=> fix: Use mainthread for RNSentry

android/src/main/java/io/sentry/RNSentryModule.java, appium/conftest.py, appium/tests/test_android.py, appium/tests/test_ios.py, ios/RNSentry.m, lib/RavenClient.js, lib/Sentry.js
Fixes #275 
Fixes #274
Fixes #272
Fixes #253
=> Several fixes

appium/Makefile, appium/check_run_failues.rb, appium/tests/test_ios.py, ios/RNSentry.m, lib/RavenClient.js, lib/raven-plugin.js
=> iOS Refactoring

docs/manual-setup.rst
Spent a couple of hours trying to figure what was wrong (was getting `error: An organization slug is required (provide with --org)`) and since I copied and pasted that snippet as is, I removed that line. Hopefully will save others from doing the same mistake!
=> [Docs] Using with NMV - Further instructions

lib/Sentry.js
=> fix: Dsn type check

android/src/main/java/io/sentry/RNSentryModule.java
Fixes https://github.com/getsentry/react-native-sentry/issues/325
=> Fix NullPointerException with tags

android/src/main/java/io/sentry/RNSentryModule.java
=> fix: Capture unhandled promise rejection on android

sentry.gradle
Fixed null object error from calling currentVariants.size() when currentVariants is null by moving null check before size call
=> Fixed null object error

package.json, yarn.lock
=> feat: Bump dependencies

package-lock.json, package.json, yarn.lock
Sentry wizard had a high severity security warning which they fixed on their end.
This PR simply updates @sentry/wizard to make use of that fix.
Related to: 
- https://github.com/getsentry/sentry-wizard/issues/15
- https://github.com/getsentry/react-native-sentry/issues/448
=> ⬆️upgrade @sentry/wizard to @^0.10.2

android/src/main/java/io/sentry/RNSentryModule.java, package-lock.json
Hi guys,
we needed to set a custom fingerprint on captureEvent. We added this to android project. The iOS implementation needs changes in the sentry-cocoa package. We will create a PR there too. I will reference it here. This feature was requested in an issue a while ago, so we thought it would be nice to share it. 
If there are questions or problems, please contact me, so we can fix them.
=> android: custom fingerprint on captureEvent

ios/RNSentry.xcodeproj/project.pbxproj
This PR adds tvOS support to react-native-sentry
=> feat: add tvOS target

sentry.gradle
Fix provided by @icfr for issue #539 
cf. https://github.com/getsentry/react-native-sentry/issues/539#issuecomment-460583113
=> Fix #539 : Update sentry.gradle

android/src/main/java/io/sentry/RNSentryModule.java
I had an issue with my app that `setRelease` had no effect on events being sent to sentry backend.
I debugged it in Android studio and noticed that `hasKey` calls in native function `setRelease` were always returning false.
Maybe it's just my env (Genymotion emulator) but my understanding is that `WritableNativeMap` is intended to be passed over the bridge, and not to store data on native side. Also javadoc for  `WritableNativeMap` says it's write-only.
I replaced `WritableNativeMap` with `HashMap` and now release is sent correctly. `JavaOnlyMap` is another option that worked for me.
=> Use HashMap instead of WritableNativeMap for static extra

README.md
Hey!
Are you sure that it's beta? Maybe someone are lazy to drop this line, let's help maintainers with it :)
Thanks
=> Feature(README): Drop line related beta status

android/src/main/java/io/sentry/RNSentryModule.java
This will eventually be used by TurboModules annotation processor.
=> Add `@ReactModule` annotation and `NAME` constant

android/src/main/java/io/sentry/RNSentryModule.java
Maybe there's a better way? This works at least 😄
=> fix(android): Fix crash in 1.0.8

package.json, src/js/integrations/reactnativeerrorhandlers.ts, yarn.lock
Fixes https://github.com/getsentry/sentry-react-native/issues/558
Fixes https://github.com/getsentry/sentry-react-native/issues/762
=> fix: console.warn promise rejections

.github/CODEOWNERS
If you want to share your spams
=> Add another code owner

sample/App.js, sample/babel.config.js, sample/metro.config.js, sample/package.json, sample/yarn.lock, src/js/integrations/debugsymbolicator.ts, src/js/sdk.ts, yarn.lock
Fix a bug in DebugSymbolicator Integration
Also fixed loading local js from for sample project
Fixes #846
=> fix: Debugsymbolicator

android/build.gradle
`io.sentry:sentry-android:2.1.1` fixes a critical bug for our Sentry integration (https://github.com/getsentry/sentry-android/commit/f53d6b4323920825e1aac4e885415b8f2491bdad#diff-9012add04403ea7e989707da0f18b87f)
This change is required to fix an issue that prevents errors from being reported on Android
I updated my npm package to the one I'm merging and it fixed the issue.
=> Bump to `io.sentry:sentry-android:2.1.1`

android/build.gradle
BUMP sentry-android 2.1.2
Fix #854
=> BUMP sentry-android 2.1.2

android/build.gradle
Can dependabot do this for us?
=> bump android 2.1.3

android/src/main/java/io/sentry/RNSentryModule.java
propagate `enableAutoSessionTracking` from JS to the android sdk
=> pass enableAutoSessionTracking to android

CHANGELOG.md, android/src/main/java/io/sentry/RNSentryModule.java, sample/App.js, src/js/backend.ts
Allow users to configure the timeout of a session
Option exist in the native layers
=> expose session timeout

CHANGELOG.md, android/build.gradle
User custom context is preserved
Ran the sample app on android.
=> build: Bump android to 2.2.0

CHANGELOG.md
Accidentally pushed this straight to master without making a branch. Sorry 😕
https://app.asana.com/0/1163978839534255/1183330583196409
Added a test to test for `sdk_info` in the envelope header.
=> Add sdk_info to envelope header for Android

test/wrapper.test.ts
Add a test to make sure the native module does not get called with an undefined second parameter to prevent this: #990 even though can't reproduce the user's issue we should still have a test for it.
=> test: Add test for second parameter of setUser to be defined

CHANGELOG.md, package.json, sample/App.js, sample/Counter.js, sample/package.json, sample/reduxApp.js, sample/yarn.lock, src/js/backend.ts, src/js/client.ts, src/js/index.ts, src/js/sdk.ts, yarn.lock
Migrating to @sentry/react adds support for the `ErrorBoundary` component along with redux support. Currently `Profiler` does not work yet, so we don't export it.
Tested `ErrorBoundary` and the redux enhancer in the sample app.
=> Migrate to @sentry/react from @sentry/browser

.github/workflows/buildandtest.yml
Remove artifact saving + cache dependencies for really fast workflow runs
=> feat: Use caching instead of artifacts in Build & Test workflow

android/build.gradle
Bump: sentry-android to v2.3.1
https://github.com/getsentry/sentry-android/issues/520
=> Bump: sentry-android to v2.3.1

.github/CODEOWNERS
This is so I get review requests on PRs
This is so I get PR review requests.
=> meta: Add @jennmueng as code owner

package.json
Bump @sentry/javascript dependencies
=> chore: Bump @sentry/javascript deps

package.json, yarn.lock
=> build: Bump @sentry/javascript dependencies to 5.23.0

package.json, sample/ios/Podfile.lock, test/backend.test.ts, yarn.lock
=> fix: Misc fixes to fix failing checks

CHANGELOG.md
=> meta: Update changelog that was forgotten

CHANGELOG.md
Added changelog entry for a pr that didn't have one
=> meta: Changelog for native nagger fix

CHANGELOG.md, package.json, yarn.lock
=> build: Bump @sentry/javascript dependencies to 5.25.0

sample/utils/fetchEvent.ts
Update e2e tests to use new org
=> fix: Fix e2e event endpoint to use new org

CHANGELOG.md, RNSentry.podspec, sample/ios/Podfile.lock
Bump sentry-cocoa to 6.0.9
sentry-cocoa 6.0.9 contains severe bug fixes.
CI
=> build(ios): Bump sentry-cocoa to 6.0.9

.eslintignore, .github/workflows/danger.yml, dangerfile.js
A new [Github action](https://github.com/danger/danger-js) that throws errors if the changelog wasn't updated (can be skipped by typing #skip-changelog ).
It also gives a tip for new features to be documented at Sentry-docs once they are accepted.
Enhanced quality on pull requests.
No open issues.
It's just an action, it's quite similar to this one https://github.com/getsentry/sentry-dotnet/pull/625 , also this PR is proof that it works just fine.
=> feat: add Danger action.

CHANGELOG.md, RNSentry.podspec, ios/RNSentry.m, sample/ios/Podfile.lock
This update contains a fix for increasing the error count on a session
if an event with an error is captured.
We want proper release health stats.
With the sample project.
=> build(ios): Bump sentry-cocoa to 6.1.3

CHANGELOG.md, android/build.gradle
Bump: sentry-android to v4.0.0
Using the latest stable version
=> Bump: sentry-android to v4.0.0

.github/workflows/release.yml
Failing e2e tests unrelated, and will be fixed by #1352 
=> meta: Add GH Actions release workflow

.github/workflows/release.yml
Install dependencies in release workflow.
=> meta: Add install deps job to release workflow

README.md
=> Add Blog posts section to README

CHANGELOG.md, android/build.gradle
Bumps `sentry-android` to `5.0.0-beta.1`
Bump to latest and prepare for RN preview
e2e tests passing
=> build(android): Bump Android SDK to 5.0.0-beta.1

CHANGELOG.md, android/build.gradle
Bumps sentry-android to 5.0.0-beta.4 so that transactions have context data attached.
Tested on Android Sample app by sending a transaction and ensured that the context data was shown on [Sentry.io Transaction Event](https://sentry.io/organizations/sentry-sdks/performance/sentry-react-native:709e174778984f1dbb80edd7a06972e0/?project=5428561&query=transaction.duration%3A%3C15m+event.type%3Atransaction&statsPeriod=1h&transaction=denraseTest10&unselectedSeries=p100%28%29).
=> build(android): Bump Android SDK to 5.0.0-beta.4

CHANGELOG.md, android/build.gradle
Bumps Sentry Android SDK to `5.0.0`. AFAIK there should not be any change needed to RN.
Through Android sample app, and will see e2e tests on this PR.
=> build(android): Bump sentry-android to 5.0.0

CHANGELOG.md, android/build.gradle
Bumps to sentry-android 5.0.1
Includes the fix for incorrect Sources and Javadoc artifacts.
e2e tests
=> build(android): Bump sentry-android to 5.0.1

CHANGELOG.md, android/build.gradle
Bumps Android to latest `5.1.0-beta.2`
Fixes issues regarding transactions and clock drift.
Fixes #1610 
Android sample app, and see e2e tests. Ensured clock drift issue was not present, and that span data is present and correct.
=> build(android): Bump sentry-android to 5.1.0-beta.2

CHANGELOG.md, RNSentry.podspec
Bumps to sentry cocoa  7.1.4.
Fixes getsentry/sentry-cocoa#1248 by including getsentry/sentry-cocoa#1224
Wait for e2e
=> build(ios): Bump sentry-cocoa to 7.1.4

sample/ios/Podfile, sample/ios/sample.xcodeproj/project.pbxproj, sample/package.json, sample/yarn.lock
Bumps sample app to use the latest GA React Native version and enable hermes on iOS for testing.
iOS sample app and await e2e tests
=> build(sample): Bump sample app to RN 0.64.2 and enable hermes on iOS

test/integrations/reactnativeerrorhandlers.test.ts
Adds correct tests for the error handler integration
The original tests were written at the same time as the regression, so the tests were wrong.
Wrote these tests and actually ran it.
=> test: Correct tests for error handlers

.craft.yml
=> craft changelog auto

CHANGELOG.md, package.json, yarn.lock
We moved the wizard into devDependencies which was what contained the cli dependency prior
Fixes #1754
Made a build with the auto sourcemap script
Release this as a 3.0.1 fix
=> fix: Add sentry-cli as a dependency

CHANGELOG.md, sentry.gradle
Fix an issue: https://github.com/getsentry/sentry-react-native/issues/1229
iOS cli PR: https://github.com/getsentry/sentry-cli/pull/967
=> [Feat] Allow to define a custom release name for source-maps upload

sample/ios/sample.xcodeproj/project.pbxproj, sample/ios/sample.xcodeproj/xcshareddata/xcschemes/sample-tvOS.xcscheme, sample/ios/sample.xcodeproj/xcshareddata/xcschemes/sample.xcscheme, sample/ios/sample/Images.xcassets/AppIcon.appiconset/Contents.json
Fixes https://github.com/getsentry/sentry-react-native/issues/1866
=> Min iOS version to 12 for samples and last xcode version

package.json, yarn.lock
Bump to latest wizard to resolve vulnerability issue in dev dependency: https://github.com/getsentry/sentry-react-native/issues/1330
-
=> build(dev): Bump sentry-wizard to 1.2.15

CHANGELOG.md, android/src/main/java/io/sentry/react/RNSentryModule.java
fix: ConcurrentModification exception for frameMetricsAggregator
Closes https://github.com/getsentry/sentry-react-native/issues/1865
=> fix: ConcurrentModification exception for frameMetricsAggregator

CHANGELOG.md, RNSentry.podspec, android/build.gradle
Bump: Sentry Android to 5.5.0 and Sentry Cocoa to 7.6.1
=> Bump: Sentry Android to 5.5.1 and Sentry Cocoa to 7.7.0

android/build.gradle, sample/android/app/src/main/AndroidManifest.xml, sample/android/build.gradle
=> Bump Android SDK target

CHANGELOG.md, android/build.gradle, android/src/main/java/io/sentry/react/RNSentryModule.java
fix: App start measurement on Android
Closes https://github.com/getsentry/sentry-react-native/issues/1968
Running it and simulating Cold and Warm App start.
=> fix: App start measurement on Android

package.json, sample/android/build.gradle, sample/ios/Podfile, sample/ios/sample.xcodeproj/project.pbxproj, sample/package.json, sample/yarn.lock, yarn.lock
Bumps sample app to the latest RN 0.66.4 following the upgrade diff from https://react-native-community.github.io/upgrade-helper/
Keeping the sample app up to date helps us catch potential bugs.
Ran both sample apps locally + See e2e on CI.
=> build(sample): Bump sample app to RN 0.66.4

CHANGELOG.md, RNSentry.podspec
Closes https://github.com/getsentry/sentry-react-native/issues/1964
=> Bump: Sentry Cocoa 7.9.0

CHANGELOG.md, package.json, yarn.lock
Fixes https://github.com/getsentry/sentry-react-native/issues/1424
=> Bump: sentry-cli to 1.72.0

sample/android/build.gradle
Similar to https://github.com/getsentry/sentry-dart/pull/710
=> Remove jcenter from repos

README.md
=> Add new blogpost about BLE

CHANGELOG.md, RNSentry.podspec, ios/RNSentry.m, sample/android/sentry.properties, sample/ios/sentry.properties
=> Bump Sentry Cocoa to 7.10.0

CHANGELOG.md, ios/RNSentry.m
feat: Support enableNativeCrashHandling for iOS
Closes https://github.com/getsentry/sentry-react-native/issues/1362
=> feat: Support enableNativeCrashHandling for iOS

CHANGELOG.md
=> Fix changelog 3.3.0

CHANGELOG.md, RNSentry.podspec, ios/RNSentry.m
Bump Sentry Cocoa to 7.10.1 and report slow and frozen measurements
Slow and frozen frames were not reported.
=> Bump Sentry Cocoa to 7.10.1 and report slow and frozen measurements

.github/CODEOWNERS
@jennmueng so you can focus on the issues that you were purposely tagged :)
=> Remove Jenn from CODEOWNERS

CHANGELOG.md, RNSentry.podspec, android/build.gradle
Bump: Sentry Cocoa to 7.10.2
Closes https://github.com/getsentry/sentry-react-native/issues/1964
=> Bump: Sentry Cocoa to 7.10.2 and Sentry Android to 5.6.3

src/js/tracing/reactnativenavigation.ts, src/js/tracing/reactnativetracing.ts, src/js/tracing/reactnavigation.ts, src/js/tracing/reactnavigationv4.ts, src/js/tracing/routingInstrumentation.ts, src/js/tracing/types.ts
Fix circular dependency for RN tracing
Helps with https://github.com/getsentry/sentry-react-native/issues/2080
=> Fix circular dependency for RN tracing

CHANGELOG.md, RNSentry.podspec, android/build.gradle
Bump: Sentry Cocoa to 7.11.0 and Sentry Android to 5.7.0
Fixes https://github.com/getsentry/sentry-cocoa/pull/1695
```
yarn run v1.22.18
$ jest
PASS  test/transports/native.test.ts (6.396s)
PASS  test/integrations/release.test.ts (6.742s)
PASS  test/backend.test.ts (7.158s)
PASS  test/wrapper.test.ts (7.299s)
PASS  test/tracing/reactnativenavigation.test.ts (7.472s)
PASS  test/tracing/reactnativetracing.test.ts (7.94s)
PASS  test/integrations/reactnativeerrorhandlers.test.ts (7.787s)
PASS  test/integrations/sdkinfo.test.ts (9.191s)
PASS  test/tracing/reactnavigationv4.test.ts (9.259s)
PASS  test/integrations/eventorigin.test.ts (9.16s)
PASS  test/tracing/nativeframes.test.ts (9.496s)
PASS  test/tracing/reactnavigation.test.ts (10.285s)
PASS  test/touchevents.test.tsx (11.268s)
PASS …
```
=> bump: Sentry Cocoa to 7.11.0 and Sentry Android to 5.7.0

CHANGELOG.md, RNSentry.podspec
=> Bump Sentry Cocoa to 7.16.1

.github/dependabot.yml
=> ci: Add GH actions to dependabot

CHANGELOG.md, RNSentry.podspec, android/build.gradle, ios/RNSentry.m, src/js/client.ts
=> Bump Sentry Android 6.1.2 and Cocoa 7.18.0

CHANGELOG.md
=> Update changelog for v4

CHANGELOG.md, RNSentry.podspec, android/build.gradle
https://github.com/getsentry/sentry-cocoa/pull/1915
https://github.com/getsentry/sentry-java/pull/2127
=> Bump Cocoa to 7.18.1 and Android to 6.1.4

.github/workflows/buildandtest.yml, .github/workflows/codeql-analysis.yml, .github/workflows/danger.yml, .github/workflows/e2e.yml, .github/workflows/stale.yml
=> Bump GH actions

package.json
=> chore: pin sentry/wizard

CHANGELOG.md
=> Fix changelog double fixes entry

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/maintainer-blank.yml
=> Chore refactor issue templates

CHANGELOG.md, package.json, yarn.lock
Just wizard update
The new wizard includes TS RN templates support.
=> Update wizard to 2.2.0 to support rn ts templates

sample/ios/sample.xcodeproj/project.pbxproj
- https://github.com/getsentry/sentry-react-native/pull/2463
Fixes the sample project. I didn't commit the new AssetModule.
=> fix(sample) Add AssetsModule to the Xcode project

CONTRIBUTING.md
When I changed nodejs version to 14 because of deps I forgot to update it in this file.
=> Update CONTRIBUTING.md nodejs version

CHANGELOG.md, CONTRIBUTING.md, android/src/main/java/io/sentry/react/RNSentryModule.java, src/js/wrapper.ts, test/wrapper.test.ts
Reason is here https://github.com/getsentry/sentry-react-native/issues/1919#issuecomment-1268547391
Fixes https://github.com/getsentry/sentry-react-native/issues/1919
Running on Android and iOS
=> Nested breadcrumb data on android was not treated correctly

src/js/tracing/reactnativenavigation.ts, src/js/tracing/reactnavigation.ts, src/js/tracing/reactnavigationv4.ts
https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/
=> Improve docs commentsfor routers

android/src/main/java/io/sentry/react/RNSentryModule.java, ios/RNSentry.m, src/js/definitions.ts
=> Remove dead code from the bridge

android/src/main/java/io/sentry/react/RNSentryModule.java
Fix linting
https://develop.sentry.dev/sdk/event-payloads/breadcrumbs/
crumbs level are `info` by default
=> Ref linting

android/src/main/java/io/sentry/react/RNSentryModule.java, ios/RNSentry.m, sample/src/screens/HomeScreen.tsx, src/js/user.ts, src/js/wrapper.ts
Refactor setUser native function params naming and underlying native fucntion. 
Closes: https://github.com/getsentry/sentry-react-native/issues/2532
__#skip-changelog__
=> chore(android): Change from deprecated user.others to user.data

ios/RNSentry.m
Context: https://github.com/getsentry/team-mobile/issues/40
=> Use PrivateSentrySDKOnly.options instead of own options reference

.github/dependabot.yml
Updater action is updating all the JS SDK deps and other sentry/* npm deps. There is a lot of noice by having depbot also updating the same packages.
=> chore(depbot): Add sentry/* npm deps to depbot ignore

.github/workflows/e2e.yml
=> Upgrade emulator runner because of node12

CHANGELOG.md, package.json, yarn.lock
Bumping wizard as this version of the SDK supports modules and the wizard 1.4.0 automatically setup the modules collection.
=> chore: update scripts/update-wizard.sh to v1.4.0

CHANGELOG.md, package.json, yarn.lock
- https://github.com/getsentry/sentry-react-native/issues/2581
=> chore: update scripts/update-cli.sh to 2.10.0

.github/workflows/e2e.yml
```
Building Debug
20[23](https://github.com/getsentry/sentry-react-native/actions/runs/3966509905/jobs/6797397947#step:20:24)-01-20 10:03:11.311 xcodebuild[23109:55280] Writing error result bundle to /var/folders/[24](https://github.com/getsentry/sentry-react-native/actions/runs/3966509905/jobs/6797397947#step:20:25)/8k48jl6d249_n_qfxwsl6xvm0000gn/T/ResultBundle_2023-20-01_10-03-0011.xcresult
xcodebuild: error: SDK "iphonesimulator16.0" cannot be located.
```
=> fix(ci): Change fixed iOS SDK version to OS latest flag 

CHANGELOG.md
Crafting the v5 GA changelog.
Only including v5 changes, omitting fixes between alphas/betas etc.
[Rendered Changelog](https://github.com/getsentry/sentry-react-native/blob/v5-changelog/CHANGELOG.md) 
=> Crafting v5 GA Changelog

CHANGELOG.md, sample-new-architecture/src/App.tsx, src/js/sdk.tsx
Add `enableTracing` option
- closes: https://github.com/getsentry/sentry-react-native/issues/2923
sample app
=> feat(tracing): Add `enableTracing` option

CHANGELOG.md
Make a better changelog.
- https://github.com/getsentry/sentry-react-native/pull/2931
=> fix(changelog): Correct HTTP Client Errors entry and add an example

README.md
- https://github.com/getsentry/sentry-wizard/pull/243
- https://github.com/getsentry/sentry-docs/issues/5730
=> chore(readme): Update to one-line wizard command and add traces sample rate to the code snippet

src/js/client.ts, test/client.test.ts
Adds dummy integration so we can track adoption.
integration tests
=> chore(internal): Add User Interaction Tracing as Integration

src/js/utils/normalize.ts
Quick fix/ignore to lint warnings/errors  on the `normalize.ts` file
=> Fix Lint on utils\normalize.ts

.github/CODEOWNERS
=> Add @lucas-zimerman to CODEOWNERS

.github/workflows/e2e.yml, sample-new-architecture/package.json, sample-new-architecture/yarn.lock
update e2e test to latest minor to verify that nothing is broken
ci
=> chore(ci): Bump e2e tests to 0.72.4

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Corrects grammar in bug report template
=> Correct grammar in bug report template

.github/workflows/e2e.yml
Small CI update, execute all e2e patches from the tested app directory.
=> chore(e2e): Execute all e2e app patches from the app root dir

CHANGELOG.md, sample-new-architecture/src/Screens/ManualTrackerScreen.tsx, src/js/index.ts
Re export the New JS Performance API for React Native users.
- closes: https://github.com/getsentry/sentry-react-native/issues/3370
sample app
=> feat(performance): Export New JS Performance API

CHANGELOG.md, scripts/collect-modules.sh, scripts/sentry-xcode.sh
- introduced in https://github.com/getsentry/sentry-react-native/pull/3425 (not released)
ci e2e
=> fix(xcode): Collect modules path from shell

CHANGELOG.md, android/src/main/java/io/sentry/react/RNSentryModuleImpl.java
- Not released, introduced in https://github.com/getsentry/sentry-react-native/pull/3397, bad merge from main.
sample app, ci
=> fix(android): `proguardUuid` loading

CHANGELOG.md
=> fix(changelog): Remove PR 3631 message, already released

CHANGELOG.md
in sync with https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0
=> fix(changelog): remove authToken from v5.16.0 changelog

.github/workflows/skip-ci.yml
- follow up to https://github.com/getsentry/sentry-react-native/pull/3738
This PR fixes the runs for non PR runs.
=> fix(ci): `diff_check` action should succeed on non-PR runs

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
=> Remove Flutter from FEATURE_REQUEST.md template

.github/workflows/sample-application.yml, samples/react-native/ios/Podfile
Fixes dynamic frameworks builds and add test to CI for it.
To save CI time I only included legacy architecture and dynamic frameworks. The new arch and dynamic doesn't seem to give any new errors/
=> fix(sample): Fix bare sample Pods to work with dynamic frameworks

LICENSE.md
=> date range to license - 2017-2024

.github/workflows/e2e.yml
=> fix(ci): Pin perf metrics ios builds to macos-12 and xcode 14.2

CHANGELOG.md, RNSentry.podspec, RNSentryCocoaTester/RNSentryCocoaTester.xcodeproj/project.pbxproj, RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryOnDrawReporterTests.m, ios/RNSentryOnDrawReporter.h, ios/RNSentryOnDrawReporter.m
Includes hot fixes from: 
- https://github.com/getsentry/sentry-react-native/pull/3815
- https://github.com/getsentry/sentry-react-native/pull/3832
Main branch already includes new features which will be release as 5.23.0.
=> Release 5.22.3 hotfix

CHANGELOG.md, RNSentry.podspec
SR beta release
Relates; to:
* https://github.com/getsentry/sentry/issues/70065
=> bump cocoa SDK 8.31.0

src/js/replay/mobilereplay.ts
Update the JDoc comment to make it reflect the right MobileReplayOptions setting
- [] All tests passing
- [] No breaking changes
=> Fix maskAllImages JSDoc comment

.github/workflows/buildandtest.yml, .github/workflows/codegen.yml, .github/workflows/e2e.yml, .github/workflows/native-tests.yml, .github/workflows/sample-application.yml
=> misc: Enable CI on V5 branch

CHANGELOG.md
=>  docs: Add V6 Release changelog

CHANGELOG.md, packages/core/RNSentry.podspec
=> chore(deps): update Cocoa SDK to v8.41.0-beta.1

CHANGELOG.md
Add when https://github.com/getsentry/sentry-docs/pull/11980 is merged
=> chore: Update `captureFeedback` changelog entry

CHANGELOG.md
Fixes minor changelog typo
Fix typo
Manually
=> chore: Fixes minor changelog typo

.github/workflows/sample-application-expo.yml
This is the last task of https://github.com/getsentry/sentry-react-native/issues/3707 where the Sample app should not fail when exporting it.
https://github.com/getsentry/sentry-react-native/issues/3707
CI
=> Export Expo Sample App on CI

.github/workflows/update-deps.yml, scripts/update-bundler-plugins.sh
=> ci: Add workflow for updating `@sentry/babel-plugin-component-annotate`

CHANGELOG.md, packages/core/android/build.gradle
Brings in mainly SR improvements for Android.
=> chore(deps): Bump Android SDK from v7.20.1 to v7.22.0

samples/expo/app/(tabs)/index.tsx, samples/expo/package.json, yarn.lock
Add InApp Browser to Expo sample for testing of replay masking.
=> feat(samples): Add InApp Expo WebBrowser

CHANGELOG.md
=> chore: Update Expo Gradle docs link

CHANGELOG.md
=> misc(changelog): Add options example and `showFeedbackWidget` code snippet

.github/ISSUE_TEMPLATE/BUG_REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
- adds default issue type `Bug` to bug issue template
- converts feature issue template to align with other platforms + set default issue type `Feature`
=> chore: Adds default issue types to issue templates

CHANGELOG.md, packages/core/android/build.gradle
=> chore(deps): Bump Android SDK to v7.22.4

CHANGELOG.md, packages/core/android/build.gradle
Needed for https://github.com/getsentry/sentry-java/issues/4228
=> chore(deps): Bump Anroid SDK to v7.22.5

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
Using the code block enhances the readability of the created issue, replacing the placeholder with the value guides users to use the "````" notation without the need of manually adding it.
"````" the 4 ticks ensure there is no clash with "`" symbols in the code.
=> chore(issue-templates): Use code block for info command and init snipets

CHANGELOG.md
=> chore(changelog): Add 6.11.0-beta.0 to Unreleased

.github/workflows/e2e.yml, .github/workflows/sample-application.yml
Bump maestro version from 1.39.0 to 1.40.0
https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md#14000
CI
=> chore(ci): Bump maestro version from 1.39.0 to 1.40.0

.github/workflows/e2e.yml, dev-packages/e2e-tests/patch-scripts/rn.patch.app.js
=> chore(ci): Update React Native version in e2e workflow to 0.79.1

dev-packages/utils/package.json, samples/expo/app.json, samples/expo/package.json, yarn.lock
This PR upgrades Expo Sample to the Expo SDK 53. 
Main changes summary at https://expo.dev/changelog/sdk-53 
run the sample locally
Only sample changes in this PR.
=> chore(expo-sample): Upgrade to Expo SDK 53

CHANGELOG.md
=> chore: Fix v7 other changes section header

scripts/update-maestro.sh
Tiny follow up to https://github.com/getsentry/sentry-react-native/pull/4878
=> fix(ci): Change current maestro lookup to `e2e-v2.yml`

packages/core/src/js/tracing/span.ts
=> fix(typo): `stap` -> `span` in tracing span utils

CHANGELOG.md
Adds upgrading section in the changelog
The upgrading section was missing fro beta1
Proofread
=> chore: Add upgrading section in the changelog

.github/CODEOWNERS
=> chore(gh): Update CODEOWNERS, add Alex

CHANGELOG.md
=> chore(changelog): fix whitespaces

.github/workflows/e2e-v2.yml, .github/workflows/native-tests.yml, .github/workflows/testflight.yml
Similar to https://github.com/getsentry/sentry-react-native/pull/5079 for the Testflight workflow that runs only on `main`
Failed check on main https://github.com/getsentry/sentry-react-native/actions/runs/16964858933/job/48089703186#step:11:299
CI
=> chore(ci): Use macos-14 for testflight workflow

CHANGELOG.md
=> chore(changelog): Update CHANGELOG.md

CHANGELOG.md
=> chore(changelog): Fixes changelog alignment issue
