getsentry/sentry-react-native

ios/RNSentry.m

These calls to RCTConvert are inferred based on the types passed into
the macro, according to the RN docs.
http://facebook.github.io/react-native/releases/0.42/docs/native-modules-ios.html#argument-types

Remove superfluous calls to RCTConvert

---

ios/RNSentry.m
lib/Sentry.js
lib/raven-plugin.js

This PR will always use raven-js internally with all its features.
We combine it with our native client to make everything even more powerful.
Fixes #28
Fixes https://github.com/getsentry/react-native-sentry/issues/12

Use Raven Power

---

lib/Sentry.js

This resolves various issues that I discussed with Daniel and Armin on Slack. Changes to `lib/Sentry.js` depend on new configuration options which I have PR'd to raven-js.
Wait until https://github.com/getsentry/raven-js/pull/938 lands to merge.

Add out of the box support for Expo

---

lib/Sentry.js

The config ended up changing slightly before landing on master. See https://github.com/getsentry/raven-js/commit/57859119d5e3d1b4255aa6a0603e844761ff47b7 -- I'll add a commit to this PR when @benvinegar publishes a new release of raven-js to bump the raven-js dependency version in react-native-sentry.

Update Raven instrument config

---

ios/RNSentry.xcodeproj/project.pbxproj

Added React to the Header Search Paths of `RNSentry.xcodeproj`. This fixes a missing `RCTEventEmitter.h` error as mentioned in https://github.com/getsentry/react-native-sentry/issues/21#issuecomment-300355379

Added React to Header Search Paths

---

SentryReactNative.podspec

Needs to include this change https://github.com/getsentry/sentry-swift/commit/362f7ea1b0757e264d0e133546f6439b41c77ed7
Otherwise this leads to a build failure [in RNSentry.m](https://github.com/getsentry/react-native-sentry/blob/v0.8.1/ios/RNSentry.m#L191).

[podspec] Bump Sentry requirement and include all required files.

---

android/src/main/java/io/sentry/RNSentryModule.java

I was getting errors running on Android. The keys for 'user' and 'tags' weren't defined (at least at startup time), so I've wrapped their access in a check.
I wasn't sure if they should be defined at this point in time, I'd be happy to change this PR, if you could point me in the right direction

Fix missing keys in Android event context

---

docs/index.rst
docs/manual-setup.rst
package.json
scripts/postlink
scripts/postunlink

This heavily improves react-native link and unlink.
The idea is that we do some stuff on link that generally makes sense and then persist through unlink and relink. This way users can "upgrade" by unlinking and re-linking to newer react-native sentry versions.

Improve react-native link

---

android/build.gradle

It is recommended by React Native to use build tools 23.0.1
https://facebook.github.io/react-native/releases/0.23/docs/android-setup.html#configure-your-sdk

Use android buildToolsVersion 23.0.1

---

SentryReactNative.podspec

Full context is in https://github.com/getsentry/sentry-cocoa/issues/169
This should fix a build using CocoaPods for Sentry + SentryReactNative

Update SentryReactNative.podspec to remove RSSwizzle

---

lib/Sentry.js

**Sentry.isNativeClientAvailable()**
Currently, calling this function can throw `undefined`, so we end up writing something like:
```
const isInstalled = Sentry.isNativeClientAvailable() !== undefined;
```
In my opinion, this should return either *true* or *false*. I'd like to get something like this:
```
const isInstalled = Sentry.isNativeClientAvailable();
```
In our case, we need to instantiate a shared util that configures Sentry on the go. We need to do this just once, so we ask Sentry if is ready/installed many times, but we set it up just the first one.
**Disclaimer**: not a big JS fan or expert here. And if there is a better way to achieve this behaviour, please let me know!

Make Sentry.isNativeClientAvailable a boolean function

---

lib/Sentry.js

changed lib/Sentry.js to not require the raven client to be installed following advice from #85. Closes #55.
Previous PR got in a bit of a pickle, so I've opened this one with the relevant commit cherry picked out.
Thanks

[Revamped] Allow calls to be made to Sentry when not installed

---

SentryReactNative.podspec

Currently cocoapods install max version 3.0.12 of `sentry-cocoa`, but in latest version of `react-native-sentry` you are already using latest interface. Especially `shouldSendEvent` callback of `SentryClient`, which has been introduced in version 3.1.0. So we are not able to build it ;) See screenshot below

Bumping sentry-cocoa version to 3.1.2

---

scripts/postlink

This issue has been brought up before, there is an ignore list for the glob `['node_modules/**', 'ios/Pods/**', '**/Pods/**']` however I have a git submodule within my project hence this does not get ignored. So changed it such that the glob only searches 1 directory down for the `*.xcodeproj/project.pbxproj` file.

Do not search recursively in glob for ios.

---

android/src/main/java/io/sentry/RNSentryPackage.java

createJSModules was removed in 0.47.0 release here https://github.com/facebook/react-native/releases/tag/v0.47.0
RN code change here https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8
I only remove @Override keyword, not sure if keeping the function would make it compatible with older versions of RN. Please check.

Fixed Compilation Error in React Native 0.47.0

---

appium/Makefile
appium/fastlane/Fastfile
sentry.gradle

This PR fixes gradle plugin error `getResDir`
The output of `./gradlew assembleRelease --stacktrace` is: (so it seems to work)
```
...
:app:bundleReleaseJsAndAssets
Scanning 564 folders for symlinks in /Users/haza/Projects/react-native-sentry/examples/react-native/AwesomeProject/node_modules (8ms)
Scanning 564 folders for symlinks in /Users/haza/Projects/react-native-sentry/examples/react-native/AwesomeProject/node_modules (17ms)
Loading dependency graph, done.
warning: the transform cache was reset.
bundle: start
bundle: finish
bundle: Writing bundle output to: /Users/haza/Projects/react-native-sentry/examples/react-native/AwesomeProject/android/app/build/intermediates/assets/release/index.android.bundle
bundle: Writing sourcemap output to: …
```

Fix gradle script getResDir for gradle > 3.0

---

appium/fastlane/Fastfile
sentry.gradle

Fixes https://github.com/getsentry/react-native-sentry/issues/157
~~If you pass `-Pflavoraware=true` to gradle e.g.:~~
~~`./gradlew -Pflavoraware=true assembleDebug --stacktrace`~~
it produces the following output and uses `url` `authtoken` `org` `project` from the file to pass it to `sentry-cli`.
```
**********************************
* Flavor aware sentry properties *
**********************************
For demoDebug using: /Users/haza/Projects/react-native-sentry/examples/react-native/AwesomeProject/android/sentry-demoDebug.properties
For demoRelease using: /Users/haza/Projects/react-native-sentry/examples/react-native/AwesomeProject/android/sentry-demoRelease.properties
For fullDebug using: /Users/haza/Projects/react-native-sentry/examples/react-native/AwesomeProject/android/sentry-full …
```

Add functionality for flavor aware sentry properties in gradle

---

ios/RNSentry.m
ios/RNSentryEventEmitter.h
ios/RNSentryEventEmitter.m
lib/NativeClient.js

Fixes #158 
For react-native > 0.45 they no longer provide the `moduleID` <-> `moduleName` mapping we use to not trace every stacktrace that crosses the native bridge.
This result is a massive performance impact when for example an animation happens and react-native sends an update over the native bridge for every frame (almost 60 updates / sec) which is way to much when we always create a `new Error().stack`.
This PR adds a workaround; We are able to fetch the `moduleName` on the native side, I additionally send the `moduleID` over the bridge and build an index on native with `moduleID` <-> `moduleName`.
After an update to this, I propagate the changes to javascript (EventEmitter) and build our `_ignoredModules` in javascript which we then use to decide what we send over the native …

Improve performance on stacktrace merging

---

.editorconfig
.travis.yml
.travis/run.sh
appium/Makefile
lib/NativeClient.js
lib/RavenClient.js
lib/Sentry.d.ts
lib/Sentry.js
package.json
typescript/Sentry-tests.ts
yarn.lock

feat(typescript): Add typescript definitions

---

android/build.gradle

I realized this did actually fix a bug that is possible on Android, may as well bump it.

Upgrade sentry-android depdendency to 1.5.3

---

lib/raven-plugin.js

This PR fixes bad frame paths when only using `raven-js` aka `disableNativeIntegration`
ref: https://forum.sentry.io/t/react-native-sentry-android-sourcemaps-uploaded-but-not-matched/2377/7
Also, it updates the regex to work with CodePush 
ref: https://github.com/getsentry/raven-js/pull/1042

fix: url for frames when using raven-js

---

index.js

eslint-plugin-import doesn't track the exports properly when passed through
indirectly, and this approach is more direct / succinct.

Use export * to export items in index.js

---

appium/fastlane/Fastfile
lib/NativeClient.js

fix: Add try/catch of occasional crash when parsing json

---

sentry.gradle

It used to run for every variant not just the active ones
Fixes #245
Fixes #234

fix: Run sentry-cli upload only once per active flavor

---

sentry.gradle

My fix for #255
For each bundleTask I parse build variant from task name. This way it's guaranteed that sourcemap upload runs only once for correct release.

fix: Parse current build variant from task name

---

.npmignore
appium/fastlane/Fastfile
docs/config.rst
docs/index.rst
lib/NativeClient.js

This always causes problems so we are making the default off

fix: Make stacktrace merging default off

---

package.json
scripts/postlink.js

Bump sentry-cocoa version
Note:
https://github.com/getsentry/react-native-sentry/pull/265/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R40
This is supported for over a year now, so we should be good.

feat: Update link step to use new App.js for rn > 0.49

---

android/build.gradle

Multiple bugfixes, but one effects offline disk buffering of events so probably useful here.

Bump sentry-android to 1.6.1

---

.travis.yml

Device farm tests cannot be executed in PRs from contributors outside of the
organization since secure environment variables are missing. Besides that,
they take awfully long to execute and force contributors to wait unnecessarily.
An example of this is #266.
This fix follows an approach from getsentry/raven-js#1095, by using the
`TRAVIS_SECURE_ENV_VARS` variable. It indicates whenever the variables are
present.

ci: Prevent device farm builds in outside PRs

---

sentry.gradle

Fixes a case where sentry silently fails if the application name contains a number.

Allow numbers in applicatication name

---

SentryReactNative.podspec
android/src/main/java/io/sentry/RNSentryModule.java

Fixes: https://github.com/getsentry/react-native-sentry/issues/169
This fix is more of a workaround, the problem probably was that it created some kind of race condition where the sending of the event isn't fully done yet, but the bubbling of the JS error from react-native causing a crash was interrupting the send process.
So it sometimes happened that the event still was sent, but then also stored and send again after restart.
Now on Android I send the notification of storing the event after I receive the success callback of sending it.
That makes sure that it has been send before the app crashes.
On iOS we only really store the event and not try to send it at all.

fix: Call store event on android when the event has been sent

---

sentry.gradle

Sentry requested sourcemap (like for release bundle) should be auto deleted after upload is complete.
For our usage, the resulting `release.apk` is ~1MB smaller, except with an extra line in `\assets\index.android.bundle`:
//# sourceMappingURL=index.android.bundle.map

fix: Clean up sentry requested sourcemap

---

ios/RNSentry.m
lib/Sentry.js

Exposes `crashedLastLaunch` on iOS.  Allows the client to check after Sentry install has completed whether or not there was a crash on the previous launch.

Expose crashedLastLaunch for iOS

---

lib/Sentry.js

When Sentry is not configured and you for example call `Sentry.captureMessage`, `_log` tries to pull `logLevel` out of `undefined`, as `Sentry.options` is only set when calling `Sentry.config` with a valid DSN.

Don't crash on _log when Sentry is not configured.

---

android/build.gradle
android/proguard-rules.pro

Fixes a case when Android build if the RN project enables proguard.

Add proguard rule

---

docs/manual-setup.rst

I'm currently using `react-native-sentry` version `0.33.0`.
I don't know if we should be more explicit about the versions here.

Update sentry-cli path on manual-setup.rst

---

android/src/main/java/io/sentry/RNSentryModule.java
lib/NativeClient.js
lib/Sentry.js

NOTE: This does not seem to occur on iOS. We believe that it fails silently which is also an error. We have not done extensive testing there.
---
We found an issue on Android (8.1 was used) where if we used the public DSN URL we would get an exception citing that we were missing the Sentry secret. In react native, this gave us a red box with the error but it crashed our app. We tried to wrap in a try/catch but no luck. 
The error was happening asynchronously [in the Sentry Java SDK](https://github.com/getsentry/sentry-java/blob/97fc170d0eec16906e56262cfedd075f0153fa72/sentry/src/main/java/io/sentry/dsn/Dsn.java#L204) and not being broadcasted over the [RN bridge like you would expect](https://facebook.github.io/react-native/docs/native-modules-android.html#callbacks) (note this line …

Fixing uncatchable, crashing, exception on Android

---

android/src/main/java/io/sentry/RNSentryModule.java
ios/RNSentry.m
lib/NativeClient.js
lib/Sentry.js

This makes the start call async more info here:
https://github.com/getsentry/react-native-sentry/pull/355
I've changed it so it works for iOS and Android.
Fixes https://github.com/getsentry/react-native-sentry/issues/347

fix: Bugfix async start / Clone Object before send over bridge

---

android/src/main/java/io/sentry/RNSentryModule.java
ios/RNSentry.m
lib/Sentry.js

Now you can do this to "catch" a possible misconfiguration with the DSN
```
Sentry.config(sentryDsn, {
logLevel: SentryLog.Debug,
deactivateStacktraceMerging: false
})
.install()
.catch(error => {
console.log(error);
});
```
cc @cworsley4 
Also fixes #354

fix: Make install async to make it catchable

---

sentry.gradle

Hi!
I've encountered an issue that I haven't find a way how to resolve.
My Android app (and any other React Native app that uses default settings) have builds for 2 ABIs: `"x86"` and `"armeabi-v7a"`. App versions with different ABIs should have different version codes as per Google Play Store requirements.
The issue is that on each build `react-native-sentry` took only one version code on each build, which makes source maps work only for a version of the app with "lucky" ABI (I believe it's the last of alphabetically sorted list) which version code was used as `--dist` argument on source maps upload. 
But for source maps to work on all ABIs, all of their version codes should be accounted.
There's a code in `sentry.gradle`:
```
versionCodes.each { versionCode ->
args.add("--dist"); …
```

Make sentry.gradle include all ABIs version codes as dist

---

SentryReactNative.podspec
docs/cocoapods.rst
ios/RNSentry.m
package.json
yarn.lock

This fixes an issue where if an error occurs in a module, we do not send the event to Sentry because it's always a `RCTFatalException`.
This makes the check more explicit.
Also updated CocoaPods docs.

fix: Check for Unhandled js exception

---

SentryReactNative.podspec

I'm using Sentry with a `React Native`-only app.
`react-native link react-native-sentry` adds `RNSentry` as a pod. If I include `React` as a pod in `Podfile`, all is ok. But I explicitly do not include `React` as a pod in my `React Native`-only app, because it has many downsides and using-react-as-a-pod-issues. In this case `Sentry`-pod forces CocoaPods to satisfy this (check the changes of this PR) `React`-dependency by installing old/obsolete/deprecated `React` `0.11`, which breaks even more things.
Resolution is to remove this dependency.
Check corresponding issues in another repos:
invertase/react-native-firebase#325
invertase/react-native-firebase#324
ocetnik/react-native-background-timer#71

Remove obsolete React podspec dependency

---

lib/raven-plugin.js

See https://github.com/getsentry/raven-js/pull/1330

ref: Emit transaction instead of culprit

---

docs/codepush.rst

In react-native, codepush is been exported as `codePush` instead of `CodePush`.
The release command has also been changed to be part of appcenter command.

change codepush command

---

lib/Sentry.d.ts

Since `install` is async, it might make sense for a user to want to ensure sentry is completely installed before doing some other work, in order to not miss any messages/exceptions that might occur. With the current type def, this requires a nasty typecast from typescript (eg. `(Sentry.config(...).install() as any as Promise<void>).then(...)`), so let's expose `install`'s async signature properly.

Expose async `install` signature in typescript def

---

.gitmodules
.travis.yml
CHANGELOG.md
README.md
SentryReactNative.podspec
android/build.gradle
ios/RNSentry.m
ios/RNSentry.xcodeproj/project.pbxproj
ios/RNSentry.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
package.json

- `react-native-sentry >= 0.39.0` requires `react-native >= 0.56.0`
- [Android] Bumping of gradle deps
```
compileSdkVersion 26
buildToolsVersion '26.0.3'
...
targetSdkVersion 26
```
- [Android] Use `sentry-android` `1.7.5`
- Bump `@sentry/wizard` `0.11.0`
- Bump `sentry-cocoa` `4.0.1`
- Use new SDK identifier `sentry.javascript.react-native`

feat: Bump deps

---

android/src/main/java/io/sentry/RNSentryModule.java

Within the https://github.com/getsentry/sentry/issues/5792, the iOS part has been fixed by the https://github.com/getsentry/react-native-sentry/pull/205/files.
This change makes the userId optional in the Android code.

Make userId optional in the Android code.

---

lib/Sentry.d.ts

This PR improve typescript definitions slightly. For `SentryOptions`:
- Add missing `handlePromiseRejection` option
- Fix typings for `ignoreModulesExclude` and `ignoreModulesInclude`
- Fix type of `deactivateStacktraceMerging` to be optional (or `npm run test:typescript` failing, does it run in CI?)
- Add doc comments for some options
Also I have one question. There is `instrument` option, but I can find it only in default values in file: https://github.com/getsentry/react-native-sentry/blob/727dca6f7e516191ea646ff9b0ce5c3e9674e4b9/lib/Sentry.js#L64 
Does it used at all?

Improve typings

---

android/build.gradle

This PR allows a library user to define Android SDK version. It is a common practice in React Native community to check project level properties in `rootProject.ext` for that.

Check project properties to get sdk version

---

android/build.gradle

Lead to the error message:
```
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/me/Apps/mobile-app/node_modules/react-native-sentry/android/build.gradle' line: 9
* What went wrong:
A problem occurred evaluating project ':react-native-sentry'.
> Could not find method buildToolsVersion() for arguments [27] on object of type com.android.build.gradle.LibraryExtension.
```

Fix: :bug: Was not getting buildToolsVersion

---

sentry.gradle

Add proper windows support with default config

---

lib/raven-plugin.js

- Addresses an issue events (on Android platform) are being sent with `transaction` context value `app://index.android.bundle` rather than `app:///index.android.bundle` which means source code cannot be found
- Related to issue https://github.com/getsentry/react-native-sentry/issues/531

Add return case to ensure normalised url is a file path (begins /) after 'app://'

---

index.js
lib/Sentry.d.ts
package.json

This PR fixes a couple of things:
- Add `types` field to package.json
- Properly export the default export from the main module
- Strictness of some TS types

Improve TS typings

---

android/src/main/java/io/sentry/RNSentryModule.java

Ran into this react native error even when not using Sentry. Sentry will crash (and crash your RN app with it) if stacktrace doesn't exist. This adds a check for stacktrace just like the checks being performed in the immediate vicinity of this code.
Related to issue #487

Checking if stacktrace exists before accessing it

---

package.json
yarn.lock

as per [discussion](https://github.com/getsentry/sentry-react-native/issues/612#issuecomment-511434560) in #612 `snyk` automatically added itself as a `dependencies` in `package.json` as part of #615 yet it should be in the `devDependencies` so that downstream users do not have to install snyk as an (unused) dependency, and with it, it's own (transitive) dependencies.
I also noticed that snyk's lockfile entry was out of sync with it's entry in package.json. At a guess snyk bumped itself automatically in f57f8d35f36f5a725f46a7b173fa259408f24004 but I'm assuming it doesn't handle then updating the `yarn.lock` at the same time.
Snyk's use is only at development time and doesn't have any effect/use for library users directly

Move snyk dependency and fix lockfile entry

---

android/src/main/java/io/sentry/RNSentryModule.java

This PR fixes two small bugs in our handling of Android breadcrumbs.
1) Currently, Android breadcrumbs miss copying over the `type` attribute of breadcrumbs, leading all breadcrumbs to be of type `"default"`. Among other things, this affects their display in the UI:
Without `type`:
With `type`:
2) Somehow or other, the response status code for XHR requests is getting cast as a double (you can see it in the first screenshot above), which is confusing people. This strips the decimals off so that the status again appears like `200` rather than `200.0`.

fix(breadcrumbs): Fix missing `type`, miscast `status_code` entries in Android breadcrumbs

---

sentry.gradle

Closes: #721 
This PR adds the ability to override where `sentry.gradle` will find the `sentry.properties` file. 
It also pulls up some of the validation to only run once instead of for each bundle task because the validation doesn't vary by bundle task.

Allow overriding sentry.properties location

---

README.md

Adds documentation for running the wizard when self hosting Sentry.
See https://github.com/getsentry/sentry-react-native/issues/311, https://github.com/getsentry/sentry-react-native/issues/17
Not sure how auto-linking affects these instructions.

docs: add instructions for self hosting

---

android/src/main/java/io/sentry/RNSentryModule.java

Android lint throws warning of a redundant type cast

Lint: Redundant type cast

---

android/src/main/java/io/sentry/RNSentryModule.java

PR to fix issue https://github.com/getsentry/sentry-react-native/issues/742

temporary solution checking if frames exists before extracting the value

---

src/js/integrations/debugsymbolicator.ts
src/js/sdk.ts

... and also avoid using the DebugSymbolicator in release mode.

fix: Strip a bogus function name suffix from Hermes frames

---

sentry.gradle

The way the gradle hook works is very fragile, and it extracted the wrong sourcemap reference
when working with a multi-stage build process (as used for hermes).

fix: Pass the correct sourcemap to sentry-cli

---

.github/ISSUE_TEMPLATE.md

People often confuse the `React Native version` field with a (heretofore non-existent) `react-native-sentry / @sentry/react-native version` field. It's helpful to have both, so let's explicitly ask for them.
Also removes the italics from the `Platform` heading, to match the headings before and after.

meta(issue template): Add SDK version to issue template

---

android/build.gradle
android/src/main/java/io/sentry/RNSentryModule.java
src/js/wrapper.ts

@HazAT it was supposed to be a draft PR but.. This is an attempt (untested) to fix: https://github.com/getsentry/sentry-android/issues/273
The size issue exists because currently, we use the string length which is the number of characters. The envelope spec expects the number of bytes (which in UTF-8 vary depending on the character).
Ideally, we'd implement this in Java (we need it there anyway given the new hybrid spec) and RN will just call in with the event.
Fixes: https://github.com/getsentry/sentry-react-native/issues/775

fix: Envelope header bytes length

---

sentry.gradle

fix source maps folder detection

---

RNSentry.podspec
android/src/main/java/io/sentry/RNSentryModule.java
ios/RNSentry.m
sample/App.js
sample/android/.project
sample/android/.settings/org.eclipse.buildship.core.prefs
sample/android/app/.classpath
sample/android/app/.project
sample/android/app/.settings/org.eclipse.buildship.core.prefs
sample/android/app/src/main/java/com/sample/MainApplication.java
sample/ios/Podfile.lock
src/js/client.ts
src/js/integrations/devicecontext.ts

To note:
* Even though not public API in react-native, it was public on the bridge but now removed:
`crashedLastLaunch`
* Now passing the whole dictionary of options which might not be wise. Needs a review. Should we whitelist what can go through? Or perhaps blacklist what we know should only stay at the JS layer?
* Dropping `enableNativeCrashHandling` which means we're always bringing in native crashes. Can we get feedback on this? Is it a real use case where users need only JS crashes?
TODO:

sentry-cocoa 5.0

---

.github/ISSUE_TEMPLATE.md

While the request for a link to an example Sentry issue currently shows up for the user when they're creating a GH issue (just as the comments here do), people still ignore it. So, I made it a little more in-your-face.
Other changes:
- Added version hints to the SDK choice, to prevent people from checking both of them
- Made the formatting more consistent throughout

ref: Reformat issue template

---

package.json
src/js/backend.ts
src/js/integrations/devicecontext.ts
src/js/integrations/release.ts
src/js/wrapper.ts
test/backend.test.ts
test/wrapper.test.ts

Wrote functions to mirror the native modules in a wrapper. Added tests to test the basic functionality of the wrapper along with testing for initializing the backend.
Removed all usages of `RNSentry` outside of the native wrapper.
This is for the migration of all usages of `RNSentry` to a native wrapper to allow for more extensive testing of the SDK.
Wrote new tests in Jest.

Remove usages of RNSentry to a native wrapper

---

android/src/main/java/io/sentry/RNSentryModule.java
ios/RNSentry.m
src/js/backend.ts
src/js/wrapper.ts
test/wrapper.test.ts

Refactored the `startWithDsnString` method in the native wrapper to be `startWithOptions`. If a DSN is not provided to Android an empty string will be the fallback. Added a warning message if a DSN is not provided.
Having the DSN is a separate parameter was redundant as it's already included in the options passed.
Wrote two Jests tests to test that it calls the native module, and that the warning is logged when a DSN was not provided. Tested on the sample iOS and Android with emulators, with DSN provided and no DSN provided.

Refactored startWithDsnString to be startWithOptions.

---

android/src/main/java/io/sentry/RNSentryModule.java

Unless explicitly passed in via configuration, attachThreads will be `false`.
JS sends event.stacktrace (see getsentry/sentry-javascript#2605 and `sentry-android` attaches event.threads and the UI picks the threads instead. But that means the stacktrace unrelated to any thread doesn't render, and the Java threads are irrelevant (in fact they don't include any frame). Lastly threads don't seem to be useful in this context
Used the sample app

fix: Don't attach Android Threads

---

android/src/main/java/io/sentry/RNSentryModule.java

@marandaneto this is your fix.
I believe we should also change the `wrapper.ts` and avoid calling `RNSentry.init` completely if the JS options have `initNative`=false.

disable native integration

---

sentry.gradle

The react native sentry client appends its versionCode to its
releaseName, so each versionCode needs to have its own release in order
for sourcemaps to work properly. Iterate over all release variants and
create the corresponding release with the matching sourcemap artifacts.
Closes #798

Upload sourcemaps for each android dist to its own release

---

src/js/backend.ts

Adds missing `enableAutoSessionTracking` type to `ReactNativeOptions` interface.
This fixes #879 . The definition was missing in the `1.4.0` update

Add enableAutoSessionTracking to ReactNativeOptions interface

---

CHANGELOG.md
src/js/wrapper.ts

Fixes #882
Fixes #883
Filters out `beforeSend`, `beforeBreadcrumb`, `integrations`, `defaultIntegrations`, and `transport` before sending the options object to native.
Some options weren't filtered out which were functions such as `beforeBreadcrumb` which would crash apps on startup.
All tests passing, tested on Android and iOS simulators.

fix: Filter out all init options that would crash native

---

CHANGELOG.md
RNSentry.podspec
android/src/main/java/io/sentry/RNSentryModule.java
ios/RNSentry.m
sample/ios/Podfile.lock
src/js/sdk.ts

Added a new tag `event.origin` to events with values
- `javascript`
- `ios`
- `android`
Along with an `event.environment` tag for native android events with values:
- `java`
- `native`
These tags are attached onto the event in the `beforeSend` function in both iOS and Android and determined using the SDK name. On javascript, the event is added to the scope on init.
This change allows users to easily determine, search, and filter where the event originated in react native apps with native code running alongside javascript.
We use the simplified tag values above instead of the SDK names such as `sentry.java.android` or `sentry.javascript.react-native` as the goal is to make it easy to search and filter for the end-user.
Tested using the sample app by testing all the options, and confirmed …

Add event tags so users can easily determine and filter where events originate from.

---

CHANGELOG.md
RNSentry.podspec
ios/RNSentry.m
sample/ios/Podfile.lock

We only want to store "fatal" events in Release mode to make sure we use fewer resources. We can't rely on always sending it. That means after a restart we will pick up the event and send it.
Potential fix for https://github.com/getsentry/sentry-react-native/issues/911 in combination with https://github.com/getsentry/sentry-cocoa/pull/571

fix: We only store the event in release mode

---

CHANGELOG.md
src/js/backend.ts
src/js/wrapper.ts
test/wrapper.test.ts

Fix the native wrapper not checking for `enableNative` option in the init options. Also does not display the warning to use `enableNative: false` if it is already set to false.
Addresses https://github.com/expo/sentry-expo/issues/112#issuecomment-639845260
Also #920
Ran on both iOS and Android simulators that no warnings/errors appear when setting scope, or any of the functions in the sample app with either `enableNative:false` and `enableNative:true`. All events show up on sentry.io other than the native crash which is disabled.

fix: Fix Native Wrapper not checking enableNative setting

---

CHANGELOG.md
package.json
sample/App.js
src/js/index.ts
src/js/interactionevents.tsx
src/js/touchevents.tsx
tsconfig.build.json
tsconfig.json

By wrapping the root component (or any part of the component tree if they really need to) with the `TouchEventBoundary` it would capture any touch events performed on any component and log either the component tree or a component with a `static displayName` property set. Also exported as a Higher-Order-Component for convenience as `withTouchEventBoundary`.
Note: If you look at the code for this, it uses `e._targetInst` which is not documented at all and not mentioned officially anywhere, so this could be a potential issue if the event payload ever changes without notice.
Example:
```js
import * as Sentry from '@sentry/react-native';
...
// Application root
render() {
return (
<Sentry.InteractionEventBoundary>
<App />
</Sentry.InteractionEventBounaary>
)
}
...
// Some child component …
```

feat: Track touch events as breadcrumbs

---

CHANGELOG.md
src/js/sdk.ts

Fixes a bug where we append the `app:///` prefix to calls to native code `[native code]`
This was causing event grouping issues which spams users with emails. (Of which brought me here)

fix: Fix appending app:/// prefix to [native code]

---

CHANGELOG.md
src/js/touchevents.tsx

Currently we only log the whole touch component tree when we couldn't find a component with a `displayName` set. This changes it so the component tree is logged every time:
This was done because we can't be sure which components have a `displayName` set. Any component from any library can have it set, looking at an example issue here: https://github.com/getsentry/sentry-react-native/issues/950 where it looks like the user is using an Svg library where they have a component with the `displayName` set to `Svg` and it doesn't log the user's component. It would be useful to just log the whole tree in the case that the touch event runs into a component with a `displayName` not set by the user.
Tested on sample app and verified on `sentry.io` dashboard.

feat: Log the component tree to all touch events, not just ones without a component with displayName.

---

CHANGELOG.md
src/js/sdk.ts

Adds back in the check to not prefix `app:///` to stack trace frames "native".
Found a case where a stack trace frame could be "native" instead of "[native code]" (#951) and we shouldn't be prefixing `app:///` to it
**Note:** I have yet to be able to reproduce a stack trace that says `native` instead of `[native code]` or have any idea where it's coming from, but we shouldn't be prefixing it anyways.

fix: Don't prefix app:/// to "native" filename as well

---

CHANGELOG.md
babel.config.js
package.json
src/js/touchevents.tsx
test/touchevents.test.tsx
yarn.lock

Rename `ignoredDisplayNames` to `ignoreNames` and apply it to ignore both `displayName`s and `name`s in the component tree. Adds support for regular expressions.
Originally was going to "clean" the names of components and remove duplicate names next to each other as well but decided against it as it could remove some information for users who don't use named components such as styled-components or emotion.
After using touch events in production in Tour for a week the touch event breadcrumb's component tree logs were full of useless duplicates and components from random libraries that made it a bit more difficult to see where the touch occurred. 
Wrote new tests but needed new jest config + babel-jest as dev dependencies to support tsx.

feat: Touch events take Regex for ignoreNames & add tests

---

CHANGELOG.md
sample/.flowconfig
sample/android/app/build.gradle
sample/android/build.gradle
sample/android/gradle.properties
sample/android/gradlew
sample/android/gradlew.bat
sample/ios/Podfile
sample/ios/Podfile.lock
sample/ios/sample.xcodeproj/project.pbxproj
sample/ios/sample/AppDelegate.m
sample/metro.config.js
sample/package.json
sample/yarn.lock
src/js/backend.ts
test/backend.test.ts

Use LogBox in `backend.ts` if it exists, otherwise fallback to older `YellowBox`. Also updates the sample app to 0.63.
In React Native 0.63 `YellowBox`[ is deprecated and replaced with](https://reactnative.dev/blog/2020/07/06/version-0.63) `LogBox`. Using the SDK in 0.63 shows annoying warnings: #977
Tested on Sample App running on both `0.62.2` and `0.63.1`

Use LogBox instead of YellowBox in RN 0.63 + Update sample app to RN 0.63.1

---

CHANGELOG.md
src/js/sdk.ts
src/js/wrapper.ts

`DeviceContext` calls into native, which can result in extraneous error logs if the user has already stated they don't want to enable the native SDK. 
I also silenced the console warning if `enableNativeNagger` is false
This is an issue for our integration of `sentry-expo` https://github.com/expo/sentry-expo/issues/120 
Ran `yarn test` and tested in an expo project with sentry, no more bad logs! 🎉

fix: don't initiate DeviceContext if enableNative is false

---

android/build.gradle
src/js/wrapper.ts
test/wrapper.test.ts

Fixes incorrect `sdk_info` spec and bump android to `2.2.2` so it actually is used.

fix: Attach sdk field to envelope header instead of sdk_info

---

src/js/integrations/release.ts
src/js/sdk.ts
test/integrations/release.test.ts

The `release` and `dist` set in the init options are now used over the native build's release. However we keep `setRelease` and `setDist` as legacy methods to support users who currently use it along with users who use `codePush.getMetadata` to set their release later in the session rather than at the start. We will migrate the documentation to prefer setting the release and dist in init options over using `setRelease` and `setDist` and list the downside of using them.
Using `setRelease` and `setDist` does not set the release on the native Android/Cocoa SDKs, causing release health and sessions to be attributed to the build's release. This is not ideal for apps that use custom release versions such as apps with CodePushed bundles. 
Wrote `release.test.ts`
Will be followed up with a docs …

fix: Use the release and dist set in init options over native release

---

CHANGELOG.md
RNSentry.podspec
sample/ios/Podfile.lock

build: Bump sentry-cocoa to 5.2

---

src/js/sdk.ts

the changes i made in https://github.com/getsentry/sentry-react-native/pull/993 result in `deviceContext` not initializing by default, since the default `enableNative:true` isn't set until right after
https://github.com/getsentry/sentry-react-native/pull/993#issuecomment-665649047
existing tests

fix: assign default options before enableNative check

---

ios/RNSentry.m

Setting the log level didn't work, because the switch would always fall through to `kSentryLogLevelNone`.

add missing breaks to log level switch

---

sample/test/e2e.test.ts

Fixes failing end to end tests due to an Xcode update deprecating UIAutomation. Also actually made the timeout 20 minutes as stated in the comment.

fix: Fix failing end to end tests

---

src/js/wrapper.ts
test/wrapper.test.ts

Adds a `_processLevel` method to the native wrapper to convert `Severity.Log` and `Severity.Critical` levels to `Severity.Debug` and `Severity.Fatal` respectively. This method is called in `sendEvent` and `addBreadcrumb` in the native wrapper.
This is to handle this issue for now until we remove these levels from the javascript SDK. This also means that we can remove `Log` and `Critical` from android, @marandaneto.
https://github.com/getsentry/sentry-react-native/issues/1055
Added tests for `_processLevel`

fix: Don't send over Log and Critical levels over native bridge

---

src/js/wrapper.ts
test/wrapper.test.ts

`RNSentry.deviceContexts` is not present on the android module. We shouldn't call it.
https://github.com/getsentry/sentry-react-native/issues/1050
Updated the wrapper tests to include a case for android platform.

fix: Only call native deviceContexts on iOS

---

test/touchevents.test.tsx

Fixes failing touch events test on ci due to mocking `addBreadcrumb` minimal instead of core.

fix: Fix failing touchevents test

---

CHANGELOG.md
package.json
yarn.lock

This bump fixes timestamp offset issues due to issues with `performance.now()` introduced in React Native 0.63
https://github.com/getsentry/sentry-react-native/issues/1004
Relevant PR that fixed the issue:
https://github.com/getsentry/sentry-javascript/pull/2915

build: Bump @sentry/javascript dependencies to 5.24.1

---

CHANGELOG.md
package.json
yarn.lock

Checks that `performance` actually exists (doesn't exist in RN <0.63) before calling it.
Fixes #1090 and #1089

build: Bump @sentry/javascript dependencies to 5.24.2

---

RNSentry.podspec

According to https://github.com/facebook/react-native/issues/29633#issuecomment-694187116 - "React pod is in fact really only an umbrella dependency for pure JS applications to depend on, whereas the native APIs that these libraries rely on actually reside in the React-Core pod." This PR updates the dependency from `React` to `React-Core`.
Xcode 12 fails to build if a module depends on React instead of React-Core. 
More info: https://github.com/facebook/react-native/issues/29633#issuecomment-694187116
Use this branch to install with an app running on Xcode 12 or Xcode11. Both versions will work.

fix: xcode 12 compatibility

---

CHANGELOG.md
package.json
src/js/version.ts
src/js/wrapper.ts
test/wrapper.test.ts
yarn.lock

Should only log the warning if the `enableNativeNagger` flag is _truthy_. Also, since the `wrapper` test doesn't get the default options provided [here](https://github.com/getsentry/sentry-react-native/blob/master/src/js/sdk.ts#L40-L43), I added the `enableNativeNagger: true` option to the test. 
in https://github.com/getsentry/sentry-react-native/commit/93dfe7931847b190b467ad8537deaeea90412765 I did this wrong
Tested locally

fix: flip `enableNativeNagger` check

---

sentry.gradle

The `SentryUpload` task was added to disabled bundle tasks, and it would fail when running `assemble` or `install`.
See [this issue](https://github.com/getsentry/sentry-react-native/issues/1142).
I've tested it on a react native application I'm working on.
Now `./gradlew assembleCustom` (where custom is a debug variant) does not fail, while `./gradlew assembleRelease` still works.

don't run SentryUpload on disabled bundle tasks

---

.vscode/launch.json
.vscode/settings.json

Add `launch.json` configuration and a setting to allow the react native tools vscode extension to work with the repo. This allows us to attach a debugger to the react native dev server.

meta: Add react native tools vscode settings to attach debugger to RN

---

src/js/wrapper.ts
test/wrapper.test.ts

Serialize the envelope `payload` before sending it across the native bridge on iOS. This will remove class instances that will crash the native bridge such as spans. This is needed before the next tracing PR that will follow this soon.
Tested on sample app running on iOS emulator. Added tests to test class instance serialization. Includes a test for Android as well for good measure.

fix: Serialize envelope payload when sending event on iOS

---

CHANGELOG.md
RNSentry.podspec
ios/RNSentry.m
sample/ios/Podfile.lock

Remove private imports from sentry-cocoa and call storeEnvelope on the client instead of through fileManager like before.
Users were having issues with `use_frameworks!` in their Podfile.
https://github.com/getsentry/sentry-react-native/issues/1171
Confirmed that the app builds with the `use_frameworks!` tag in the Podfile. Tested that unhandled fatal errors are still stored and sent as needed.

fix(ios): Bump sentry-cocoa to 6.0.8 and remove private imports 

---

CHANGELOG.md
package.json
yarn.lock

Routine bumping of sentry-js dependencies. Tested on sample app.

build(deps): Bump @sentry/javascript deps to version-locked 5.27.4

---

CHANGELOG.md

The Changelog contains several markdown lint warnings `MD034 - Bare URL used`. This is fixed now.
It's a Changelog

docs: Fix MD034 Bare URL used in Changelog

---

dangerfile.js

Fixes danger action checking for a PR link when we only use the PR number

meta: Danger should only check for PR Number, link not needed

---

package.json
src/js/index.ts

Import `@sentry/tracing` and expose `startTransaction`. Or should we only expose `startTransaction` and have users manually install and import `@sentry/tracing`?
Following this up with a PR for a new sample app that showcases tracing.

feat: Include @sentry/tracing and expose startTransaction

---

CHANGELOG.md
android/src/main/java/io/sentry/RNSentryModule.java
sample/src/App.tsx

These will keep coming.. 
We can take a map on Android, similarly as we do on iOS:
https://github.com/getsentry/sentry-java/issues/1117

fix: max breadcrumbs android

---

CHANGELOG.md
src/js/options.ts
src/js/sdk.ts
src/js/wrapper.ts
test/wrapper.test.ts

Allows the user to disable the initialization of the Native SDK in the case that they already have one initialized themselves. We do this by adding the `shouldInitializeNativeSdk` key to `ReactNativeOptions`. This is not breaking as it will default to `true`.
User has an app that is extensively native iOS and the React Native section is only run way later: https://github.com/getsentry/sentry-react-native/issues/1248
Wrote a new test in `wrapper.ts`.
Should add documentation on this option.

feat: Allow disabling native SDK initialization but still use it

---

CHANGELOG.md
src/js/wrapper.ts
test/wrapper.test.ts

Don't set `type: "event"` on the envelope payload if it is `undefined`.
`"event"` is not a valid value for `type` in the envelope payload: https://github.com/getsentry/sentry-data-schemas/blob/main/relay/event.schema.json#L1194-L1206
Fixes #1174 where events sent from android have an `unknown` key.
Changed the existing tests to expect the payload type to be empty if none is present in the event.

fix: Only set "event" type in envelope item and not the payload

---

CHANGELOG.md
src/js/integrations/debugsymbolicator.ts

If `parseErrorStack` throws when passed the full error object we catch it and try again but only with the stack.
In 0.64-rc.1 and above, the internal React Native method that we use to parse error stacks while in debug mode with `DebugSymbolicator` was changed to only accept strings: https://github.com/facebook/react-native/commit/9edfc43aad2f68be8a37c916779681cd9ad13fee
Sending any event from the SDK will throw an error: https://github.com/getsentry/sentry-react-native/issues/1262#issuecomment-754047470
Working on iOS simulator running React Native 0.64-rc.2 with hermes enabled.

fix: Fix parseErrorStack that only takes string in DebugSymbolicator event processor

---

CHANGELOG.md
src/js/options.ts
src/js/sdk.ts
src/js/wrapper.ts
test/wrapper.test.ts

Renames the option introduced in #1259 from `shouldInitializeNativeSdk` to `autoInitializeNativeSdk`.
https://github.com/getsentry/sentry-react-native/issues/1273#issuecomment-755766836
Updated the existing test to test for `autoInitializeNativeSdk`

ref: Rename shouldInitializeNativeSdk to autoInitializeNativeSdk

---

CHANGELOG.md
ios/RNSentry.m

Add a default envelope item type to be "event" on the iOS side of the native bridge.
When we removed the item type from the payload in this PR: https://github.com/getsentry/sentry-react-native/pull/1271 for Android, this caused a regression in iOS where envelopes were discarded. This is because on iOS we took the item type from the payload which is different than on Android.
Ran iOS simulator and passing e2e tests

fix: Add fallback envelope item type to iOS

---

CHANGELOG.md
android/build.gradle

Bump `sentry-android` to version 3.2.1
Includes this fix https://github.com/getsentry/sentry-java/pull/1064 that pertains to RN on Android where it includes an exception from the `FileObserver.java` which is where the SDK reads the envelope and not relevant to the user event.
Tested on Android emulator, sent an event, made sure that the above issue was fixed.

build(android): Bump `sentry-android` to 3.2.1

---

CHANGELOG.md
RNSentry.podspec
ios/RNSentry.m
sample/ios/Podfile.lock

Posts a `SentryHybridSdkDidBecomeActive` notification once if the app is active, on iOS SDK init to start a session on iOS.
https://github.com/getsentry/sentry-react-native/issues/1292
Tested on sample app and verified that sessions get sent on initial app launch.

fix: Handle auto session tracking start on iOS

---

CHANGELOG.md
src/js/tracing/reactnavigationv4.ts
src/js/tracing/reactnavigationv5.ts
test/tracing/reactnavigationv4.test.ts
test/tracing/reactnavigationv5.test.ts

On V5, the initial blank transaction is now set on the routing instrumentation register instead of the navigator mount, this way it gets set on the scope before the app component is mounted. Then, once the navigator is mounted, `beforeNavigate` is called, and the transaction on the scope is updated with the new context.
On V4, the same strategy is adopted as V5. This means that now V4 has the option of updating a transaction on the scope instead of just setting a new one. For V4 however, this behavior is only used on the initial transaction and nothing is changed by this PR for subsequent route changes.
```js
// Root App component
React.useEffect(() => {
// This gets called before the next useEffect block, however, the transaction will already exist
const transaction = …
```

fix: React Navigation Instrumentation starts initial transaction before navigator mount

---

sample/ios/Podfile
sample/ios/sample/AppDelegate.m
sample/package.json
sample/test/e2e.test.ts
sample/yarn.lock

This PR fixes the failing e2e tests we've been having on iOS.
We never used [Flipper](https://fbflipper.com) in our sample app, so I removed it as it was causing problems with our e2e test build. It was there in the first place as it was included by default in React Native templates.
Bumps `appium` to 1.20.2,
Bumps `wd` to 1.14.0

fix: Removing Flipper from sample app and bump Appium to 1.20.2

---

dangerfile.js

This way we stop getting spammed by failed CI on every dependabot PR due to no changelog.
Reference: https://danger.systems/js/reference.html#GitHubUser

meta: Disable changelog requirement on Danger for PRs created by bots

---

CHANGELOG.md
sample/src/screens/EndToEndTestsScreen.tsx
sample/src/screens/HomeScreen.tsx
sample/test/e2e.test.ts
src/js/integrations/reactnativeerrorhandlers.ts

Because of a [version mismatch in the Promise version](https://github.com/facebook/fbjs/pull/413) used in `react-native` and `fbjs` the promise patching we perform is patching the incorrect one, so the hacky fix is to overwrite global promise's methods (if they exist).
https://github.com/getsentry/sentry-react-native/blob/b1de06bbb0d8f45e98340d3cdae02692ba63879f/src/js/integrations/reactnativeerrorhandlers.ts#L90-L105
Fixes #1077 
Added a new e2e test for unhandled promise rejections. Ran iOS locally but please wait for it to run CI on this PR to confirm.
We should add a matrix to our e2e CI to test on multiple react native versions as although the code block shown in the description is very defensive to prevent issues, we should still have a way to make sure.

fix: Fix unhandled promise rejections not being tracked

---

.github/workflows/release.yml

Fixes the issue we've been having with the release branch created by craft not running CI. Simplifying the release's dependency install step fixed the issue over at the Cordova repo.

ci(release): Simplify dependency install step

---

CHANGELOG.md
sample/src/App.tsx
src/js/tracing/reactnavigationv4.ts
src/js/tracing/reactnavigationv5.ts
test/tracing/reactnavigationv4.test.ts
test/tracing/reactnavigationv5.test.ts

In an attempt to find causes of routing transactions not being sampled. I ended up finding multiple edge cases for routing transactions to not be sent. Below are the list and explanations for what I found. Sorry in advance that this description is especially long:
1. If the Instrumentation gets the navigation container registered before the integration’s `setupOnce` is called. So it tries to update the state of the initial route’s transaction which does not yet exist. When the integration is setup and it registers the routing instrumentation, which triggers the `_onDispatch` to be called and creates the initial blank transaction, the state is never set and the timeout to not sample is never cancelled, so the transaction ends up not being sampled.
- **Status**: Done
- Fix:
- Add a …

fix(performance): Handle edge cases in React Navigation routing instrumentation

---

CHANGELOG.md
sample/src/App.tsx
src/js/tracing/reactnavigationv4.ts
src/js/tracing/reactnavigationv5.ts
test/tracing/reactnavigationv4.test.ts
test/tracing/reactnavigationv5.test.ts

Adds the ability to set the timeout duration where a routing transaction is considered "discarded". The default timeout duration is now set to 1000ms.
This stems from an issue of users having unperformant navigation routes that take longer than the old default of 200ms getting their valid navigation transactions discarded. It makes sense as you're supposed to measure the performance of these route changes.
Resolves #1369 and #1361 
Adds test for both V4 and V5.

feat(performance): Option to set route change timeout in routing instrumentation

---

CHANGELOG.md
sample/src/App.tsx
src/js/backend.ts
src/js/options.ts
src/js/sdk.ts
test/backend.test.ts

Adds a callback `onReady` to be passed as an option to `Sentry.init`. After the native SDK initialization step is finished, this callback is called with an object with property `nativeDidInitialize`. This value is `true` when the native SDK was initialized by the SDK, `false` otherwise.
In these cases:
- `enableNative: false` = onReady called with `{ nativeDidInitialize: false }`.
- `autoInitializeNativeSdk: false` = onReady called with `{ nativeDidInitialize: false }`.
- Error happens when initializing native SDK but JS layer is fine = onReady called with `{ nativeDidInitialize: false }`.
- Error happens when initializing JS layer SDK = onReady **not** called.
Originally was just going to be a callback after the native SDK initialized. But I figured having it still be called with `false` …

feat: Add onReady callback that gets called after Native SDK initialization

---

CHANGELOG.md
src/js/tracing/reactnavigationv4.ts
src/js/tracing/reactnavigationv5.ts

When making integrations for other libraries, to avoid a dependency of the library we usually just define the types inline, however doing so means we have to manually keep them up to date otherwise a new update on the other library could cause new type errors, so I decided to just allow `any` types for the React Navigation container. We check the passed ref and warn the user if it is invalid, so it should be OK to accept an `any` type.
Resolves #1445
Eslint on CI to make sure the types work, and e2e tests to make sure nothing is broken.

fix: Type navigation container ref arguments as any to avoid Typescript errors

---

CHANGELOG.md
src/js/wrapper.ts
test/wrapper.test.ts

Setting both `enableNative: false` and `autoInitializeNativeSdk: false` will now prioritize `enableNative: false`.
Setting both `enableNative: false` and `autoInitializeNativeSdk: false` ignores `enableNative: false` and only considers `autoInitializeNativeSdk` thus it would not initialize the native SDK but not set `NATIVE.enableNative: false`, allowing calls to still be made to the bridge.
Fixes #1461
Added a test for this precedence, also added tests for each of the scope sync methods as well.

fix: enableNative: false should take precedence over autoInitializeNativeSdk: false

---

CHANGELOG.md
android/build.gradle
android/src/main/java/io/sentry/react/RNSentryModule.java
ios/RNSentry.m
sample/src/App.tsx
sample/src/screens/EndToEndTestsScreen.tsx
sample/src/screens/HomeScreen.tsx
sample/test/e2e.test.ts
src/js/client.ts
src/js/index.ts
src/js/sdk.ts
src/js/wrapper.ts
test/wrapper.test.ts

Exposes a new `close` method that closes the SDK. This includes the JavaScript layer and calls down to the native SDK layer.
Although this uses the latest Cocoa SDK `7.0.0`, it still uses Android `4.4.0-alpha.2`.
Resolves #1329 
Added a unit test for the wrapper, and a JS-layer integration test on the e2e test. The test only tests that the eventId is not set by beforeSend. Cannot do a full e2e test there is no way to determine how long to wait for an event to not show up on the dashboard.

feat: Close method to fully disable the SDK on all layers

---

CHANGELOG.md
android/build.gradle
android/src/main/java/io/sentry/react/RNSentryModule.java

Bumps `sentry-android` to `5.0.0-beta.3` and handles the breaking change to `enableAutoSessionTracking`: https://github.com/getsentry/sentry-java/pull/1457
Tested on Android Sample app and ensured that changing the `enableAutoSessionTracking` option effects session tracking.

build(android): Bump Android SDK to 5.0.0-beta.3

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java

Gets the latest outbox path from the hub through `HubAdapter` instead of a private variable like before. This fixes the issue of not having the correct outbox path or not having it entirely if the user decides to init the SDK elsewhere and disabling auto init using `autoInitNativeSdk: false`
Fixes #1516 
Android Sample + e2e tests (waiting)
Maybe release this fix before the beta as `2.4.3`.

fix: Use the latest outbox path from hub options instead of private options

---

CHANGELOG.md
sample/src/screens/HomeScreen.tsx
src/js/index.ts
src/js/sdk.ts
test/sdk.test.ts

Exports a new public `Sentry.flush` method to flush all pending events in the queue to disk and return a promise that can be awaited.
This method should be used and awaited before live-reloading the JS bundle to ensure any events in the queue are properly stored on disk.
User contacted support with an issue regarding missing events when reloading the JS bundle using expo-updates, this would also be applicable to code-push updates.
On sample app and with new tests for `sdk.ts`

feat: Sentry.flush to flush events to disk and returns a promise

---

CHANGELOG.md
src/js/wrapper.ts

Processes `level` in breadcrumbs as well as the native layers do not support the `"log"` level that is used in JS.
Every time a `log` breadcrumb comes through, an error happens and the breadcrumb could've been dropped. Also could've caused duplication seen in #1409?
Related change made for the Capacitor SDK: https://github.com/getsentry/sentry-capacitor/pull/46
Tested on sample app and confirmed through logcat logs. Await for e2e tests on CI.

fix: Process "log" levels in breadcrumbs before sending to native

---

CHANGELOG.md
src/js/integrations/reactnativeerrorhandlers.ts
test/integrations/reactnativeerrorhandlers.test.ts

Fatal uncaught errors sent from the React Native global error handler are now marked `handled: false` alongside `level: "fatal"` with the mechanism type `onerror`.
Uncaught errors that crash the app should be marked `handled: false`. Not doing so meant our sessions might have not correctly been marked as crashed.
This fix is needed before we can tackle #1409.
Tested on Android sample app on both debug and release builds. Written new unit tests.
Land the PR to handle #1409.

fix: Fatal uncaught events should be tagged handled:false

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java
src/js/options.ts

Adds support for `sendDefaultPii` in React Native.
The RN docs stated `sendDefaultPii` was supported but it wasn't in the TypeScript types. I queried this on the Sentry Community Discord[[1](https://discord.com/channels/621778831602221064/750735628932612096/857554081244512267)]. It was a documentation bug[[2](https://discord.com/channels/621778831602221064/750735628932612096/857554424929714198)] but @jennmueng & @bruno-garcia suggested I raise a PR so Sentry could officially support it on RN[[3](https://discord.com/channels/621778831602221064/750735628932612096/857591080367554560)].
There didn't appear to be any unit tests around the areas changed so I manually tested. I couldn't see a debug statement from the iOS/Java SDKs stating whether `sendDefaultPII` was enabled or disabled so I …

Support sendDefaultPii on React Native

---

src/js/integrations/reactnativeerrorhandlers.ts

Fixes a regression caused by #1597 that caused the default error handler (the red box dialog) not to be shown in dev mode.
Customer issue raised in slack.
iOS simulator.

fix: Fix the error handler (error dialog) not called in dev

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java
ios/RNSentry.m
src/js/definitions.ts
src/js/index.ts
src/js/integrations/eventorigin.ts
src/js/integrations/index.ts
src/js/integrations/sdkinfo.ts
src/js/sdk.tsx
src/js/wrapper.ts
test/integrations/eventorigin.test.ts
test/integrations/sdkinfo.test.ts

Aligns the values for `event.origin` and `event.environment` with what we have on other Hybrid SDKs such as capacitor, cordova, and flutter.
Possible values:
- **event.origin**: `android`, `javascript`, `ios`,
- **event.environment**: `java`, `native`, `javascript`
Adds the `SdkInfo` integration so we now add the sdk package info of the native sdks to the event.
Part of #1701 
Wrote unit tests for each of the integrations + tested them on both ios and android sample apps.

feat: Align event.origin, event.environment and sdk info with other hybrid sdks

---

CHANGELOG.md
src/js/tracing/nativeframes.ts

Native frames were "timing out" due to when we moved the integration's self exist check out of the event processor and into the constructor. The instrumentation did not exist yet at that time so the check should be done in the event processor.
Tested on both iOS and Android sample apps

fix: Fix native frames not being added to transactions

---

CHANGELOG.md
RNSentry.podspec
android/build.gradle

Bumps sentry-cocoa to 7.2.6 and sentry-android to 5.1.2
We should use the latest GA'd versions of the native sdks for the RN SDK's GA.
Sample app on both emulators + see e2e tests

build: Bump sentry-cocoa to 7.2.6 and sentry-android to 5.1.2

---

package.json

This moves the dependency `@sentry/wizard` to a `devDependency` of `sentry-react-native`.
We noticed that `@sentry/wizard` was bringing in `lodash` as a dependency to our React Native project. Since the wizard is only intended to be a development tool, it seemed appropriate to make it a `devDependency` instead.
I didn't test it, given the nature of the PR. If you want me to spin up the sample app I can, but it doesn't really make a lot of sense to do that.
Discuss ... and merge if cool!

fix: Move @sentry/wizard dependency to devDependency

---

CHANGELOG.md
android/build.gradle

fixed #1762
after updating new version,  android is build is crashing with this error
```
project1/node_modules/@sentry/react-native/android/src/main/java/io/sentry/react/RNSentryModule.java:86: error: lambda expressions are not supported in -source 7
SentryAndroid.init(this.getReactApplicationContext(), options -> {
^
(use -source 8 or higher to enable lambda expressions)
1 error
FAILURE: Build failed with an exception.
```
by running build on android

Fix: Set Java 8 for source and target compatibility if not using AGP >= 4.2.x

---

CHANGELOG.md
src/js/index.ts
src/js/tracing/index.ts
src/js/tracing/reactnavigation.ts
test/tracing/reactnavigation.test.ts

Rename the React Navigation V5 instrumentation by removing the V5 prefix as the same instrumentation supports both V5 and V6. We still export the `reactNavigationV5Instrumentation` for backwards compatibility purposes with a `@deprecated` tag.
Resolves #1756 
Tested on an example app with React Navigation 6.
- Update docs: https://github.com/getsentry/sentry-docs/pull/4134
- Add the React Navigation V6 example to the [examples](https://github.com/getsentry/examples) repo. Waiting for a release to be made with this PR so the example can have the correct imports.

ref: Remove v5 prefix from react navigation instrumentation to support v6

---

CHANGELOG.md
RNSentry.podspec
ios/RNSentry.m

Closes https://github.com/getsentry/sentry-react-native/issues/1864
running with sampler

fix(ios): tracesSampler becomes NSNull in iOS and the app cannot be started

---

CHANGELOG.md
src/js/integrations/reactnativeerrorhandlers.ts

Fixes a fatal bug caused by the SDK trying to make an inline dynamic require to a file that does not exist on older RN versions. Although the require is inside a try-catch block, the metro bundler's dependency magic, in trying to optimize dependencies, ignores the try catch statement.
Metro added the optional dependency feature in version 0.59, so having a dynamic require statement inside a try catch is not feasible for users on prior versions, **however** we can get around metro's dependency magic by defining the name of the dependency as a string variable, and instead, we pass it into `require.call`.
Fixes #1922 
Tested on an RN app running `react-native: 0.63.1` and `metro: 0.58.0` (before the optional dependency feature was added in 0.59).
E2E tests passing

fix: Fix dynamic require for promise options ignoring try catch

---

CHANGELOG.md
sentry.gradle

Instead of hardcoding the path to @sentry/cli when an executable path is not provided we can use node to get the path instead.
This is the technique used by expo libraries to get the path to where js deps are installed.
Tested locally in an app inside a monorepo

Support monorepo in gradle android plugin

---

CHANGELOG.md
src/js/integrations/reactnativeerrorhandlers.ts

by @jennmueng -> the simplest solution is to remove the dependency on react-native/Libraries/promiseRejectionTrackingOptions altogether. All it does is to prettify the promise rejection error message, before my PR we didn't prettify the message. This is causing more issues than it's worth.
Fixes #1927

fix: Remove dependency on promiseRejectionTrackingOptions

---

CHANGELOG.md
src/js/tracing/reactnavigationv4.ts

fix: ReactNavigationV4Instrumentation null when evaluating 'state.routes'
Closes https://github.com/getsentry/sentry-react-native/issues/1454

fix: ReactNavigationV4Instrumentation null when evaluating 'state.routes'

---

.github/workflows/e2e.yml
sample/.gitignore
sample/package.json
sample/test/e2e.test.ts
sample/yarn.lock

The Appium server's build step for the WebDriverAgent (WDA) was either failing without any logs or hanging after the default iOS deployment target was switched from 14.4 to 15.0 on Github Actions. Attempts to obtain logs from the build step with `showXcodeLog` repeatedly failed. 
The solution is to disable the Appium server from building the WDA (`usePrebuiltWDA: true`) and instead build it ourselves as a step of the workflow. Also updates the iOS e2e tests to test on iPhone 13 instead of iPhone 12.
Fixes failing iOS e2e tests.
Ran here on CI.

test(e2e): Fix ios e2e tests

---

CHANGELOG.md
src/js/options.ts

Deprecate initialScope in favor of configureScope
Closes https://github.com/getsentry/sentry-react-native/issues/1925
Remove in the next major version

Deprecate initialScope in favor of configureScope

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java

fix: Do not crash if androidx.core isn't available on Android
Docs: https://github.com/getsentry/sentry-docs/pull/4517
If AndroidX isn't in the classpath and slow/frozen frames are enabled, that might crash the App.
https://docs.sentry.io/platforms/android/performance/instrumentation/automatic-instrumentation/#androidx-support

fix: Do not crash if androidx.core isn't available on Android

---

CHANGELOG.md
sample/package.json
src/js/integrations/reactnativeerrorhandlers.ts
src/js/options.ts
src/js/sdk.tsx
test/integrations/reactnativeerrorhandlers.test.ts

Instead of warning the user and requiring them to set the Promise library resolution, we instead polyfill the global promise library to ensure we can install our handler.
Adds a new option `patchGlobalPromise` that can be passed to either `Sentry.init` or the `ReactNativeErrorHandlers` integration.
There is the expectation that a third party SDK shouldn't have the side effect of polyfilling a commonly used global instance, but as RN has not changed the functionality of its promises for quite a while we should be fine. If you use a polyfill such as core-js for example, such as adding `Promise.allSettled`, they would have to use the polyfill after Sentry init. We can also add back in the Promise warning along with a boolean toggle for people who do not want to polyfill.
Resolves #1942 …

fix: Polyfill the promise library to permanently fix unhandled rejections

---

CHANGELOG.md
ios/RNSentry.m

fix: fetchNativeDeviceContexts returns an empty Array if no Device Context available
Avoid crash https://github.com/getsentry/sentry-react-native/issues/1999
Running it without initing the SDK
Investigate why `fetchNativeDeviceContexts` returned null in the first place.

fix: fetchNativeDeviceContexts returns an empty Array if no Device Context available

---

CHANGELOG.md
package.json
yarn.lock

Adds `@sentry/wizard` back in as a direct dependency.
Sentry wizard is called after running `react-native link @sentry/react-native` in older versions of RN before 0.60. As it is currently not a direct dependency, an error is thrown.
Tried in a blank empty project

fix(deps): Add `@sentry/wizard` back in as a dependency

---

CHANGELOG.md
src/js/tracing/reactnavigation.ts
test/tracing/reactnavigation.test.ts

When multiple navigation actions are dispatched before the `routeChangeTimeoutMs`, and the state does not change occur for a prior action, the transaction is not cancelled and sent with the blank "Route Change" transaction context. This change makes sure any navigation transaction that had a successful navigation state change is removed from the instrumentation (it'll still be present on the scope until finished) and any new navigation action dispatch will **cancel** any prior waiting transactions to ensure they won't be sent when they don't have a successful state change.
Fixes #2051 
Added a jest test where multiple navigation actions were dispatched in a row
As we did not recieve a reproduction, need to ask customer to see if bug is fixed.

fix: Discard prior transactions on react navigation dispatch

---

CHANGELOG.md
ios/RNSentry.m
sample/ios/sample.xcodeproj/project.pbxproj

Fix passing mutable options to iOS SDK
Not passing `tracesSampleRate` leads to https://github.com/getsentry/sentry-cocoa/issues/1657
Passing a JS `tracesSampler` leads to a crash.
https://github.com/getsentry/sentry-cocoa/issues/1657

Fix passing mutable options to iOS SDK

---

CHANGELOG.md
ios/RNSentry.m

Instead of using a build flag of #DEBUG the code should respect the variable set by user in the sentryOptions.debug.
We have are putting a pretty large payload into our context, it is filling up our logs and we have to go comment out the` NSLog("Contexts: %")` in our code to get around this. 
I didnt 🤷 
Decide if you want it or not. This is a Take it or leave it PR, I won't be doing followup changes.

Respect sentryOption.debug setting instead of #DEBUG build flag for outputting logs

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java
sample/src/App.tsx
src/js/options.ts

feat: Support setting maxCacheItems
https://github.com/getsentry/sentry-react-native/issues/1452

feat: Support setting maxCacheItems

---

CHANGELOG.md
src/js/tracing/reactnativenavigation.ts
test/tracing/reactnativenavigation.test.ts

The transaction is not cleared on a route change confirm in the React Native Navigation instrumentation so a subsequent call to `onComponentWillAppear` will overwrite the existing transaction context. Potentially fixes #2066, however I was not able to reproduce the exact behavior. 
Add a unit test and test with React Native Navigation example app.
Check with customers if this fixes the issue.

fix: Clear transaction on route change for React Native Navigation

---

CHANGELOG.md
ios/RNSentry.m
src/js/integrations/devicecontext.ts

Missing userId on iOS when userId is not set
Similar to https://github.com/getsentry/sentry-dart/pull/782
Running on Android and iOS

Missing userId on iOS when the user is not set in the Scope

---

CHANGELOG.md
sentry.gradle

This PR causes no changes for anyone not building multiple APKs.
It also causes no changes for anyone building multiple APKs and giving
them each a distinct `versionCode`, as the React Native template app
does.
What it does affect is building multiple APKs and giving each of them
the same `versionCode`: currently this causes sentry.gradle to crash,
and with this commit it instead uploads correctly.
The crash in sentry.gradle comes because we're naming the upload task
based on the version code, and Gradle task names must be unique.  We
can fix it by simply not attempting to create a task if it would be a
duplicate.  To be exactly correct, we have the task name include the
release name as well as the version code: when both of these are the
same, the two tasks would run exactly the same …

fix: Upload correctly regardless of version codes

---

android/src/main/java/io/sentry/react/RNSentryModule.java
src/js/options.ts

Remove shutdownTimeout since BrowserOptions already have it
Already exists on JS https://github.com/getsentry/sentry-javascript/blob/38278210118576d041117e11e2bd6507677625f6/packages/types/src/options.ts#L104-L111

Remove shutdownTimeout since BrowserOptions already have it

---

CHANGELOG.md
src/js/wrapper.ts
test/wrapper.test.ts

Duplicate Breadcrumbs when captuing messages 
Closes https://github.com/getsentry/sentry-react-native/issues/1409

Duplicate Breadcrumbs when captuing messages

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java
src/js/wrapper.ts

setContext serializes as Context for Android instead of Extra
Found by debugging https://github.com/getsentry/sentry-react-native/issues/2154

setContext serializes as Context for Android instead of Extra

---

CHANGELOG.md
sample/src/App.tsx
src/js/integrations/release.ts
test/integrations/release.test.ts

If you pass the `release`, it respects the given release.
If you pass the `dist`, it respects the given dist.
If you pass `release` but not `dist`, the `dist` from the Native SDK is used, and vice versa.
If you pass `release` to SDK init but not `dist`, the `release` isn't respected and it's used the Native `release`.

fix: Respect given release if no dist is given during SDK init

---

CHANGELOG.md
src/js/touchevents.tsx

Make the second argument to withTouchEventBoundary optional instead of required.
Fixes https://github.com/getsentry/sentry-docs/issues/4910
Local sample app

fix: Make withTouchEventBoundary options optional

---

CHANGELOG.md
ios/RNSentry.m

By conditionally compiling some of the more advanced functionality the SDK now compiles on react-native-macos applications. Don't know how the commented functionality works, XCode was simply throwing errors on the methods, which I guess are not exposed/defined based on platform checks too.
I need react-native-macos support for my applications. The commented functionality (performance tracking) is not vital for my use case, for now getting the errors is better than nothing.
I built my own [app](https://ospfranco.com/sol) with support and the events are being received on Sentry. Not sure how to add tests for the macOS target though, since I didn't change any functionality not sure if this is necessary.
- [] I added tests to verify changes
Please review, let me know if you **need** me to add …

MacOS support

---

CHANGELOG.md
src/js/client.ts

This fixes the warning that it was missing the DSN, despite being set by the user,

Add missing DSN to BrowserClient

---

CHANGELOG.md
src/js/tracing/reactnativetracing.ts
test/tracing/reactnativetracing.test.ts

Filter out app start with more than 60s
https://github.com/getsentry/sentry-react-native/issues/2295

Filter out app start with more than 60s

---

CHANGELOG.md
sentry.gradle

https://github.com/getsentry/sentry-react-native/issues/2309

Fix Calculate the absolute number of Android versionCode

---

.github/workflows/update-deps.yml
scripts/update-android.sh
scripts/update-cocoa.sh
scripts/update-javascript.sh
scripts/update-package-json.sh
scripts/update-wizard.sh

see https://github.com/getsentry/team-mobile/issues/20

chore: dependency updater

---

CHANGELOG.md
src/js/sdk.tsx
test/sdk.test.ts

SDK overwrites the user-defined ReactNativeTracing and because of that, slow and frozen frames are not reported.
Fixes https://github.com/getsentry/sentry-react-native/issues/2317
Bug introduced by https://github.com/getsentry/sentry-react-native/pull/2250 likely because `ReactNativeClientOptions` does not have a `defaultIntegrations` anymore.
Running and unit test

Fix: SDK overwrites the user defined ReactNativeTracing

---

CHANGELOG.md
ios/RNSentry.m

The OOM code of the Cocoa SDK also relies on the
SentryHybridSdkDidBecomeActive to work properly.
If a user has enableAutoSessionTracking disabled wrong
OOM events would be created.
Came up when investigating https://github.com/getsentry/sentry-cocoa/issues/1852.
Hard to test as there are no unit tests for this.

Send DidBecomeActiveNotification when OOM enabled

---

.github/workflows/update-deps.yml
package.json
scripts/update-cli.sh

closes #2305 via the next PR that would be created after this is merged
ideally, there should be tests first, but I wanted to get this PR off my mind (and hit the checkbox in https://github.com/getsentry/team-mobile/issues/20)

chore: auto-update sentry-cli

---

CHANGELOG.md
sentry.gradle

Fixes https://github.com/getsentry/sentry-react-native/issues/2322
`System.getenv("SENTRY_DIST")` returns a String and fails to `Math.abs`

When using SENTRY_DIST env. var. on Android, SDK fails to convert to an Integer

---

ios/RNSentry.m

Solved a reference to a private cocoa SDK class that keeps projects from compiling when using cocoa pods and dynamic libraries.
close #2353 

fix: Solve reference to private cocoa SDK class

---

CHANGELOG.md
sample/yarn.lock
sentry.gradle

https://github.com/getsentry/sentry-react-native/discussions/2394
Running

SENTRY_DIST accepts non-number values on Android

---

CHANGELOG.md
src/js/client.ts
test/client.test.ts

I've updated the ReactNativeClient constructor to first check if `options.transport` is provided and if so - then it takes it and calls to `super(options)`. If `options.transport` not provided then keep the previous logic and conduct react-native transport layer and then calls to `super(options)`.
this resolves issue #2397 
I've added a test which gets the given custom transport layer and then runs and validates the customized `send` and `flush` functions.

should not ignore `options.transport` function provided in `Sentry.init(...)`

---

CHANGELOG.md
src/js/tracing/reactnativetracing.ts

ReactNativeTracing wrongly marks transactions as deadline_exceeded when it reaches the idleTimeout
Bug was introduced when migrating the JS SDK to v7
Fix https://github.com/getsentry/sentry-react-native/issues/2426

ReactNativeTracing wrongly marks transactions as deadline_exceeded when it reaches the idleTimeout

---

package.json

`wizard` was added back in as a dependency because of https://github.com/getsentry/sentry-react-native/pull/2015
on v5, we don't support RN < 0.69 so it's not a problem anymore.
Fix https://github.com/getsentry/sentry-react-native/issues/2409

Move `wizard` to dev dep

---

.github/workflows/update-deps.yml

One notable difference this brings is the "PR Stragegy" change from "creating new PRs for each dependency, while old unmerged PRs stay untached" to "update the same PR until finally merged". This will require existing open PRs for the affected dependencies to be closed (& branches deleted) or merged. It's OK to merge this even without doing the change, but then the updater workflow will fail.

ci: bump updater to v2

---

CHANGELOG.md
src/js/tracing/reactnativenavigation.ts
src/js/tracing/reactnavigation.ts
src/js/tracing/reactnavigationv4.ts
src/js/tracing/utils.ts
test/tracing/reactnativenavigation.test.ts
test/tracing/reactnavigation.test.ts
test/tracing/reactnavigationv4.test.ts

I've added default `view` source for all the integration, which can be overwritten by the user.
I've picked `view` as its description fitted the most to what it actually is. Example `Home`, `Menu`, `ProfilePage` etc.
https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations
At the moment the source is always `custom`, because we first create empty transaction and then update it with the correct route data, which causes the source to be set as `custom`.
https://github.com/getsentry/team-mobile/issues/46
🚨 To be done when sentry backend will allow dynamic sampling for React Native.

Add transaction source for dynamic sampling

---

CHANGELOG.md
src/js/tracing/reactnativetracing.ts

https://github.com/getsentry/sentry-react-native/blob/b6fe2890eedc3c6f66e1f75d5fab6653106ec889/src/js/tracing/reactnativetracing.ts#L42-L49 `maxTransactionDuration` is documented as in `seconds`.
https://github.com/getsentry/sentry-javascript/blob/fbd4ef07dd4248a1a9f8a80e0c220628a663f91c/packages/tracing/src/idletransaction.ts#L79-L87
defines both values in `ms`
When passing the values to the idle transaction, we need to convert the one in seconds to milliseconds
https://github.com/getsentry/sentry-react-native/blob/b6fe2890eedc3c6f66e1f75d5fab6653106ec889/src/js/tracing/reactnativetracing.ts#L363-L364
https://github.com/getsentry/sentry-react-native/issues/2468
https://github.com/getsentry/sentry-react-native/issues/2467

maxTransactionDuration should be ms when passing to startIdleTransaction

---

CHANGELOG.md
src/js/sdk.tsx
test/sdk.test.ts
test/testutils.ts

I mainly wrote tests to lock in the behaviour of `integrations` and `defaultIntegrations` attributes of the Sentry.init function.
Fix: https://github.com/getsentry/sentry-react-native/issues/2462
Sample app, unit tests

fix(init): Integrations factory gets default integrations

---

.github/workflows/e2e.yml
.gitignore
sample/test/e2e.test.ts
sample/utils/fetchEvent.ts
test/tracing/stalltracking.test.ts

Trying to improve e2e tests & their reliability:
Current reliability as tested by running with `tmpVal: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]` in the matrix.
To improve the Android reliability, I'll have a look if adding some retry logic to `reactivecircus/android-emulator-runner` is doable (in a fork).
As is, this PR already has some improvements and cleans up the CI so I'd suggest merging already.

CI: improve e2e tests

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java
src/js/client.ts
src/js/sdk.tsx
src/js/utils/envelope.ts
src/js/utils/outcome.ts
test/client.test.ts
test/testutils.ts

If clientReport exists it will be send with the next envelope.
Closes: https://github.com/getsentry/sentry-react-native/issues/2034
Unit tests, sample app, checked the client dropped in the graph

feat(sdk): Add ClientReports

---

CHANGELOG.md
src/js/index.ts
src/js/sdk.tsx
test/client.test.ts
test/sdk.test.ts
test/testutils.ts

The `configureScope` wasn't safe to execute.
Missed in https://github.com/getsentry/sentry-react-native/issues/2499

fix(callbacks): Fix configureScope is safe

---

.github/workflows/add-platform-label.yml
.github/workflows/buildandtest.yml
.github/workflows/codeql-analysis.yml
.github/workflows/e2e.yml

Used `Get-ChildItem . -Filter *.yml | Foreach-Object { pin-github-action --allow 'actions/*,getsentry/*' $_.FullName }` and manually reverted the most disturbing formatting changes it's making (line breaks on long lines)...
There should be no need to do this again + new PRs will automatically get a failure through Danger.

ci: ping GHA to a commit hash

---

sample/metro.config.js

https://github.com/facebook/metro/tree/v0.60.0/packages/metro-config/src/defaults
In version 0.60 was introduced `exclusionList`.
Although this should have been issue earlier, it started crsahing now.
The metro bundle would not start in the sample app.

fix(sample): Metro-config renamed backlist to exclusionList

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModule.java
ios/RNSentry.m
src/js/definitions.ts
src/js/tracing/reactnativetracing.ts
src/js/wrapper.ts
test/integrations/eventorigin.test.ts
test/integrations/release.test.ts
test/tracing/nativeframes.test.ts
test/tracing/reactnativetracing.test.ts

Allows collecting app start and slow/frozen frames if Native SDK is inited manually
https://docs.sentry.io/platforms/react-native/manual-setup/native-init/
Fixes https://github.com/getsentry/sentry-react-native/issues/2367

Allows collecting app start and slow/frozen frames if Native SDK is inited manually

---

CONTRIBUTING.md

Add note about disabling fabric for users trying our sample. Without it they might struggle to switch between the archs.
__#skip-changelog__

Add note about fabric for legacy rn arch

---

CHANGELOG.md
RNSentry.podspec

This is done, because that makes it incompatible with react-native versions that hardcode a different version
Fixes #2557 
Do not hardcode RCT-Folly version
This makes it compatible with a react-native version that uses a different Folly version. See #2557 
Manually patched the file in `node_modules`

RNSentry.podspec: remove hardcoded Folly version

---

CHANGELOG.md
src/js/integrations/sdkinfo.ts
test/client.test.ts
test/integrations/sdkinfo.test.ts

I've introduced this bug in https://github.com/getsentry/sentry-react-native/pull/2492 while fixing missing SDK information in the envelope header. I didn't know that the JS SDK adds information from metadata also to the packages as RN does in SdkInfo integration, therefore this needed to be removed.
Closes: https://github.com/getsentry/sentry-react-native/issues/2531
Sample app and integrations tests

fix(envelope): Remove duplicate sdk package record from envelope

---

CHANGELOG.md
src/js/wrapper.ts

fixed `Sentry Logger [error]: Error while sending event: RangeError: Maximum call stack size exceeded` error that occurs when adding large attachments to sentry capture
fixes `Sentry Logger [error]: Error while sending event: RangeError: Maximum call stack size exceeded` error which happens when the sentry payload bytes exceeds the number of arguments the `Array.prototype.push` method can support
it is recommended to only use the spread operator for smaller arrays. So when adding a large attachment such as a json file that contains a lot of data this will result in the `maximum call stack size exceeded error` which drops the sentry capture 
> The spread syntax fails to work with larger Arrays. When testing with 100,000 elements, the spread syntax generated a RangeError with the message: …

fix: maximum call stack exceeded error

---

CHANGELOG.md

Craft added duplicate entries to our changelog.
https://github.com/getsentry/sentry-react-native/commit/9abdd867fc7663c4208bd89776b848d5d882d54a

chore(changelog): Remove autogenerated duplicate entries from 4.8.0 changelog

---

CHANGELOG.md

This isn't needed, but was the reason for the wrong publish behavior and Might be good to avoid copy pasta.
Craft will parse changelog sections by looking for content between `## <Title>` sections. This caused the last publish to create a new Fixes section because it saw "## Unreleased" -> "## Fixes" as the section
Prevent future copy pasta mistakes, otherwise this isn't really needed.
Tested running craft locally with `--dry-run`.
Merge? :P

fix(changelog): Adjust heading for 4.8.0 Fixes

---

CHANGELOG.md
src/js/sdk.tsx

This switches the functions defined in `sdk.ts` from using the `Scope` interface for typing to using the `Scope` class for typing, so that the types of `withScope` here and `withScope` from the main JS repo match.
Fixes https://github.com/getsentry/sentry-javascript/issues/6217.
I steered the OP of the above issue toward a different approach, so in the end he may avoid this problem regardless, but the error he was getting points out the mismatched types.
I have not tested it. Total mea culpa, I didn't want to go through and set up a whole RN SDK dev environment just for this tiny change, so I did it through the GH UI. I'm hoping that one of my esteemed colleagues might be willing to test it out and see if I've messed up the types anywhere else in the SDK. 🙏🏻
I'll leave this a draft for …

ref(js): Use `Scope` class rather than `Scope` type for top-level functions

---

.npmignore
CHANGELOG.md

The source file based on which native interfaces are generated is missing in the package, therefore users opting in for the new architecture would not be able to generate the native interfaces during their app build.
Failing new arch build with sentry SDK.
Using yalc store.

fix(new_arch): Add missing sources for Codegen

---

CHANGELOG.md
android/build.gradle

This reverts commit fcbe8ce98f89602d435c240eefe3ffedb6e397d3.
Going back to 6.8.0.
I've merged the new Android SDK to the main before the messages about the failing release.
Since I want to release some fixes from the main I need to revert this change.

Revert "chore(deps): update Android SDK to v6.9.0 (#2643)"

---

CHANGELOG.md
sentry.gradle
src/js/tools/collectModules.ts

fixes: https://github.com/getsentry/sentry-react-native/issues/2650
fixes: https://github.com/getsentry/sentry-react-native/issues/2642
```bash
No signature of method: java.util.ArrayList.containsKey() is applicable for argument types: (String) values: [collectModulesScript]
Possible solutions: contains(java.lang.Object), containsAll(java.util.Collection), contains(java.lang.Object), containsAll([Ljava.lang.Object;)
```
This happens when `project.ext.sentryCli` is not defined in `sample/android/app/build.gradle`.
Sample app

fix(modules): Android builds without ext config, auto create assets dir for modules

---

CHANGELOG.md
sentry.gradle

The cleanup task was missing `releaseName` and `versionCode` and was created with the same name for multiple variants.
One cleanup task is enough as there is one source map file.
fixes: https://github.com/getsentry/sentry-react-native/issues/2656

fix(modules): Modules create only one cleanup task

---

CONTRIBUTING.md

Fix the local sentry-cocoa dev guide

fix(docs): Missing SentryPrivate in the contributing guide

---

CHANGELOG.md
src/js/integrations/modulesloader.ts
src/js/wrapper.ts
test/integrations/modulesloader.test.ts

The modules loader would throw an error if the native layer was unavailable.
Also, the native event modules were overwriting the event modules.
closes: https://github.com/getsentry/sentry-react-native/issues/2718
unit tests and sentry-testkit
Ttechnically the event modules prioritization is breaking change but it never should be like that so I consider that a fix

fix(modules): Modules loaders integration handles native error and event modules are prioritised over native

---

CHANGELOG.md
sample/src/App.tsx
sample/src/screens/HomeScreen.tsx
src/js/touchevents.tsx
test/touchevents.test.tsx

This PR removes the default usage of `accessibilityLabel` for automatic touch tracking due to GDPR issues. As a replacement, the PR adds a custom `labelName` property to the `TouchEventBoundary` that can be used to set a custom property name to be used for touch tracking. 
Currently, the `sentry-react-native` uses [`accessibilityLabel` for automatic touch tracking](https://docs.sentry.io/platforms/react-native/touchevents/#tracking-specific-components). This means that if no `sentry-label` is provided it falls back to using `accessibilityLabel` as part of the uploaded breadcrumbs. However, `accessibilityLabel` often contains PII data that can help accessibility users with e.g. TalkBack or VoiceOver (this be for instance home address, phone number, social security number etc.). This means …

feat(sdk): Custom touch tracking property instead of accessibilityLabel

---

sample/metro.config.js

When a developer has multiple RN project downloaded in the test dir the file conflict with the sample build as watchFolders paths are used as sourcePaths by Metro transformers
When developing locally without this fix you need to delete the downloaded RN project in the test folder which can be quite annoying.
ci, sample app

fix(sample): Explicitly name sample source dirs to avoid conflicts 

---

sample/src/App.tsx

As logs are collected in breadcrumbs, logging the event hint with attachments causes too big an envelope size, and events are not sent, which is a terrible out-of-the-box experience.
```
01-12 10:09:37.075 18611 18713 D Sentry  : Request failed, API returned 413
01-12 10:09:37.076 18611 18713 D Sentry  : {"detail":"failed to read request body","causes":["A payload reached size limit."]}
01-12 10:09:37.076 18611 18713 D Sentry  : The transport failed to send the envelope with response code 413
01-12 10:09:37.076 18611 18713 E Sentry  : Envelope submission failed
```
sample app

chore(sample): Remove EventHint log from sample app before send

---

sample/test/e2e.test.ts

After switching to the lastest tag to fix builds the ios e2e tests are not working. 
```
2023-01-23T20:00:56.033Z WARN webdriver: Request failed with status 500 due to An unknown server-side error occurred while processing the command. Original error: 'platformVersion' must be a valid version number. 'latest' is given instead.
```
https://github.com/getsentry/sentry-react-native/actions/runs/3989908849/jobs/6842902079

fix(e2e): Remove runtime from e2e tests as it requires number 

---

.github/workflows/e2e.yml
package.json
test/e2e/tsconfig.build.json
test/perf/metrics-ios.yml
test/touchevents.test.tsx
yarn.lock

- After merging the 4.14.0 changes which included the jest testing library bump. The `jsdom` test environment is missing.
- RN Matrix E2E needed to fix iOS SDK version -> latest flag
- iOS bundles are large (60 KiB more) 
Failing tests
- https://github.com/getsentry/sentry-react-native/actions/runs/4005109915/jobs/6875065900

Fix v5 tests 

---

CHANGELOG.md
scripts/collect-modules.sh

Depending on the setup node can't be always located automatically in the XCode builds.
Therefore it's handy to support a simple way to set your own node path. As React Native scripts do. 
- https://github.com/facebook/react-native/blob/0.67-stable/scripts/node-binary.sh#L7
- https://github.com/getsentry/sentry-react-native/issues/2804
sample app

Add support for NODE_BINARY for xcode script to collect modules

---

README.md

Updating the readme for v5 release. Match the min version with `package.json`.

chore(readme): Set min RN version to 0.65 and include wizard

---

CHANGELOG.md
src/js/integrations/rewriteframes.ts
src/js/sdk.tsx
test/integrations/rewriteframes.test.ts

In JS SDK `frame.abs_path` was added and that caused the `from.abs_path` to be relative. This lead to source maps failure in the product.
related changes in JS getsentry/sentry-javascript#7167
fixes: https://github.com/getsentry/sentry-react-native/issues/2879

fix(frames): remove non absolute non url frame.abs_path coming from default stack parser

---

CHANGELOG.md
src/js/sdk.tsx
src/js/tracing/nativeframes.ts
src/js/transports/native.ts
src/js/wrapper.ts
test/sdk.test.ts

Do not ignore passed options when creating transport.
Minimalize log spam when people disable native.
I was trying out `enableNative: false` when trying options to solve this issue in Android SDK.
- https://github.com/getsentry/sentry-java/issues/2576

chore(sdk): Better DEX when native disabled

---

sample-new-architecture/ios/sampleNewArchitecture.xcodeproj/project.pbxproj
test/react-native/rn.patch.xcode.js

since sentry-cli v2
- https://github.com/getsentry/sentry-cli/pull/1172/files#diff-cb8bf951f1ff97b04c8463d418fd8439d96fcd0724b12fff24b07113e6447b7dL227

fix(xcode): Upload debug-files needs a path to read from

---

CHANGELOG.md
sample-new-architecture/src/App.tsx
src/js/options.ts
src/js/sdk.tsx
src/js/wrapper.ts
test/sdk.test.ts
test/wrapper.test.ts

In JS this feature is enabled by integration, the presence of the integration is transformed to a bool flag for the ios SDK.
- closes: https://github.com/getsentry/sentry-react-native/issues/2882

fix(ios): Disable HTTP Client Errors on all platforms by default

---

CHANGELOG.md
src/js/tracing/reactnativenavigation.ts
test/tracing/reactnativenavigation.test.ts
tsconfig.build.json

RNN instrumentation can be initialized with an option to instrument tab switches.
- closes: https://github.com/getsentry/sentry-react-native/issues/2285
- wix navigation sample https://github.com/krystofwoldrich/sentry-react-native-navigation-example
- unit tests

feat(tracing): Tabs auto instrumentation for React Native Navigation

---

CHANGELOG.md
package.json
scripts/update-javascript.sh
src/js/tracing/reactnativetracing.ts
yarn.lock

JS SDK update, for some reason the updater was failing on the `@sentry-internal/tracing` package, but that one is not necessary in 7.48.0.
https://github.com/getsentry/sentry-react-native/actions/runs/4716993448/jobs/8365203595

chore(deps): update JavaScript SDK to v7.48.0

---

CHANGELOG.md
src/js/wrapper.ts

Enforcing the native module causes an error when RN App is built with the new architecture but doesn't have the sentry native SDKs installed. 
A user might want to use sentry only in JS.
sample app, rn-tester

fix(rnna): Allow disabling native on RNNA

---

sample-new-architecture/tm/NativeSampleModule.cpp

Using string is not recommended in CPP, runtime exceptions `what` will get correctly assigned to js error message.

chore(sample): Update CPP Turbo Module crash to use runtime exception

---

.github/workflows/e2e.yml
CHANGELOG.md
ios/RNSentry.xcodeproj/project.pbxproj

Removed in https://github.com/getsentry/sentry-react-native/pull/2707/files#diff-accdc83031ad6cc664dfc3a76eba7d3f3d9c74ca4512a7c538af2b2a949c0398
RN CLI requires xcode project for autolinking 0.68 and older
https://github.com/react-native-community/cli/blob/7a10b39160d53caf43f36ae9e62d4bed942003ea/packages/platform-ios/src/config/index.ts#L41-L48
The project is just a dummy, Podfile is used.
https://github.com/getsentry/sentry-react-native/issues/2956
generated older app, ci
https://github.com/getsentry/sentry-react-native/actions/runs/4742862644/jobs/8421660685?pr=2980#step:16:16

fix(autolinking): Restore RNSentry xcode project used for autolinking in older RN versions

---

CHANGELOG.md

fix(changelog): JS SDK PRs links

---

CHANGELOG.md
ios/RNSentry.m

This typo doesn't break the build, but it cause the envelope never to be stored directly which can cause issues when taking screenshots or taking view hierarchy.
introduced in https://github.com/getsentry/sentry-react-native/pull/2463/files#diff-add4c17f9e3987271b5ca99f9a87cff1cd9adf9ffa5a599987d0ab3980990b25R293

fix(ios): Store envelopes immediately during a fatal crash

---

CHANGELOG.md
src/js/integrations/sdkinfo.ts
test/integrations/sdkinfo.test.ts

When SDK like `sentry-expo` is built on top of `sentry-react-native` it should be able to supply its own metadata,
unit tests

fix(sdk): Do not overwrite `_metadata` option by default `sdkInfo`

---

CHANGELOG.md
src/js/integrations/reactnativeinfo.ts
src/js/utils/environment.ts
src/js/utils/worldwide.ts
test/integrations/reactnativeinfo.test.ts
tsconfig.build.json
tsconfig.json
typings/react-native.d.ts

Add expo, hermes version, react_native_version to react_native_context.
This helps both us and our customers to debug issues.
sample app, expo app -> https://github.com/krystofwoldrich/sentry-expo-bare-sample-app

Add expo, hermes version, react_native_version to react_native_context

---

.github/workflows/update-deps.yml

`sentry-wizard` is a dev dependency and doesn't make sense to inform users about its' version.
users should be always using the latest version regardless of what we have as a dev dep in the repository.

chore(ci): Don't add changelog entry for sentry-wizard updates

---

CHANGELOG.md
src/js/integrations/rewriteframes.ts
test/integrations/rewriteframes.test.ts

This code was part of `sentry-expo` package by moving it into `sentry-react-native` users using this package directly will have working source maps out of the box without changing the rewriteframes integration themself. 
Technically this could be a breaking change as before we kept the hash bundle name, but since then source maps are not working it will only add more for new users and will not affect current non-expo users and expo users with their own rewriteframes.    
closes: https://github.com/getsentry/sentry-react-native/issues/3081
unit tests, expo app
https://github.com/getsentry/sentry-react-native/issues/3078#issuecomment-1554208985

feat(expo): Add support for Expo hash named bundles in RewriteFrames

---

CHANGELOG.md

Fixes PR links style, so all have "()" around the PR link.

Fix CHANGELOG.md unreleased RP links

---

.github/workflows/e2e.yml
.github/workflows/sample-application.yml
package.json
sample-new-architecture/.eslintrc.js
sample-new-architecture/__tests__/App-test.tsx
sample-new-architecture/android/app/build.gradle
sample-new-architecture/android/app/src/main/java/com/samplenewarchitecture/MainActivity.java
sample-new-architecture/android/build.gradle
sample-new-architecture/android/gradle.properties
sample-new-architecture/android/gradle/wrapper/gradle-wrapper.properties
sample-new-architecture/android/gradlew
sample-new-architecture/android/gradlew.bat
sample-new-architecture/android/settings.gradle
sample-new-architecture/ios/Podfile
sample-new-architecture/ios/sampleNewArchitecture.xcodeproj/project.pbxproj
sample-new-architecture/metro.config.js
sample-new-architecture/mocks/fileMock.js
sample-new-architecture/package.json
sample-new-architecture/yarn.lock
yarn.lock

Upgrade to the latest RN version 0.72.0
- upgrade e2e test
- upgrade sample app to the latest template
- upgrade sdk dev dep
- https://github.com/getsentry/sentry-react-native/pull/3142
sample app, ci

chore: update scripts/update-rn.sh to v0.72.0

---

CHANGELOG.md
src/js/wrapper.ts
test/wrapper.test.ts

Includes `beforeSendTransaction` to the list of filtered items from the Native SDK.
Close #3069
TODO: tests for beforeSendTransaction and also the other cases that were ignored.

Filter beforeSendTransaction from the Native SDK

---

CONTRIBUTING.md

We removed the old `sample` and `sample-new-architecture` doesn't have the `allprojects` section in `build.gradle`, so it should be added to the contribution guide.
Keeping the contributing guide up to date.
Building `sentry-java` and the sample localy.

Update `CONTRIBUTING.md` to show `allprojects` in the Android guide

---

sample-new-architecture/android/app/build.gradle

The Sentry Android Gradle Plugin auto installation can potentially break the RN SDK by installing a newer version of the Android SDK which can be potentially incompatible. RN SDK shipped with a comparable version of `sentry-android`.

chore(sample): Disable SAGP autoInstallation

---

CHANGELOG.md
src/js/integrations/reactnativeerrorhandlers.ts

We are patching the global promise which might be an unexpected side effect, but we decided to do this to ensure rejected promise tracking is working 100%. Since the `promise` package is not our dependency but `react-native` it can happen that some other package or the user installs a different version of the package. We can't fix which version will be used in our integration unless we will change from mode 100% tracking working to 100% using the `react-native` version but it might cause the tracking not to work.
Therefore I've added checks and guidance for users that run into this issue. As the solution is simply to install the exact same version as RN uses as direct dep to the app.
- fixes https://github.com/getsentry/sentry-react-native/issues/2851
- relates to one of the issues in …

fix(promise):  Warn users about multiple versions of `promise` package which can cause unexpected behaviore

---

sample-new-architecture/metro.config.js

without the additional blacklist rule, The React Native CLI always crashes/closes when running the sample on Windows with the following Error message:
```
Error: EPERM: operation not permitted, lstat 'c:\...\sentry-react-native\sample-new-architecture\android\app\build\intermediates\cxx\Debug\6h4e2b82\obj\arm64-v8a\libreact_codegen_rngesturehandler_codegen.so.tmpa7af62e'
Emitted 'error' event on NodeWatcher instance at:
at c:\...\sentry-react-native\sample-new-architecture\node_modules\metro-file-map\src\watchers\NodeWatcher.js:231:14 {
errno: -4048,
code: 'EPERM',
syscall: 'lstat',
path: 'c:\\...\\sentry-react-native\\sample-new-architecture\\android\\app\\build\\intermediates\\cxx\\Debug\\6h4e2b82\\obj\\arm64-v8a\\libreact_codegen_rngesturehandler_codegen.so.tmpa7af62e'
```
This error …

Fix windows sample build

---

scripts/version-bump.js

This fixes a small bug I've found when checking https://github.com/getsentry/sentry-react-native/pull/3156
The bump-version.js doesn't print modified files paths
```bash
Modified files: [object Object], [object Object]
```
After the cahnge:
```bash
Modified files: none
OR
Modified files: src/js/version.ts, other/js/version.ts
```

fix(ci): bump-version.js logs out modified files paths

---

sample-new-architecture/src/App.tsx

We want to receive all events from the sample for development and debugging purposes.
> Environments that contain "debug", "dev", "local", "qa", and "test" are not sampled on the server.

chore(sample): Change environment to `dev` to ensure 100% sampling

---

CHANGELOG.md
src/js/tracing/reactnativeprofiler.tsx

Switching the order causes issues with the App Start tracking. 
sample app

chore(wrap): Warn users if root component mounts before `Sentry.init`

---

CHANGELOG.md
RNSentry.podspec

Bump sentry-cocoa version to 8.10.0.
Closes #3240

chore: Bump Sentry-Cocoa version

---

CHANGELOG.md

Fixes link to release 5.9.1 in changelog note for 5.9.0

Fix changelog note for 5.9.0

---

RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentry+initNativeSdk.h
RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentry+initNativeSdk.mm
ios/RNSentry.mm

- Fixes oversight from https://github.com/getsentry/sentry-react-native/pull/3245

fix(ios): BinaryImageCache is only available from dependency container

---

CHANGELOG.md
package.json
src/js/options.ts
src/js/tracing/reactnativetracing.ts
src/js/tracing/transaction.ts
yarn.lock

- supersedes https://github.com/getsentry/sentry-react-native/pull/3247

chore: update sentry-js to 7.68.0 and fix types 

---

CHANGELOG.md
src/js/profiling/integration.ts
src/js/sdk.tsx
test/profiling/integration.test.ts

Currently start-up transactions don't have profiles attached. 
sample app, ci

fix(profiling): Create profiles for start up transactions

---

CHANGELOG.md
src/js/integrations/rewriteframes.ts
test/integrations/rewriteframes.test.ts

- fixes: https://github.com/getsentry/sentry-react-native/issues/3239
TODO: Add rewrite integration unit test

fix(hermes): Convert Hermes bytecode col pos to 1-based format

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModuleImpl.java
src/js/options.ts
src/js/sdk.tsx

This PR adds an option to disable/enable the sentry native on Android. This should help users experiencing https://issuetracker.google.com/issues/300840851 until resolved.
- https://github.com/facebook/react-native/issues/39505
- https://getsentry.atlassian.net/browse/INC-517
- https://issuetracker.google.com/issues/300840851
ci

feat(android): Add `enableNdk` to rn options

---

CHANGELOG.md
sample-new-architecture/metro.config.js
sample-new-architecture/src/App.tsx
src/js/tracing/reactnativetracing.ts
src/js/tracing/transaction.ts
test/tracing/reactnativetracing.test.ts

This PR adds a hook to auto instrumented transactions from ReactNativeTracing (navigation and ui) which cancels them when the app goes to background.
This aligns the behavior with other SDKs and fixed the issue of unexplainable long transactions due to the app in background and the js thread being paused.
https://github.com/getsentry/sentry-react-native/pull/3223
[Internal Notion Page with context and decision](https://www.notion.so/sentry/How-to-handle-Tx-when-App-is-paused-in-background-992cc95f357e4a708a7b08385a2e5800?pvs=4#c0839167d9c842a48370466377d54004)

fix(tracing): Cancel auto tx when app goes to background

---

CHANGELOG.md
src/js/tools/ModulesCollector.ts

Fixes log output which should show what paths are considered when collecting modules.
closes: https://github.com/getsentry/sentry-react-native/issues/3308

fix(modules-collector): Fix info output log to show from where modules are collected

---

test/react-native/rn.patch.app.build.gradle.js

Updates the e2e test patch file to use the node resolution to resolve the path to the react native sentry android gradle plugin.
if the e2e test works, we can make the same change in the sentry-wizard
ci
- https://github.com/getsentry/sentry-wizard/pull/352

chore(e2e): Use monorepo friendly RN SAGP path resolution

---

CHANGELOG.md
src/js/tracing/reactnativetracing.ts

The warning was showing always when `tracePropagationTargets` on the client was used.
sample app

fix(tracing): Ignore defaults when warning about duplicate definition of trace propagation targets

---

CHANGELOG.md
src/js/tracing/reactnativetracing.ts
test/tracing/reactnativetracing.test.ts

Until the next major version, where we can remove the deprecated options, there are 3 ways to set trace propagation targets. The oldest `tracingOrigins` option was not working as the default value of the newer option always overwrote it.

fix(tracing): Use deprecated tracing origins option if set

---

CHANGELOG.md
src/js/sdk.tsx
test/wrap.test.tsx

closes: https://github.com/getsentry/sentry-react-native/issues/3311
adds test to prevent this regression in the future
unit test, sample app

fix(sdk): `Sentry.wrap` doesn't enforce any keys on the wrapped component props

---

CHANGELOG.md
src/js/client.ts
src/js/integrations/screenshot.ts

This PR removes hardcoded screenshots from the RN Client and hooks into the global event processor like any other integration.
This may result in slightly delayed screenshots compared to the original method but prevents unexpected behavior due to non-standard integration behavior. 
It also deprecated `attachScreenshotToEventHint` which can be removed in the next major of the SDK.
closes: https://github.com/getsentry/sentry-react-native/pull/3328
closes: https://github.com/getsentry/sentry-react-native/issues/3317
sample app

fix(integrations): No screenshots when the SDK is disabled

---

CHANGELOG.md
sentry.gradle

Since 5.11.0 `sentry.gradle` exec a js script to check if the generated source map has debug id. This process needs to be awaited.
- fixes: https://github.com/getsentry/sentry-react-native/issues/3334
I could not reproduce the issue in CI or locally. Based on the reported error message we are accessing the exit code before the process exites.
sample app

fix(gradle): Waif for `has-sourcemap-debugid` process to exit

---

CHANGELOG.md
src/js/profiling/convertHermesProfile.ts
src/js/profiling/types.ts
src/js/profiling/utils.ts
test/profiling/convertHermesProfile.test.ts

the missing active thread id cause the Sentry backend to not calculate aggregate data, as those are calculated only for the active thread
sample app

fix(profiling): Add actual `activeThreadId` to Profiles

---

CHANGELOG.md
src/js/profiling/convertHermesProfile.ts
src/js/profiling/hermes.ts
test/profiling/convertHermesProfile.test.ts
test/profiling/hermes.test.ts

When the Hermes bundle is created without debug information the Hermes Profiles frames contain the bytecode virtual address and function offset.
sample app

fix(profiling): Parse Hermes Bytecode frames virtual address

---

CHANGELOG.md

Cancel background transaction on app in background was in 5.10.0 in the changelog but actually released in 5.11.0

Fix 5.11.0 changelog

---

CHANGELOG.md
src/js/profiling/utils.ts
src/js/sdk.tsx
src/js/utils/environment.ts
test/profiling/integration.test.ts
test/sdk.test.ts

Detection is based on the JS environment and the global `__DEV__` property user can override the value.
This change might affect users not setting the environment option at the moment. As their dev builds will now have `development` environment.
- https://github.com/getsentry/sentry-react-native/issues/2801
sample app, tests

feat(sdk): Automatically detect environment if not set by User

---

sample-new-architecture/yarn.lock

This reverts commit 12427f44d4b7746c431a369b538ec70ab2993c02.
`@babel/traverse` dependency bump breaks the sample app bundle.

Revert "build(deps): bump @babel/traverse from 7.19.3 to 7.23.2 in /sample-new-architecture (#3352)"

---

CHANGELOG.md
src/js/integrations/debugsymbolicator.ts

The hack is not necessary anymore, Sentry doesn't show symbolication errors
This PR removes the hack that was used to hide source maps symbolication errors. Sentry doesn't show the errors anymore.
Example event after this PR.
https://sentry-sdks.sentry.io/issues/4609867578/events/5c7a02ee966c4566bbb5a565124a9c58/
The platform node caused UI issues. 
https://discord.com/channels/621778831602221064/1024798907496140820/1171452965538762752
sample app

fix(debug): Remove `platform: node` from Debug Builds Events

---

sample-new-architecture/src/Screens/HomeScreen.tsx

without content type the preview button is disabled in Sentry UI
this PR only updated the sample app

fix(sample): Add contentType to attachments to enabled preview in Sentry

---

CHANGELOG.md
android/build.gradle

Bumps Android SDK to beta version that includes bump of sentry native that includes fix for the native crashesh.
ci

chore(deps): update Android SDK to v6.33.2-beta.1

---

.github/workflows/e2e.yml
CHANGELOG.md
package.json
src/js/tools/sentryMetroSerializer.ts
src/js/tools/utils.ts
yarn.lock

This PR checks if `CountingSet` exists, if not NodeJS Set is used as a fallback.
CountingSet was added in Metro 0.72.0 before NodeJS Set was used.
This PR also fixed the tests so that the parent dir node modules are not used during the build of the test Apps. As due to that the e2e tests were OK although they should not.
- fixes: https://github.com/getsentry/sentry-react-native/issues/3406
e2e tests, locally run 0.65.3 build

fix(metro): Conditionally use Set or CountingSet in Sentry Metro plugin

---

CHANGELOG.md
ios/RNSentry.h
ios/RNSentry.mm

`Sentry/SentryCurrentDateProvider.h` is missing in the `HybridPublic` in `sentry-cocoa`. This PR redeclares the interface in `RNSentry` to fix use_frameworks. builds.
- fixes https://github.com/getsentry/sentry-react-native/issues/3414
- related https://github.com/getsentry/sentry-react-native/pull/3416
sample app, ci

fix(ios): Define SentryCurrentDateProvider in RNSentry

---

samples/expo/app.json
samples/expo/package.json
samples/expo/withSampleSentry.js
samples/expo/withSampleSentry.ts
samples/expo/yarn.lock
samples/react-native/ios/.xcode.env

The Expo sample native builds didn't work due to incorrect paths.
build locally
e2e test will be added in a follow-up PR.

fix(sample): All Expo native scripts paths are relative to the repo root

---

CHANGELOG.md
src/js/tracing/reactnavigation.ts
src/js/tracing/reactnavigationv4.ts
test/tracing/reactnavigation.test.ts
test/tracing/reactnavigationv4.test.ts

We collect the RN navigation route params in the trace context:
*  `contexts.trace.data.route.params`
*  `contexts.trace.data.previousRoute.params`
But as the params may contain PII, and the data bag isn't scrubbed server side, sensitive data may leak.
This bugfix PR simply ensures `params` are not collected and an empty map is used instead.

Fix remove route params, as they may leak PII data

---

samples/react-native/src/dsn.ts
test/perf/TestAppSentry/App.js
test/react-native/rn.patch.app.js

The previous DSN was disabled due to a leaked access token.
ci/sample app

chore(internal): Use new DSN after leaked token

---

package.json
src/js/tools/sentryMetroSerializer.ts

This PR adds support to inject a debug module before serialization for Expo projects, since expo has a custom serialization process. 
In order to provide a good user experience, people can declare their `metro.config.js` like so:
``` js
// metro.config.js
const {
getSentryExpoConfig,
} = require("/Users/quin/Documents/sentry-react-native/dist/js/tools/sentryMetroSerializer");
const config = getSentryExpoConfig(__dirname);
module.exports = config;
```
- Changed all the `requires` to point to the working directories of `sentry-react-native` with this change and `@expo/metro-config` with the changes of https://github.com/expo/expo/pull/25859
- Manually changed the `@expo/metro-config` source code to dump the `js` bundle to disk
- Ran `expo export --output-dir dist --dump-sourcemap`
- Confirm …

feat(expo): Add support to inject debug module before serialization

---

scripts/expo-upload-sourcemaps.js

Give users an easy way to upload their sourcemaps and bundles to sentry when they publish an OTA update. This script does the following:
- Resolve sentry project from environment variable or the sentry plugin from expo config 
- Resolve sentry auth token from environment variable
- Amend sourcemaps to contain `debug_id` field (sentry servers expect this field)
- Upload sourcemaps and bundles with sentry-cli
```
SENTRY_AUTH_TOKEN=[super-secret] node node_modules/@sentry/react-native/scripts/expo-upload-sourcemaps.js dist
```
In test project, I generate the updates with  `eas update` then run the upload script

feat(expo): Add source maps upload script

---

.github/workflows/e2e.yml
package.json
samples/react-native/package.json
samples/react-native/yarn.lock
yarn.lock

This release fixes the iOS boost pods install issue which is crashing our iOS ci jobs.
https://github.com/facebook/react-native/releases/tag/v0.73.2
closes: https://github.com/getsentry/sentry-react-native/pull/3303
ci

chore(rn): Update repository to RN 0.73.2

---

.eslintrc.js
scripts/expo-upload-sourcemaps.js

The lint parsing was failing due to use newer ecmascript features.
I checked https://node.green/#ES2018 we can safely bump to 2018 in the scripts as the oldest node version used is 16, which is required for RN 0.65, which is the currently oldest supported version by the Sentry RN SDK.
ci

fix(expo): Fix expo upload source maps script lint

---

.npmignore
CHANGELOG.md
package.json
scripts/expo-upload-sourcemaps.js

This PR fixes the missing script file in the published package. And adds `npx` command for simple execution of the upload script.
sample app

feat(expo): Add `npx sentry-expo-upload-sourcemaps` command

---

.github/workflows/e2e.yml

E2E on RN 0.73.0,1,2 New Architecture on iOS timeout due to race condition in the RN framework.
- More details https://github.com/facebook/react-native/issues/42123#issuecomment-1881203719
This PR disables the tests.

chore(ci): Temporarily disable new arch E2E test on ios

---

CHANGELOG.md
src/js/tools/sentryMetroSerializer.ts

Options object is optional in the original Expo function.
https://github.com/expo/expo/blob/0060551c471b3c63af68cbd94db7fb3bae3e17e2/packages/%40expo/metro-config/src/ExpoMetroConfig.ts#L106

fix(expo): Make `getSentryExpoConfig` options param optional

---

.github/workflows/codegen.yml
.github/workflows/e2e.yml
.github/workflows/native-tests.yml
.github/workflows/sample-application.yml

ONLY CI CHANGES
This PR switches to `ubuntu-latest` runners everywhere possible, all Android and platform-independent jobs.
`macos-latest` runners stay only for ios jobs.
Android builds are ~3x faster from ~11 min to ~4 mins.
All android simulators are using ATD images and KVM -> native test from ~8 mins to ~2.
This PR fixes the extra E2E JSC tests on the latest RN that were enabled by mistake.
This PR removes the E2E development builds to lower the number of jobs so the CI is not blocked by the macos runners' smaller pool.
- part of https://github.com/getsentry/sentry-react-native/issues/3419

chore(ci): Use ubuntu-latest runners everywhere possible

---

.github/dependabot.yml

Configure Dependabot to:
- Only open security update PRs.
- Group dependencies where necessary to keep versions aligned and reduce Dependabot spam.

dependabot: configure to use groups for npm

---

CHANGELOG.md
scripts/expo-upload-sourcemaps.js

Although the previous option also works,
we promote in all docs and previous messages/changelogs the `/expo` export, so we should use it here too.

fix(expo): Use `@sentry/react-native/expo` as plugin name in expo upload

---

CHANGELOG.md
src/js/integrations/rewriteframes.ts
test/integrations/rewriteframes.test.ts

By default InternalBytecode is marked as inApp but in reality it's an generated file outside of the user code so it should be flagged as  false.
closes #3348
I haven't found in time an error that could be reproduced so instead, I retrieved from the internet the raw Stack Trace with users that had errors with the `InternalBytecode`, made a test with it and then I fixed the `rewriteStackFrame` in order to pass the test.

fix: errors from InternalBytecode.js are no longer marked as in_app

---

CHANGELOG.md

This PR adds crafted release notes summarising the most important Expo changes.
[Rendered changelog](https://github.com/getsentry/sentry-react-native/blob/6e306fa3bf77401b2f4e0bc3d216d03adb5246a1/CHANGELOG.md)

chore(sdk): Add Expo release summary to the changelog

---

.github/workflows/sample-application.yml

The cached `node_modules` caused the new architecture builds to fail.
This PR uses the node setup action cache instead.
ci

fix(ci): Use node action yarn cache instead of node modules

---

CHANGELOG.md
src/js/integrations/default.ts
src/js/sdk.tsx
test/profiling/integration.test.ts
test/sdk.test.ts

- introduced by https://github.com/getsentry/sentry-react-native/pull/2933
unit tests, sample app

fix(tracing): Performance Tracing should be disabled by default

---

CHANGELOG.md
RNSentry.podspec

Fixes #3547, builds were breaking due to a visionos change
#3547 
Tested against my project and my builds no longer break
- [ x I added tests to verify changes

Prevent pod install crash when visionos is not present

---

CHANGELOG.md
RNSentry.podspec
jest.config.js
package.json
samples/expo/app/(tabs)/index.tsx
samples/react-native/src/App.tsx
src/js/integrations/default.ts
src/js/integrations/index.ts
src/js/integrations/spotlight.ts
src/js/options.ts
test/integrations/spotlight.test.ts
test/mockFetch.ts
test/sdk.test.ts
yarn.lock

Attempts to match Browser Integration as close as possible
- https://github.com/getsentry/spotlight/blob/996754bc915572165cabcf66337afd74e64f7eb8/packages/overlay/src/integrations/sentry/sentry-integration.ts#L15
This PR adds Spotlight integration for React Native and Expo applications.
The integration auto-detects the dev server hostname and expects spotlight/sidecar to be available on the same hostname.
sample apps

feat(integrations): Add Spotlight integration

---

CHANGELOG.md
scripts/expo-upload-sourcemaps.js

Read from `.env` file if it exists in the user's project directory, based on https://github.com/getsentry/sentry-react-native/issues/3546#issuecomment-1911987720
Fixes https://github.com/getsentry/sentry-react-native/issues/3569
Most of the expo commands are of [this form](https://github.com/expo/expo/blob/97005b5a2528c2349e2c27d6d678f85e6f8eb754/packages/%40expo/cli/src/prebuild/prebuildAsync.ts#L65-L66): 
1. Set `NODE_ENV` to development if unset (unless if the command is `expo export`, where the metro bundler will output differently depending on NODE_ENV so we default it to production)
2. Read from `.env` file - `@expo/env` is a dependency of the `expo/cli` so we make a best effort to load it at runtime. 
test project

feat(expo): read .env file in upload script

---

CHANGELOG.md
scripts/sentry-xcode-debug-files.sh

RN script `WITH_ENVIRONMENT` calls `NODE_BINARY=$(command -v node)` which return non-zero when the command doesn't exist. We have `-e` to exit after the first error, which causes the debug symbols to stop uploading.
This PR enables `-e` after loading `WITH_ENVIRONMENT` so no errors in the env stop debug symbols upload.
- fixes https://github.com/getsentry/sentry-react-native/issues/3551
sample app

fix(xcode): Upload Debug Symbols continues when `node` not found

---

.eslintrc.js
CHANGELOG.md
package.json
src/js/client.ts
src/js/integrations/debugsymbolicator.ts
src/js/integrations/reactnativeerrorhandlers.ts
src/js/integrations/rewriteframes.ts
src/js/sdk.tsx
src/js/tools/sentryMetroSerializer.ts
src/js/tracing/addTracingExtensions.ts
src/js/tracing/nativeframes.ts
src/js/tracing/reactnativetracing.ts
test/client.test.ts
test/e2e/test/utils/fetchEvent.ts
test/integrations/rewriteframes.test.ts
test/tracing/gesturetracing.test.ts
test/tracing/reactnativenavigation.test.ts
test/tracing/reactnativetracing.test.ts
test/tracing/reactnavigation.test.ts
yarn.lock

This PR bumps JS SDK to 7.99.0 and disables lint deprecation warnings TMP.
There are over 150 deprecations in the SDK code and over 250 in the test. I will create a follow-up PR which fixes the deprecations to make it easier to review.
ci

chore(deps): update JavaScript SDK to v7.99.0

---

README.md

This PR removed the E2E tests badge, as the metric E2E tests are flaky (the red badge is not a good look.).
Since this package now supports Expo OOTB we can add Runs with Expo badge.

Update README badges, add Expo

---

.github/workflows/e2e.yml
.github/workflows/sample-application.yml
samples/react-native/Gemfile
samples/react-native/Gemfile.lock

- failing ios cocoapods caused by https://github.com/CocoaPods/CocoaPods/issues/12226#issuecomment-1930604302
- This PR forces the latest 1.15.2 cocoapods for the sample application CI and RN 0.73 e2e tests. As with previous Cocoapods versions, the Hermes pod will crash the pod install.
ci, could not reproduce locally

fix(ci): Fix iOS builds failing Hermes cocoapods

---

.github/workflows/skip-ci.yml

- follow up to https://github.com/getsentry/sentry-react-native/pull/3545
Skip CI job should check the diff only in pull requests.

fix(ci): Only check for diff in to skip ci in pull requests

---

samples/react-native/android/app/build.gradle
samples/react-native/ios/sampleNewArchitecture.xcodeproj/project.pbxproj
samples/react-native/ios/sampleNewArchitecture/Info.plist
samples/react-native/package.json
samples/react-native/src/App.tsx
samples/react-native/src/Screens/ErrorsScreen.tsx
samples/react-native/src/Screens/PerformanceScreen.tsx
samples/react-native/yarn.lock

This PR adds bottom tabs navigation to our bare react native sample application.
Note: Expo sample application already has bottom tabs navigation.
Bottom tabs are very popular in mobile applications, having sample with it makes verifying our auto instrumentation easier.
sample app

feat(sample): Add bottom tabs navigation to the RN sample app

---

CHANGELOG.md
src/js/client.ts
test/client.test.ts
test/testutils.ts

Introduced in https://github.com/getsentry/sentry-javascript/pull/9101 `client.options.enabled` check was moved from `_processEvent` to `_sendEnvelope`
- fixes https://github.com/getsentry/sentry-react-native/issues/3603
sample expo app and unit tests

fix(client): Option `enabled: false` ensures no events are sent

---

CHANGELOG.md
src/js/integrations/debugsymbolicator.ts

The Expo Dev Server without web support behaves differently from the Bare React Native Dev Server and Expo with web support. It always returns 200 HTTP status with JSON config instead of the expected 404 for non-existing endpoints.
Since we are fetching source code context we can ignore the JSON response as the code can not be JSON.
fixes: https://github.com/getsentry/sentry-react-native/issues/3602
- repro from the issue https://github.com/stichingsd-vitrion/sentry-expo-bug-reproduction

fix(symbolication): Ignore dev server JSON responses

---

CHANGELOG.md
plugin/src/utils.ts
plugin/src/withSentry.ts
plugin/src/withSentryAndroid.ts
plugin/src/withSentryIOS.ts
test/expo-plugin/modifyAppBuildGradle.test.ts
test/expo-plugin/modifyXcodeProject.test.ts

This PR reduced the warning spam when a config property is missing in Expo plugin configuration.
sample app

fix(expo): Reduce waning messages spam when a property in configuration is missing

---

CHANGELOG.md
scripts/expo-upload-sourcemaps.js

when on Windows, the execution will call "node sentry-cli..."  which will behave the same as on MacOS and Linux.
The main difference is that only calling "sentry-cli ..." on a Unix system works is due to the first line on the file telling the shell to invoke the file with the Node cli. 
It makes the script usable on Windows.
Fixes #3613
Localy on a  brand new project invoking the script the same way as users did, the below script shows sentry cli being invoked on a Windows device where previously it wouldn't execute it.
```
⬆️ Uploading dist\_expo\static\js\web\AppEntry-f904ff768b6e71e8cc866a59c8a999de1.js bundle and sourcemap...
> Found 1 file                                                             
> Found 1 file                                                             
> …
```

expo-upload-sourcemaps now works on Windows

---

CHANGELOG.md
scripts/sentry-xcode-debug-files.sh

`sentry-cocoa` symbolicates crashes/errors locally in debug builds, there is no need to upload the native debug files to Sentry.
This makes onboarding Sentry simpler, in larger projects, as devs don't have to have a Sentry token to create debug builds. And don't have to actively disable Sentry auto upload.  
The same condition as for source maps auto upload https://github.com/getsentry/sentry-cli/blob/a2a4d543f4d191db553f7b1b3385c5cd0c9cfefd/src/commands/react_native/xcode.rs#L160
sample app

fix(xcode): Upload debug files only for non-debug builds

---

.github/workflows/e2e.yml
.github/workflows/sample-application.yml
samples/react-native/android/app/build.gradle

I can't track down the cause of the uploads timing out in GitHub actions. Currently, ~80% of the uploads fail, so it's better to turn them off until we implement a mock server to test against.
It might be related to the amount of the files uploaded to the `sentry-react-native` project as these uploads run on every PR.
For the sample application builds and the perf metrics the upload can be disabled permanently as the debug files are of no use.
For the e2e tests, the missing debug files will result in non-symbolicated test errors. But since this is not checked in the tests, disabling the uploads won't be an issue.
With the disabled auto upload, we are losing the smoke test of `sentry-cli` integration with the current RN scripts. 
But since `sentry-cli` has its integration tests for the RN …

misc(ci): Disable auto debug files upload

---

.github/workflows/skip-ci.yml

This PR fixes `skip-ci` jobs which failed when only `*.md` files were changed.
`grep -v '\.md$'` returns code `1` when all lines are filtered out.

fix(ci): `diff_check` should not fail when all files are filtered

---

README.md

- related to https://github.com/getsentry/sentry-react-native/issues/3665

misc(readme): Change Expo link to Sentry docs

---

CHANGELOG.md
src/js/tracing/utils.ts

Introduced in https://github.com/getsentry/sentry-react-native/releases/tag/5.19.0 by the JS SDK update.
Caused by the integrations not calling finish() on spans.
- https://github.com/getsentry/sentry-javascript/pull/9954/files
sample app, the specific situation is hard to test in integration tests, so I have not added one, this should be tested in E2E tests

fix(performance): Missing frames measurements when active span is trimmed

---

samples/expo/app.json
samples/expo/app/_layout.tsx
samples/expo/utils/isExpoGo.ts

This PR adds Expo Router auto instrumentation to the Expo sample app.

misc(sample): Enable expo-router auto instrumentation

---

samples/expo/app/_layout.tsx
samples/expo/package.json

During Expo export, the JS code is executed, which spams the export output.
This PR adds env to the sample app to avoid this.

misc(sample): Do not execute Sentry in NodeJS during npx expo export

---

.eslintignore

Android Test App includes js in JVM test reports after the test runs locally the repository lint fails.

misc(lint): Skip Android Tester App from JS eslint

---

CHANGELOG.md
samples/expo/app/_layout.tsx
samples/expo/metro.config.js
samples/expo/package.json
samples/expo/utils/isExpoGo.ts
src/js/tools/metroconfig.ts

For special setups like our own repository, where the Sentry Metro Plugin is outside of the project structure it's needed to supply the correct (from the project node modules) default config. 
Otherwise, some features might not work, for example, hbc bundles are not emitted.

feat(expo): Add getDefaultConfig option to getSentryExpoConfig

---

CHANGELOG.md
samples/expo/app/(tabs)/index.tsx
samples/expo/app/_layout.tsx
samples/expo/metro.config.js
samples/expo/package.json
samples/expo/utils/isExpoGo.ts
src/js/tools/metroconfig.ts

Follow our docs and move `Sentry.init` to `app/_layout`
https://docs.sentry.io/platforms/react-native/manual-setup/expo/
This is important especially when the default route changes and async routes are enabled. Sentry would not load until the route would be required.

misc(expo-sample): Add expo-router auto instrumentation

---

samples/expo/yarn.lock
samples/react-native/yarn.lock
test/e2e/yarn.lock
test/perf/TestAppPlain/yarn.lock
test/perf/TestAppSentry/yarn.lock
test/typescript/ts3.8/yarn.lock
yarn.lock

Replaces:
- https://github.com/getsentry/sentry-react-native/pull/3612
- https://github.com/getsentry/sentry-react-native/pull/3619
- https://github.com/getsentry/sentry-react-native/pull/3618
- https://github.com/getsentry/sentry-react-native/pull/3617
- https://github.com/getsentry/sentry-react-native/pull/3616
- https://github.com/getsentry/sentry-react-native/pull/3697
- https://github.com/getsentry/sentry-react-native/pull/3620

chore(deps): bump ip from 1.1.* to 1.1.9

---

test/sdk.test.ts
test/sdk.withclient.test.ts

This is a preparation for v8 and it's internal changes.
This PR removes dependencies of the test on the internal JS structures.
This makes the test more future-proof and ready for JS V8.
No logic in the test changed.

test(init): Remove deps on internal JS SDK structures

---

src/js/integrations/reactnativeerrorhandlers.ts
test/integrations/reactnativeerrorhandlers.test.ts
test/mocks/client.ts

Prepares tests for JS V8 changes. This PR only includes test updates, to ensure it passes with the current implementation and the next PR will include the code changes without test changes.
- needs https://github.com/getsentry/sentry-react-native/pull/3717

test(errorhandlers): Remove dependencies on JS internal structures

---

src/js/integrations/reactnativeerrorhandlers.ts
test/integrations/reactnativeerrorhandlers.test.ts
test/mocks/client.ts

Backport changes to main
- https://github.com/getsentry/sentry-react-native/pull/3720

test(errorhandlers): Remove dependencies on JS internal structures (#3720)

---

.github/workflows/skip-ci.yml

This PR makes the `diff-check` more generic, so the check works also for PR from forks.

fix(ci): Ensure `diff-check` action works with PRs from forks

---

.github/workflows/e2e.yml
.github/workflows/sample-application.yml

The new version of `xcbeautify`, 2.x.x, is not compatible with the `macos12` runners, but the runners include an older version, 1.6.0.
- https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
- https://github.com/cpisciotta/xcbeautify/releases/tag/2.0.1
This PR adds a check to only install the tool if missing.

fix(ci): Only install `xcbeautify` if missing

---

CHANGELOG.md
src/js/sdk.tsx
src/js/tools/metroconfig.ts
src/js/utils/environment.ts
src/js/utils/worldwide.ts

Before this PR the Sentry RN SDK would be initialized during static routes generation by `expo-router`. This could cause issues as the SDK is not prepared to run on the server side. This behavior pollutes the dev server and export command logs.
Before: See the duplicate WARN labels caused by the SDK init.
sample app

fix(expo): Do not run the SDK during static routes generation

---

CHANGELOG.md
src/js/tracing/addTracingExtensions.ts
src/js/tracing/stalltracking.ts
test/mocks/client.ts
test/tracing/reactnavigation.stalltracking.test.ts
test/tracing/reactnavigation.ttid.test.tsx
test/tracing/reactnavigationutils.ts
test/tracing/stalltracking.test.ts
test/tracing/stalltrackingutils.ts

This PR is a preparation for JS V8 and its new performance spans-only API. It fixes a small bug where `.end` methods were not patched.
This PR refactors StallTracking integration tests to avoid using Transaction and internal APIs. 
This will enable us to refactor the integration in the future with confidence and minimal test changes.

fix(stalls): Missing measurements when using new .end() span API

---

CHANGELOG.md
src/js/tracing/timetodisplay.tsx

The error log will trigger a stack trace log in React which is an unwanted side-effect. The log then looks like a crash/uncaught error. Plus the stack trace is not symbolicated so it's not useful.
This PR changes the log to a warning and uses Timeout to avoid the React stack printing.
Before:
After:
sample app

fix(timetodisplay): Change TimeToDisplay unsupported message from error to warning

---

CHANGELOG.md

fix(changelog): Remove duplicate Fixes header

---

.vscode/settings.json

New versions of VSC deprecated the bool option replaced by enum, 'explicit'.

misc: Update VSC settings fixAll option changes

---

samples/react-native/metro.config.js

This PR fixes the bare RN sample multiple promise package versions. 
It overwrites the default resolve function to ensure promise from the sample node_modules is used.

fix(sample): RN Sample doesn't show multiple promise packages warning

---

CHANGELOG.md
ios/RNSentry.mm
ios/RNSentryDependencyContainer.h
ios/RNSentryDependencyContainer.m
ios/RNSentryFramesTrackerListener.h
ios/RNSentryFramesTrackerListener.m
ios/RNSentryOnDrawReporter.m
ios/RNSentryRNSScreen.h
ios/RNSentryRNSScreen.m

This PR guard iOS code which requires UIKit with `SENTRY_HAS_UIKIT` compiler directive to enable non UIKit builds, for example `react-native-macos`.
- fixes: https://github.com/getsentry/sentry-react-native/issues/3774
- build sample app with react-native-macos
- follow-up PR adding the build to CI
- https://github.com/getsentry/sentry-react-native/pull/3785

fix(ios): Fix non UIKit builds

---

CHANGELOG.md
package.json

This Pull Request removes legacy `rnpm` config. `rnpm` was depracated ~8 years ago, and currently there's no tool that read this property.
Make things simpler.

chore: remove legacy `rnpm` config

---

src/js/tracing/nativeframes.ts
test/mocks/client.ts
test/tracing/addTracingExtensions.test.ts
test/tracing/gesturetracing.test.ts
test/tracing/mockedrountinginstrumention.ts
test/tracing/nativeframes.test.ts
test/tracing/reactnativenavigation.test.ts
test/tracing/reactnativetracing.test.ts
test/tracing/reactnavigation.test.ts
test/tracing/reactnavigationutils.ts
test/tracing/stalltracking.test.ts
test/tracing/timetodisplay.test.tsx

This PR refactors the tracing/performance tests using the public APIs, which are planned to change minimally in the next major (client, startSpan, ...). 
The React Navigation V4 Instrumentation is not updated, as it will likely be removed in the next major.
This PR contains the JS Core V8 upgrade.
- https://github.com/getsentry/sentry-react-native/pull/3736

test(tracing): Update performance tests for JS Core V8 

---

CONTRIBUTING.md

Without the dependency in RNSentry the Sentry module would not be found and all Swift code would not be working in RN.
sample app

fix(CONTRIBUTION.md): Fix iOS guide, dependency on Sentry is required

---

RNSentryCocoaTester/RNSentryCocoaTester.xcodeproj/project.pbxproj
RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryBreadcrumbTests.m
ios/RNSentry.mm
ios/RNSentryBreadcrumb.h
ios/RNSentryBreadcrumb.m

SentryLevel was moved to Swift in https://github.com/getsentry/sentry-cocoa/pull/3963 and we can't use Swift code in `RNSentry.mm`, so I've moved breadcrumb conversion to pure Objective-C implementation.
The current implementation works until updating to a release which includes https://github.com/getsentry/sentry-cocoa/pull/3963 changes.
This PR makes RN implementation ready for the future release.
added unit tests, sample app

ref(ios): Move breadcrumbs conversion to pure obj-c to ensure compatibility with the swift implementation

---

CHANGELOG.md
src/js/tracing/reactnativetracing.ts

Adds warning logs when `debug: true` to places in the SDK code where it's decided that App Start span won't be added.
This will makes it easier for our customer to see why their transactions are missing app start spans as well for us when debugging the SDK.
sample app

fix(logs): Add missing App Start logs when the span is dropped

---

test/perf/metrics-ios.yml

bumps the expected size after recent sentry-cocoa update

ci(ios): allow larger app size diff (up to 1 MiB) 

---

CHANGELOG.md
src/js/tracing/timetodisplay.tsx

Having the Span IDs in the debug logs makes it possible to relate data from Sentry to the logs.

fix(ttd): Add span ids to time to display debug logs

---

CHANGELOG.md
src/js/tracing/timetodisplay.tsx
test/tracing/timetodisplay.test.tsx

This PR fixes a race condition when TTFD update would be called after TTID, but the provided timestamp was set to earlier point in time than TTID end timestamp.

fix(ttfd): Use TTID end timestamp when TTFD should be updated with an earlier timestamp

---

CHANGELOG.md

https://github.com/getsentry/sentry-react-native/pull/3854 was not in the changelog, because the change should have not affected user as it would be release before the breaking changes from `sentry-cocoa`.
But due to unfortunate order of events and not requiring pass on native builds -> https://github.com/getsentry/sentry-react-native/issues/3871
The release order was opposite. 

fix(changelog): Add entry for missing SentryLevel fix on iOS

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModuleImpl.java
ios/RNSentry.mm
src/js/NativeRNSentry.ts
src/js/tracing/reactnativetracing.ts
test/tracing/reactnativetracing.test.ts
test/tracing/reactnavigation.ttid.test.tsx

This PR adds native application start spans as children of the root app start span reported by RN today. 
- https://github.com/getsentry/sentry-cocoa/pull/4021
- https://github.com/getsentry/sentry-java/pull/3454
Doesn't close https://github.com/getsentry/sentry-react-native/issues/3445 as also RN specifics spans needs to be added. That will be separate PR.
- https://github.com/getsentry/sentry-react-native/issues/3445
- Release `sentry-cocoa` with https://github.com/getsentry/sentry-cocoa/pull/4021
- Release `sentry-android` with https://github.com/getsentry/sentry-java/pull/3454

feat(tracing): Add native application start spans

---

CHANGELOG.md
src/js/tracing/reactnativeprofiler.tsx
src/js/tracing/reactnativetracing.ts
src/js/tracing/utils.ts
src/js/utils/worldwide.ts
test/tracing/reactnativetracing.test.ts

This PR uses bundle start timestamp provided by RN, to create JS bundle execution start spans.
With `Sentry.wrap()`
Without `Sentry.wrap()`
- closes: https://github.com/getsentry/sentry-react-native/issues/2915

feat(tracing): Add JS Bundle Execution to the App Start span

---

CHANGELOG.md
src/js/tracing/nativeframes.ts
src/js/tracing/reactnativetracing.ts

This PR adds more logs to the Native Frames integration to make is easier to undestand why the SDK is not adding native frames measurements to the transaction.
sample app

fix(performance): add more debug logs to native frames integration

---

CHANGELOG.md
src/js/client.ts
test/client.test.ts

This PR fixes missing RN tracing integrations (these integrations are dummy for telemetry purposes only). They stopped beiing reported when JS core switched from `setupIntegrations` to `init`.  

fix(client): use `_setupIntegrations` to extend both `init` and public `setupIntegrations`

---

CHANGELOG.md
scripts/sentry-xcode-debug-files.sh
scripts/sentry-xcode.sh

This PR ensures sentry-cli doesn't print out `error:` into console during Xcode builds with `--allow-failure`.
The prefix `error:` triggers Xcode to mark builds as failed.
- fixes: https://github.com/getsentry/sentry-react-native/issues/3677
sample apps

fix(xcode): Xcode command line builds fail with `--allow-failure`

---

CHANGELOG.md
src/js/tracing/reactnativetracing.ts
test/tracing/reactnativetracing.test.ts

UIKit init end when the native `AppDelegate.application` method is called, this is before the JS engine starts.
This PR adds check, which only records the UIKit init start if the end was recorder after JS start. 
This logic will let manual init setups to record the UIKit init end and auto init setup to record only the start.
Before
After

fix(performance): UIKit can't end after JS execution starts

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryModuleImpl.java
ios/RNSentry.mm
src/js/tracing/nativeframes.ts
src/js/tracing/reactnativetracing.ts
test/tracing/nativeframes.test.ts

The native implementations dropped zero value measurements, which could cause app start frames not to be measured as frames on transaction start would be `null`.
This PR change native impls to return zero values and adds zero value check to processing final frames.

fix(performance): app start frames can start with zeroed values

---

samples/react-native/babel.config.js
samples/react-native/package.json
samples/react-native/src/App.tsx
samples/react-native/yarn.lock

This PR adds a simple spining animation to help Replay debugging. 
[example replay](https://sentry-sdks.sentry.io/replays/058f6870d0974d9f98150c8af468af88/?project=5428561&query=&referrer=%2Freplays%2F&statsPeriod=7d&yAxis=count%28%29)
sample app

feat(sample): add running indicator (animation overlay)

---

package.json
src/js/integrations/debugsymbolicator.ts
src/js/tools/sentryMetroSerializer.ts
src/js/tracing/reactnativetracing.ts
src/js/tracing/timetodisplay.tsx
src/js/vendor/react-native/index.ts
tsconfig.build.json
yarn.lock

This PR bumps RN SDK V6 to the latest JS V8 version.

chore(deps): Update to sentry-javascript 8.11.0

---

test/perf/metrics-ios.yml

The startup time doesn't seem to be impacted by the SDK (is that OK or do we measure it wrong?), so it may be lower then without the SDK

ci: release iOS metrics startup test restrictions

---

CHANGELOG.md
samples/expo/babel.config.js
samples/expo/package.json
samples/expo/yarn.lock
samples/react-native/babel.config.js
samples/react-native/package.json
samples/react-native/yarn.lock
src/js/touchevents.tsx
test/touchevents.test.tsx

- cleanup & fix touchevent ignore behaviour
- feat: support annotated components in touch events
- deduplicate subsequent items in the component tree/path
Example event: https://sentry-sdks.sentry.io/issues/5502756331/events/13026ba7f65a4eab8ec5dfd835c11888/

feat: touch breadcrumbs info improvements

---

CHANGELOG.md
scripts/expo-upload-sourcemaps.js

Instead of throwing an error, use `https://sentry.io/` when SENTRY_URL is not set.
Users want to not define the default url for saas ( I believe this is the same behavior as sentry cli so it is a nice pattern to follow).
Locally running `sentry-expo-upload-sourcemaps` without a defined url.
Closes: https://github.com/getsentry/sentry-react-native/issues/3792

expo: sentry-expo-upload-sourcemaps no longer requires sentry url

---

samples/expo/utils/setScopeProperties.ts
samples/react-native/src/App.tsx
samples/react-native/src/Screens/TrackerScreen.tsx
samples/react-native/src/setScopeProperties.ts
samples/react-native/src/utils.ts

Adds console.anything example for testing mobile replay.
[example link](https://sentry-sdks.sentry.io/replays/b09b1f5148ab4c5aabe94204e64d056a/?project=5428561&query=&referrer=%2Freplays%2F&statsPeriod=30d&t_main=console&yAxis=count%28%29)

misc(samples): Add console anything examples for replay testing

---

CHANGELOG.md
RNSentryAndroidTester/app/src/test/java/io/sentry/rnsentryandroidtester/RNSentryReplayBreadcrumbConverterTest.kt
RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryReplayBreadcrumbConverterTests.swift
android/src/main/java/io/sentry/react/RNSentryReplayBreadcrumbConverter.java
ios/RNSentryReplayBreadcrumbConverter.m

This PR add tests for foreground and background breadcrumbs conversion.
This PR fixes missing these breadcrumbs on iOS.
This PR does not fix missing app foreground breadcrumbs which are dropped by iOS replay segments.
unit tests, sample app

fix(replay): Add app lifecycle breadcrumbs conversion tests

---

RNSentryAndroidTester/app/src/test/java/io/sentry/rnsentryandroidtester/RNSentryReplayBreadcrumbConverterTest.kt
RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryReplayBreadcrumbConverterTests.swift
android/src/main/java/io/sentry/react/RNSentryReplayBreadcrumbConverter.java

This PR fixes missing properties on nav breadcrumbs on RN Android.
Introduced in https://github.com/getsentry/sentry-react-native/pull/3912
This PR adds test for Android and iOS to prevent this in the future.

fix(replay): Add missing properties to android nav breadcrumbs

---

CHANGELOG.md

This PR add the mobile replay public beta changelog.

misc(replay): Add Mobile Replay Public Beta changelog

---

CHANGELOG.md
src/js/client.ts
src/js/options.ts
test/client.test.ts

- This PR backports https://github.com/getsentry/sentry-react-native/pull/3635 from prepared RN SDK v6 to v5.
- As this change is technically breaking for code using `threads` I added `useThreadsForMessageStack` which enables the old behavior.
- We should release this as non breaking fix, because `threads` are breaking symbolication for `captureMessage` and we are seeing large amount of reports.
- fixes https://github.com/getsentry/sentry-react-native/issues/3963
- fixes https://github.com/getsentry/sentry-react-native/issues/3967
- fixes https://github.com/getsentry/sentry-react-native/issues/3097
- [Example event ](https://sentry-sdks.sentry.io/issues/5678391709/events/a73290cc74bb4124a0507b6bad01ce17/)

fix(client): Keep captureMessage stack trace in exception

---

samples/react-native/android/app/src/main/java/io/sentry/reactnative/sample/MainApplication.kt
samples/react-native/ios/sentryreactnativesample/AppDelegate.mm
samples/react-native/src/App.tsx

This PR adds an example of how to setup React Native SDK with manually initializing the native Android and iOS SDKs. 
sample app
[Example](https://sentry-sdks.sentry.io/issues/5105068805/events/35feb7bc06a947f38f77f85b8564c0f1/?project=5428561) JS Error from the manual init
[Example](https://sentry-sdks.sentry.io/issues/5249385673/events/3ff4c8f502ac4eb5989ce3ef9b67378d/?project=5428561) Android crash from the manual init
[Example](https://sentry-sdks.sentry.io/issues/5598917176/events/ba8c40e77e0547ad815bf03565bdef74/?project=5428561) iOS crash from the manual init
[Example](https://sentry-sdks.sentry.io/performance/trace/db583c30f23b473bb20edbb451812fe2) iOS Transaction from the manual init
[Example](https://sentry-sdks.sentry.io/performance/trace/7167096b54614c159a32a7e5ae782884) …

misc(sample): Add manual init options to the sample rn app

---

CHANGELOG.md
package.json
src/js/tools/vendor/metro/utils.ts
yarn.lock

This PR fixes `sourceMapString` is not a function error which happens due to changes in `metro@0.80.10`.
The changes https://github.com/facebook/metro/compare/v0.80.9...v0.80.10#diff-1b836d1729e527a725305eef0cec22e44605af2700fa413f4c2489ea1a03aebcL28
At `metro@0.80.9`
```
module.exports = sourceMapString;
```
At `metro@0.80.10`
```
module.exports = {
sourceMapString,
sourceMapStringNonBlocking,
};
```
This PR also adds a new error message in case the expor would change in the future.
sample app, ci

fix(metro): Fix `sourceMapString` is not a function, support `metro@0.80.10`

---

.github/workflows/native-tests.yml

This PR fixes the CI Android Native Tests failures. The AVD cache was too large and there was not enough space to runt the device. Since we are using `aosp` device optimalized for automatized test, we might drop the cache now.
The error: 
```
/usr/bin/sh -c \printf 'hw.cpu.ncore=2
' >> /home/runner/.android/avd/test.avd/config.ini
Starting emulator.
/usr/bin/sh -c \/usr/local/lib/android/sdk/emulator/emulator -avd test -no-window -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -camera-front none -timezone US/Pacific &
INFO    | Storing crashdata in: /tmp/android-runner/emu-crash-35.2.4.db, detection is enabled for process: 2631
INFO    | Android emulator version 35.2.4.0 (build_id 12141100) (CL:N/A)
INFO    | Graphics backend: gfxstream
INFO    | Found …
```

fix(tests): Android native connected tests were failing due to missing disk space

---

CHANGELOG.md
samples/expo/app/_layout.tsx
samples/react-native/src/App.tsx
src/js/integrations/default.ts
src/js/options.ts
test/sdk.test.ts

Alight witht the JS SDK which uses `spotlight: true | string`.
sample app

feat: Add `spotlight` option

---

CHANGELOG.md
android/build.gradle
package.json
samples/expo/app.json
samples/expo/app/_layout.tsx
samples/expo/package.json
samples/react-native/android/app/build.gradle
samples/react-native/ios/sentryreactnativesample/Info.plist
samples/react-native/ios/sentryreactnativesampleTests/Info.plist
samples/react-native/package.json
samples/react-native/src/App.tsx
src/js/integrations/default.ts
src/js/options.ts
src/js/version.ts
test/sdk.test.ts

This PR changes the native frames from attaching to `traceId` which can be the same for multiple spans to `spanId`. 
- This fixes potencial situations when multiple root spans share the same trace id. This is possible since JS v8, before Transaction (now Root Spans) would always have unique trace id. 
- This is needed for attaching the native frames as span level measurements. 

ref: Change native frames from `traceId` to `spanId` 

---

RNSentryAndroidTester/gradle.properties
samples/react-native/android/gradle.properties
scripts/e2e.mjs
test/perf/TestAppPlain/android/gradle.properties
test/perf/TestAppSentry/android/gradle.properties
test/react-native/rn.patch.gradle.properties.js

CI: fix OOM builds

---

CHANGELOG.md
RNSentry.podspec

Fixes https://github.com/getsentry/sentry-react-native/issues/4035
`install_modules_dependencies` helper have been [available since 0.71](https://reactnative.dev/blog/2023/01/12/version-071#new-architecture) that determines what react dependencies to add depending on new arch flags etc. This is preferred and would make sure it's forwards and backwards compatible.

Use `install_modules_dependencies` for React iOS dependencies

---

CHANGELOG.md
ios/RNSentryReplay.m

This PR adds missing RN text class to array of redacted text classes.
sample app

fix(replay): Mask RCTParagraphComponentView when maskAllText enabled

---

.gitignore

This PR adds path from the new monorepo setup to gitignore to make switching between the branches easier.
- https://github.com/getsentry/sentry-react-native/pull/4057

misc(gitignore): Add new monorepo setup gitignore paths

---

CHANGELOG.md
samples/expo/app/_layout.tsx
samples/react-native/src/App.tsx
src/js/client.ts
src/js/index.ts
src/js/integrations/default.ts
src/js/options.ts
src/js/profiling/integration.ts
src/js/tracing/index.ts
src/js/tracing/reactnativenavigation.ts
src/js/tracing/reactnativetracing.ts
src/js/tracing/reactnavigation.ts
src/js/tracing/reactnavigationv4.ts
src/js/tracing/routingInstrumentation.ts
test/client.test.ts
test/mocks/client.ts
test/profiling/integration.test.ts
test/sdk.test.ts
test/tracing/gesturetracing.test.ts
test/tracing/reactnativenavigation.test.ts
test/tracing/reactnativetracing.test.ts
test/tracing/stalltracking.test.ts

This PR add deprecations and simple replacements which will be dropped in V6.

misc(deprecations): Add Tracing deprecations and replacements

---

CHANGELOG.md
android/src/main/java/io/sentry/react/RNSentryOnDrawReporterManager.java

These log enable us to debug edge cases where TTID and TTFD is not recorded on Android. 
sample app

misc(ttd): Add Android Logger when new frame event is not emitted

---

CHANGELOG.md
packages/core/src/js/tracing/reactnativetracing.ts
packages/core/src/js/utils/environment.ts
packages/core/test/tracing/reactnativetracing.test.ts

Matches `tracePropagationTargets` with the rest of mobile SDKs and JS v8 web defaults.
We can switch to all targets on mobiles, as RN doesn't check CORS headers.
unit tests

feat: `tracePropagationTargets` to all targets on mobile and same origin on the web 

---

CHANGELOG.md
packages/core/src/js/client.ts
packages/core/test/client.test.ts
packages/core/test/trace.test.ts

Add `parentSpanIsAlwaysRootSpan` default `true` to align with JS v8 browser client.
https://github.com/getsentry/sentry-javascript/blob/d265d927ee87d5c50fdebc62da926ddea3c95912/packages/browser/src/client.ts#L57
unit tests

feat: Add `parentSpanIsAlwaysRootSpan` is `true` by default

---

CHANGELOG.md

misc: typo CHANGELOG.md

---

package.json

This changes the `run-ios` and `run-android` scripts to use sequential commands instead of `run-s`
I've run into the following error while trying to run the samples on `v6`
```
$ yarn run-ios
ERROR: Task not found: "cd", samples/react-native", yarn", react-native"
$ yarn run-android
ERROR: Task not found: "cd", samples/react-native", yarn", react-native"
```
Run the following commands from `sentry-react-native` project root:
```
yarn run-ios
yarn run-android
```

Fixes run samples scripts for iOS and Android

---

CHANGELOG.md

we need to re-release 5.33.0 as 5.33.1 (after we released 5.23.4) so that 5.33.x is latest release on npmjs.org. this PR just adds an entry for that re-release

Update CHANGELOG.md for 5.33.1

---

CONTRIBUTING.md

misc: Update CONTRIBUTING.md for the monorepo changes

---

CONTRIBUTING.md

Moves the Optional section above the macOS section for consistency in the CONTRIBUTING doc `v6`
The macOS section was merged in the middle of the `Running the sample` section (see below). This PR fixes the structure moving the optional section above.
Checked the doc

Misc: CONTRIBUTING: Moves the Optional section above the macOS section for consistency

---

CHANGELOG.md
ios/RNSentry.mm

Emits Bridge log only in debug mode
Fixes https://github.com/getsentry/sentry-react-native/issues/4053
Manual testing and CI checks

Emits Bridge log only in debug mode

---

CHANGELOG.md
src/js/tracing/timetodisplay.tsx

This prop was never used and we are not planning adding such a functionality.
Span name can be change by using methods  `startTimeToFullDisplaySpan` and `startTimeToInitialDisplaySpan`.
fixes https://github.com/getsentry/sentry-react-native/issues/4108

fix: Remove unused `spanName` from `TimeToDisplayProps`

---

.github/file-filters.yml
.github/workflows/changes-in-high-risk-code.yml

Implement a mechanism that automatically adds an "alert" comment to PRs if they include changes to files we think have higher potential to break things than others.
same as https://github.com/getsentry/sentry-java/pull/3726 and https://github.com/getsentry/sentry-dart/pull/2315
✅ by adding the file-filter.yml introduced in this PR to the list of potentially risky changes and ensuring that an alert is shown

chore: Add action to warn about potentially risky PR changes

---

samples/react-native/android/app/build.gradle
samples/react-native/package.json

This PR adds splits and flavors to the RN Android Sample with easy to run packager script to test issues like https://github.com/getsentry/sentry-react-native/pull/4125
local builds

misc: Add easy enabled splits and flavors in RN Android samples

---

test/perf/metrics-android.yml

Extends the Android metrics `diffMin` [similar to iOS](https://github.com/getsentry/sentry-react-native/blob/main/test/perf/metrics-ios.yml#L9) to increase failure tolerance. This should prevent most failures [due to negative results in the check](https://github.com/getsentry/action-app-sdk-overhead-metrics/blob/main/src/test/kotlin/StartupTimeTest.kt#L91) indicating that the app with Sentry starts faster that the app without the SDK. Note that [the root cause](https://github.com/getsentry/sentry-react-native/issues/3413#issuecomment-2399340289) of the issue is not covered by this PR.
Partially https://github.com/getsentry/sentry-react-native/issues/3413
CI

chore: Extends the Android metrics diffMin similar to iOS

---

CHANGELOG.md
src/js/integrations/nativelinkederrors.ts
test/integrations/nativelinkederrors.test.ts

Adds handling for native link errors with a string cause
Fixes https://github.com/getsentry/sentry-react-native/issues/3673
Unit test

Fix: Handles error with string cause

---

src/js/utils/sentryeventemitter.ts
src/js/utils/sentryeventemitterfallback.ts
test/utils/sentryeventemitterfallback.test.ts

Kw fallback emitter suggestion

---

CHANGELOG.md

fix: Changelog after 5.34.0 release

---

samples/react-native-macos/macos/PrivacyInfo.xcprivacy
samples/react-native-macos/macos/sentry-react-native-sample.xcodeproj/project.pbxproj

Adds macOS [PrivacyInfo](https://docs.sentry.io/platforms/react-native/data-management/apple-privacy-manifest/#create-privacy-manifest-in-xcode)
See https://github.com/getsentry/sentry-react-native/pull/3851#discussion_r1800779388
CI, Manual testing

Chore: Adds macOS privacy info

---

.github/workflows/testflight.yml

misc(ci): Remove unused testflight node_modules cache

---

package.json
packages/core/android/src/main/java/io/sentry/react/RNSentryBreadcrumb.java
packages/core/android/src/main/java/io/sentry/react/RNSentryMapConverter.java
packages/core/android/src/main/java/io/sentry/react/RNSentryModuleImpl.java
packages/core/android/src/main/java/io/sentry/react/RNSentryOnDrawReporterManager.java
packages/core/android/src/main/java/io/sentry/react/RNSentryPackage.java
packages/core/android/src/main/java/io/sentry/react/RNSentryReactFragmentLifecycleTracer.java
packages/core/android/src/main/java/io/sentry/react/RNSentryReplayBreadcrumbConverter.java
packages/core/android/src/newarch/java/io/sentry/react/RNSentryModule.java
packages/core/android/src/oldarch/java/io/sentry/react/RNSentryModule.java
samples/react-native/android/app/src/main/java/io/sentry/reactnative/sample/AssetsModule.java
samples/react-native/android/app/src/main/java/io/sentry/reactnative/sample/SamplePackage.java
samples/react-native/android/app/src/release/java/io/sentry/reactnative/sample/ReactNativeFlipper.java
scripts/google-java-format.sh
yarn.lock

As the repository includes more Java code, we should start linting it as well.
The Java code change are purely formatting.
part of https://github.com/getsentry/sentry-react-native/issues/2534
ci, locally

chore: Add java lint (google-java-format)

---

packages/core/RNSentryAndroidTester/app/src/test/java/io/sentry/react/RNSentryModuleImplTest.kt
packages/core/RNSentryAndroidTester/app/src/test/java/io/sentry/rnsentryandroidtester/RNSentryModuleImplTest.kt

During the last merge of main to v6. I forgot to move this test.
ci

fix(tests): Move fetchNativeAppStart from root to package/core

---

.github/workflows/e2e.yml

Starting in Nov 24 macos-12 will be removed.
I moved the 0.65 test only to macos-13 because RN 0.65 template is by default not compatible with building on ARM. We would have to change the E2E test to add the fix for ARM to bump to macos-14 and higher. 
https://github.com/actions/runner-images/issues/10721
ci

chore: Bump E2E RN 0.65 to macos-13

---

CHANGELOG.md

Fixes wrong import in changelog

fix(changelog): Replace `import Sentry` by `import * as Sentry`

---

.github/workflows/buildandtest.yml
.github/workflows/codegen.yml
.github/workflows/e2e.yml
.github/workflows/native-tests.yml
.github/workflows/sample-application.yml

This PR removes the cancel previous runs jobs as they are not needed when using concurrency.
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs 
every commit on main should finish all jobs
ci

chore(ci): Use concurrency instead of third party action, main runs all jobs

---

.github/workflows/buildandtest.yml
.github/workflows/codegen.yml
.github/workflows/e2e.yml
.github/workflows/native-tests.yml
.github/workflows/sample-application.yml

chore(ci): Enable CI on v5

---

samples/react-native/ios/sentryreactnativesample.xcodeproj/project.pbxproj

Our samples were using the following code
```
LOCAL_NODE_BINARY=node
```
but our SDK sets the following code on the client codebase:
```
LOCAL_NODE_BINARY=${NODE_BINARY:-node}
```
This fix makes the sample to behave like the user codebase, and also fixes issues when node isn't exposed for xCode.
Build errors on the sample locally.

Refactor: use exported Node binary on Sample

---

.github/workflows/e2e.yml

0.76 was released yesterday
https://reactnative.dev/blog/2024/10/23/the-new-architecture-is-here
ci

chore(test): Bump RN E2E tests to 0.76.0

---

samples/react-native/package.json
samples/react-native/src/App.tsx
samples/react-native/src/Screens/PlaygroundScreen.tsx
samples/react-native/src/Screens/WebviewScreen.tsx
yarn.lock

This PR adds react native webview to our RN Sample to help with Session Replay development.
[Replay Example with Webview](https://sentry-sdks.sentry.io/replays/c14c95772a5b4a53a6c49dc2e7b38566)
Webview is correctly redacted.
- https://github.com/getsentry/sentry/issues/74441
locally

feat(sample): Add react-native-webview

---

README.md

For reference see https://github.com/getsentry/sentry-cocoa/pull/4236

misc(readme): Update from logo to header banner

---

samples/react-native/package.json
yarn.lock

Bumps react-native-screens from 3.34.0 to 3.35.0 in the sample app
Changelog: https://github.com/software-mansion/react-native-screens/releases/tag/3.35.0
The new release fixes a JNI crash when the Android app is obfuscated https://github.com/software-mansion/react-native-screens/pull/2290 encountered while debugging https://github.com/getsentry/sentry-react-native/pull/4232
Manual testing, CI

chore(deps): Sample App: Bumps react-native-screens from 3.34.0 to 3.35.0

---

dev-packages/type-check/ts3.8-test/index.ts
dev-packages/type-check/ts3.8-test/package.json
dev-packages/type-check/ts3.8-test/tsconfig.build.json

This PR changes the type check test project to only include the es2015/es6 types excluding dom, which would cause duplicate declarations when the project would import React or React Native.
- This is needed for https://github.com/getsentry/sentry-react-native/pull/4224
- Where we want to export React Native HostComponent Type

test(ts3.8): fix ts3.8 type check test to not include dom types

---

CHANGELOG.md
packages/core/RNSentryCocoaTester/RNSentryCocoaTester.xcodeproj/project.pbxproj
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryCocoaTesterTests-Bridging-Header.h
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryReplayOptionsTests.swift
packages/core/ios/RNSentryReplay.m

This PR fixes bug introduced during upgrade of cocoa https://github.com/getsentry/sentry-react-native/pull/4156
Bug released in https://github.com/getsentry/sentry-react-native/releases/tag/5.34.0 and https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0
locally running sample app, added tests

fix(replay): RN Classes to redact were not used by cocoa

---

.github/workflows/e2e.yml

The tests were disabled due to a bug in RN new arch, which caused the tests to fail is CI.
Since then the bug was fixed so we can reenabled the tests.
- https://github.com/getsentry/sentry-react-native/pull/3513

test(e2e): Return new architecture

---

samples/react-native/src/App.tsx

This is a temporary fix to unblock the SDK development using the sample app.
Based on our E2E tests which use minimal RN application this is specific to our sample app setup.
We have not seen any reports of this from our users, but it's possible that application using similar setup might experience the same issue.

fix(sample): Disable global promise patch

---

CHANGELOG.md
packages/core/src/js/index.ts

This PR adds the missing export SeverityLevel from @sentry/types.

fix(core): Export missing SeverityLevel from types

---

packages/core/sentry.gradle

The new disable native upload flag was not released yet.
This fixes case when the native upload is disabled but still JS source maps should be uploaded.

fix(gradle): DISABLE_NATIVE_UPLOAD should not affect JS source maps upload

---

packages/core/sentry.gradle

Aligns Android `SENTRY_DISABLE_NATIVE_DEBUG_UPLOAD` logic [with the `SENTRY_DISABLE_XCODE_DEBUG_UPLOAD` on iOS](https://github.com/getsentry/sentry-react-native/blob/7bc4d758f2bdfa0bbb51d2a9119418c0f500e893/packages/core/scripts/sentry-xcode-debug-files.sh#L38), so that the upload is performed only when both the new flag is `false` and the `SENTRY_DISABLE_AUTO_UPLOAD` is `false`
| SENTRY_DISABLE_ AUTO_UPLOAD | SENTRY_DISABLE_ NATIVE_DEBUG_UPLOAD XCODE_DEBUG_UPLOAD |Upload iOS |Upload Android (before)| Upload Android (after)
|---|---|---|---|---|
| true | true | false | false	| false |
| true | false | false | true	| false |
| false | true | false | true	| false |
| false | false | true | true	| true |
https://github.com/getsentry/sentry-react-native/pull/4263 fixes case when the native …

Fix: Aligns Android autoupload logic with iOS

---

.github/workflows/e2e.yml

The E2E Test of RN 0.65 was failing on iPhone 14 simulator lookup.
Corepack is not available in macos-15 at the moment.
- https://github.com/actions/runner-images/issues/10905
This PR doesn't fix the sample app provisioning profile issues not the native tests fail.

fix(e2e): Bump tests to iOS 18.1  and macos-15

---

.github/workflows/native-tests.yml

fix(ci): Bump native tests to iPhone 16 and macos-15

---

.github/workflows/sample-application.yml
samples/react-native/ios/sentryreactnativesample.xcodeproj/project.pbxproj

Fix failing sample ios build due to missing iPhone 14 simulator.
The build now uses generic iOS sim target. This should be more resilient for the future.

fix(ci): update sample app build target to generic ios simulator

---

.github/workflows/e2e.yml
dev-packages/e2e-tests/package.json
yarn.lock

Fixes p-retry version to `6.2.0` since [the latest release](https://github.com/sindresorhus/p-retry/releases) including https://github.com/sindresorhus/p-retry/pull/82 triggered the issue.
```
error node_modules/p-retry/index.js: Unexpected token: operator (?) in file node_modules/p-retry/index.js at 51:37.
Error: Unexpected token: operator (?) in file node_modules/p-retry/index.js at 51:37
at minifyCode (/home/runner/work/sentry-react-native/sentry-react-native/dev-packages/e2e-tests/react-native-versions/0.65.3/RnDiffApp/node_modules/metro-transform-worker/src/index.js:99:13)
at transformJS (/home/runner/work/sentry-react-native/sentry-react-native/dev-packages/e2e-tests/react-native-versions/0.65.3/RnDiffApp/node_modules/metro-transform-worker/src/index.js:317:28)
at …
```

fix(ci): Fixes p-retry version to 6.2.0

---

dev-packages/e2e-tests/cli.mjs

Skip maestro if SENTRY_AUTH_TOKEN is unavailable
See https://github.com/getsentry/sentry-react-native/pull/4268#issuecomment-2473342812
CI

fix(ci): Skip maestro test if SENTRY_AUTH_TOKEN is unavailable

---

samples/expo/app/(tabs)/index.tsx
samples/react-native-macos/src/Screens/ErrorsScreen.tsx
samples/react-native-macos/src/Screens/TrackerScreen.tsx
samples/react-native/src/Screens/ErrorsScreen.tsx
samples/react-native/src/Screens/TrackerScreen.tsx

- [Removes metric from the RN app](https://github.com/getsentry/sentry-react-native/commit/e60030005981557b907dbbabc13218a173223342)
- [Removes metric from the MacOS app](https://github.com/getsentry/sentry-react-native/commit/e21831ec59167e4e6bcc2cf902dffbeea73605d1)
- [Removes metric from the Expo app](https://github.com/getsentry/sentry-react-native/commit/616db8cc82ed105e65e5d0bd0d96412dd8415db3)
Fixes https://github.com/getsentry/sentry-react-native/issues/4242
Manual testing

misc: Removes deprecated Sentry.metrics API

---

dev-packages/e2e-tests/cli.mjs

Skip maestro test if SENTRY_AUTH_TOKEN is unavailable or empty
This is an additional fix after https://github.com/getsentry/sentry-react-native/pull/4269 since the CI issue was not solved https://github.com/getsentry/sentry-react-native/pull/4284#issuecomment-2483181486
CI

fix(ci): Skip maestro test if SENTRY_AUTH_TOKEN is unavailable or empty

---

dev-packages/e2e-tests/maestro/crash.yml
dev-packages/e2e-tests/maestro/utils/assertTestReady.yml
dev-packages/e2e-tests/maestro/utils/launchTestAppClear.yml

This PR adds longer timeout for test ready text to appear. 
Especially RN 0.65 on iOS frequently timesout on the current 2 mins timeout.

fix(e2e): Add longer timeout for test app start

---

CHANGELOG.md
packages/core/src/js/tools/metroconfig.ts
packages/core/src/js/tools/sentryBabelTransformerUtils.ts
packages/core/test/tools/metroconfig.test.ts
packages/core/test/tools/sentryBabelTransformer.test.ts

This PR remove use of tmp `.sentry` dir. And adds dedicated Sentry default Babel transformer env instead.
The use of ENV ensures that multiple concurent builds are not sharing the same resource (the tmp dir). The env is by default scoped to the current process and its children.
- Fixes: https://github.com/getsentry/sentry-react-native/issues/4121
sample app, updated unit tests

fix(metro): Use env for default Babel transformer path

---

samples/expo/app/(tabs)/index.tsx

This PR adds Reload JS Bundle button to the Expo sample app.
This helps with debugging issues related with bundle reload and session replay.
https://github.com/getsentry/sentry-react-native/issues/4234

internal(samples): Add reload JS bundle for Expo sample

---

packages/core/test/tracing/integrations/appStart.test.ts

[Mocks `Date.now()` call so that no delay is introduced](https://github.com/getsentry/sentry-react-native/blob/7fd512afedf0e54a9572c2c31545ca61e5a59aed/packages/core/src/js/tracing/utils.ts#L108) during testing.
Fixes https://github.com/getsentry/sentry-react-native/issues/4197
Checking ten different runs that resulted in failure, the cause was the timestamp comparison tolerance. By default the test requires [2 decimal digits precision (`Math.abs(expected - received) < 0.005`)](https://github.com/jestjs/jest/blob/main/docs/ExpectAPI.md#expectclosetonumber-numdigits) but that fails frequently on CI on the following tests:
* Standalone App Start › adds ui kit init start mark as a child of the main app start span
* Standalone App Start › adds bundle execution before react root via private …

test: Fix flaky App Start Tests

---

CHANGELOG.md

Update CHANGELOG.md with 6.3.0-beta.x

---

.github/workflows/e2e.yml

This PR adds a skip for `Metrics` perf jobs on release branches, these jobs are flaky (negative app start diff) and thus can block releases for "no reason". 
[Example of tests run with test condition](https://github.com/getsentry/sentry-react-native/actions/runs/12028115666/job/33530586109?pr=4312)

ci: Skip metrics on release branches

---

CHANGELOG.md
packages/core/RNSentry.podspec

This PR fixes failing builds on iOS new architecture on RN version 0.70 and older.
Before RN 0.71, there was no helper to setup the cocoapods dependencies (no install_modules_dependencies).
And so libraries needed to specifi the list of deps manually.
RNSentry was missing `React-RCTFabric` as no Fabric components were used in the SDK.
This changed in https://github.com/getsentry/sentry-react-native/pull/4224 and was not released.

fix(cocoapods): Add missing `React-RCTFabric` dependency

---

CHANGELOG.md
packages/core/RNSentry.podspec
packages/core/src/js/index.ts

Same as JS https://github.com/getsentry/sentry-javascript/issues/11951#issuecomment-2499563835
Fixes https://github.com/getsentry/sentry-react-native/issues/4311

fix(exports): Return `lastEventId`

---

CHANGELOG.md
packages/core/RNSentry.podspec
packages/core/src/js/tracing/span.ts
packages/core/test/tracing/idleNavigationSpan.test.ts

This PR fixes a bug introduced in RN SDK V6. Where unfinished navigations spans are set as parents of newly created navigations spans.
This is unexpected as navigations span should be a active root span (aka transaction in the SDK V5).
This issue was reported by the sales team working with clients trying out the new SDK V6.
added unit test for the behaviour, tests failed before the fix.
Also tested this with the Sentry RN Demo App.

fix(span): Navigation Span should have no parent by default

---

.github/workflows/e2e.yml
.github/workflows/native-tests.yml
.github/workflows/sample-application.yml
scripts/e2e.mjs
src/js/client.ts

This PR backports CI fixes done in past week on the main branch back to v5, so we are able to release patches of v5 with confidence and passing tests. :)

ci: Update v5 CI

---

samples/expo/app/_layout.tsx
samples/expo/package.json

This PR adds `export:web` as to deplay it's common to only export web without the mobile js bundles.
This PR also removes the `EXPO_SKIP_DURING_EXPORT` since since 5.21.0 release (https://github.com/getsentry/sentry-react-native/pull/3730) `___SENTRY_METRO_DEV_SERVER___` is used internally to disable Sentry during the static paths render.

chore(samples): Update Expo Sample export scripts

---

CHANGELOG.md
android/build.gradle

Bump android to 7.18.1 to include the latest SR fixes in v5.
There were no changes in RN SDK specific to android so this PR is purely dep bump.

chore: update scripts/update-android.sh to 7.18.1

---

CHANGELOG.md
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryTests.mm
packages/core/ios/RNSentry.mm

- fixes https://github.com/getsentry/sentry-react-native/issues/4343
native tests, sample app

fix(ios): Disable HTTP Client errors in sentry-cocoa to avoid duplicates

---

performance-tests/TestAppPlain/package.json
performance-tests/TestAppSentry/package.json
performance-tests/metrics-ios.yml
yarn.lock

- Bumps TestAppPlain/TestAppSentry performance test apps from RN `0.70.6` to [`0.70.15`](https://github.com/facebook/react-native/releases/tag/v0.70.15) that includes the [Boost fix](https://github.com/facebook/react-native/commit/e8e059a977ef2feec1b4b9dfd2866daede2b8ff8).
- Also [increases iOS binary size diff by 100KB](https://github.com/getsentry/sentry-react-native/pull/4414/commits/68f0bcf4ba2c246d9b23658b6c5594d0f4e8e2a8) since the tests were consistently failing after the RN version bump.
Fixes https://github.com/getsentry/sentry-react-native/issues/4413
CI
- This PR aims to tackle the CI failure with the minimum possible changes. As a next step we should consider upgrading
our performance test apps (TestAppPlain/TestAppSentry) on the latest RN version.
- ⚠️ The binary size bump …

chore(ci): Fixes performance tests failure due to Boost dependency URL unavailability

---

.github/workflows/e2e.yml

Pins the CI Environment to Ubuntu 22.04 for metrics Android to avoid the CI failure as described in https://github.com/getsentry/sentry-react-native/issues/4418#issuecomment-2577512319
Fix https://github.com/getsentry/sentry-react-native/issues/4418
CI
- [Upgrade the performance test apps](https://github.com/getsentry/sentry-react-native/issues/4426) (TestAppPlain/TestAppSentry) on the latest RN version so that they run with latest Ubuntu.

chore(ci): Pin the CI Environment to Ubuntu 22.04 for metrics android

---

CHANGELOG.md
packages/core/android/src/main/java/io/sentry/react/RNSentryModuleImpl.java
packages/core/android/src/main/java/io/sentry/react/RNSentryVersion.java

Use proper name for the RN SDK in replay tags

Fix sdk name for replay tags

---

packages/core/ios/RNSentryVersion.m

The baked in value is automatically updated during version release, but when adding this feature this value was set incorrectly to 6.4.0 instead of 6.5.0.
- Update script: https://github.com/getsentry/sentry-react-native/blob/main/scripts/version-bump.js#L10

fix(cocoa): Update the RN SDK version to current 6.5.0

---

CHANGELOG.md
packages/core/ios/RNSentry.mm

Part of https://github.com/getsentry/sentry-react-native/issues/3608
This PR moved the `RNSentryTimeToDisplay` init to the module init, so the time to display functionality is not dependent on the auto init from JS.

chore: Initialize `RNSentryTimeToDisplay` during native module `init` on iOS

---

CHANGELOG.md

Fixes wrong change-log link
A wrongly formatted changelog link was entered with https://github.com/getsentry/sentry-react-native/pull/4395/commits/32943e9c7800e04effaad22da2bbbea70c395c43
Manual

chore: Fixes wrong change-log link

---

CHANGELOG.md
packages/core/src/js/integrations/reactnativeerrorhandlers.ts
packages/core/test/integrations/reactnativeerrorhandlers.test.ts

Unhandled rejection were lacking the Mechanism field, so I added it.
https://github.com/getsentry/sentry-react-native/issues/4093
Unit test and https://sentry-sdks.sentry.io/issues/6018946733/events/91e85dfdbd5340c487e7d279378441d4/?project=5428561

Fix: Add unhandled rejection mechanism

---

CHANGELOG.md
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryReplayOptionsTests.swift
packages/core/ios/RNSentryReplay.mm
packages/core/ios/RNSentryVersion.h
packages/core/ios/RNSentryVersion.m

Sending the version and sdk name in the session replay event to show up at Tags tab.

feat: Send Sentry react-native SDK version in the session replay event

---

LICENSE.md

While updating the date ranges for multiple PRs, Michi pointed out that we don't need date ranges for our licenses. I'm sorry about the fuzz.
In our internal [Open Source Legal Policy](https://www.notion.so/sentry/Open-Source-Legal-Policy-ac4885d265cb4d7898a01c060b061e42), we decided that licenses don't require a data range. This also has the advantage of not updating the date range yearly.
cc @gavin-zee

Remove date range for LICENSE

---

packages/core/RNSentryAndroidTester/app/src/androidTest/java/io/sentry/react/RNSentryJsonConverterTest.kt
packages/core/RNSentryAndroidTester/app/src/androidTest/java/io/sentry/rnsentryandroidtester/RNSentryJsonConverterTest.kt
packages/core/android/src/main/java/io/sentry/react/RNSentryJsonConverter.java

Implements a utility class `RNSentryJsonConverter` converting a `JsonObject` to a `WritableMap`
Part of https://github.com/getsentry/sentry-react-native/issues/3608
Unit tests

Adds utility class for converting `JsonObject` to `WritableMap`

---

samples/expo/app/_layout.tsx
samples/expo/utils/isWeb.ts

Small fix as browser replay causes a crash due to https://github.com/getsentry/sentry-javascript/blob/de2c1ad309b850c1254c69890c96e869e297fa4c/packages/replay-internal/src/replay.ts#L764

fix(samples): Only load browser replay when Expo sample is running on web

---

CHANGELOG.md
packages/core/package.json
samples/expo/package.json
samples/react-native/package.json
yarn.lock

Bump to the latest version.
There were no breaking changes in the v3 related to the annotations. The v3 was released due to other changes in the monorepo where the annotation plugin is placed.

chore(deps): Bump @sentry/babel-plugin-component-annotate to v3.1.2

---

scripts/update-javascript.sh

Removes the package sentry/utils from the update list.
Sentry JavaScript will not update this package on V9 since it was merged on sentry/core https://github.com/getsentry/sentry-javascript/blob/develop/CHANGELOG.md#deprecations-4
Without this change, the action for updating the Sentry SDKs will fail.
CI error:
https://github.com/getsentry/sentry-react-native/actions/runs/13259874007/job/37030814458
CI
#skip-changelog.

Ref: Remove sentry/utils from update list

---

.github/workflows/sample-application.yml
samples/react-native/.detoxrc.js
samples/react-native/android/app/build.gradle
samples/react-native/android/app/proguard-rules.pro
samples/react-native/android/app/src/androidTest/java/io/sentry/reactnative/sample/DetoxTest.java
samples/react-native/android/app/src/main/AndroidManifest.xml
samples/react-native/android/app/src/main/res/xml/network_security_config.xml
samples/react-native/android/build.gradle
samples/react-native/e2e/jest.config.js
samples/react-native/e2e/starter.test.ts
samples/react-native/jest.config.js
samples/react-native/package.json
samples/react-native/src/App.tsx
yarn.lock

:loudspeaker: Type of change
This PR adds Detox tests to `samples/react-native`. 
We need Detox due to limited assertions on JS objects in Maestro and the inability to run the Mocked relay as part of the tests.
The actual tests are part of the following PR https://github.com/getsentry/sentry-react-native/pull/4536
```bash
detox build --configuration ios.sim.release
detox test --configuration ios.sim.release
detox build --configuration android.emu.release
detox test --configuration android.emu.release
```
Other configurations are described in `.detoxrc.js`.
run tests locally and set up new job in CI to run the tests

internal(sample-rn): Add Detox for integration/e2e tests of the rn sample

---

CHANGELOG.md
packages/core/src/js/feedback/FeedbackWidget.styles.ts
packages/core/src/js/feedback/FeedbackWidget.tsx
packages/core/src/js/feedback/FeedbackWidget.types.ts
packages/core/src/js/feedback/FeedbackWidgetManager.tsx
packages/core/src/js/feedback/defaults.ts
packages/core/src/js/feedback/integration.ts
packages/core/src/js/index.ts
packages/core/src/js/sdk.tsx
packages/core/test/feedback/FeedbackWidget.test.tsx
packages/core/test/feedback/FeedbackWidgetManager.test.tsx
packages/core/test/feedback/__snapshots__/FeedbackWidget.test.tsx.snap
samples/expo/app/(tabs)/index.tsx
samples/react-native/src/App.tsx
samples/react-native/src/Screens/ErrorsScreen.tsx

Tiny change, many lines, 
when I was looking at the docs, we refer to the feedback component as a feedback widget at most places.

chore(feedback): Use Widget instead of Form

---

packages/core/src/js/feedback/FeedbackWidget.tsx
packages/core/src/js/feedback/FeedbackWidgetManager.tsx

This PR removes duplicate animations of the feedback widget. 
Because modal slide and animated slide, the modal would flash in an upper position when sliding out, see the video below.
https://github.com/user-attachments/assets/074a62ca-3c85-484c-865a-f5740f54a29d
After the changes, the widget plays only one slide animation and slides once. Als,o the background opacity, animates now on close. Before was canceled by unmounting the widget.
if onClose or onSucess callbacks are supplied the widget doesn't unmount users get to decide what to do with the widget. This allows us in case of the auto-injection keep the form on the modal which is sliding out instead of sliding out a blank modal.
https://github.com/user-attachments/assets/eee1aa64-8f7a-4e9a-b7f1-7754800a3f22

chore(feedback): Improve widget animations

---

samples/react-native/Gemfile.lock

Not sure why, but I keep seeing this Gemfile change after `bundle install`

misc(samples): Update Gemfile missing x86 ffi

---

samples/react-native/e2e/captureMessage.test.android.ts
samples/react-native/e2e/captureMessage.test.ios.ts
samples/react-native/e2e/envelopeHeader.test.android.ts
samples/react-native/e2e/envelopeHeader.test.ios.ts
samples/react-native/package.json
yarn.lock

Fixes type errors after merge in main to capture-app-start-errors.
https://github.com/getsentry/sentry-react-native/actions/runs/13392121407/job/37404373063?pr=4472

fix(sample-e2e): Fix type errors missing sentry/core and afterAll

---

packages/core/src/js/feedback/FeedbackWidget.styles.ts
packages/core/test/feedback/__snapshots__/FeedbackWidget.test.tsx.snap

Aligns secondary buttons with the web design
|Web|
|---|
|![web](https://github.com/user-attachments/assets/b3b01764-9ae9-4915-b0ab-27448364419c)|
|iOS|Android|
|---|---|
|![after](https://github.com/user-attachments/assets/842ca17c-823e-4cf3-875f-a9b15472bca7)|![Screenshot_1740043881](https://github.com/user-attachments/assets/7f800e6f-f9d0-4159-8f0b-9f45aeb563ac)|
Part of https://github.com/getsentry/sentry-react-native/issues/4302
Manual

feat(feedback): Align secondary buttons with the web

---

CHANGELOG.md
packages/core/tsconfig.build.json
packages/core/tsconfig.build.tools.json

- fixes: https://github.com/getsentry/sentry-react-native/issues/4562
The Sentry RN Package doesn't depend on `tslib` so it should not import it in its dist files. 
The only file where `tslib` was imported was `metroconfig.js`.
`tslib` was removed in Sentry JS already in v7 -> https://github.com/getsentry/sentry-javascript/pull/9299
checked that tslib is not part of the output in dist.

fix(metro): Avoid importing tslib in Sentry Metro Plugin

---

samples/expo/app.json

The trailing command breaks SDK release because react-native-version doesn't support https://json-5.com/json-vs-json5 (includes trailing commas and comments), but Expo tooling does.

fix(expo-sample): Remove trailing comma from `app.json`

---

packages/core/src/js/feedback/FeedbackWidgetManager.tsx
packages/core/test/feedback/FeedbackWidgetManager.test.tsx

Skip the changelog because the feedback widget has not been released yet.
This PR adds a warning for users who try to open the feedback widget without using `Sentry.wrap`.

feat(feedback): Add warning when auto injected widget can't be shown

---

packages/core/src/js/feedback/FeedbackWidget.tsx
packages/core/src/js/feedback/FeedbackWidgetManager.tsx
packages/core/src/js/feedback/integration.ts
packages/core/src/js/feedback/lazy.ts
packages/core/test/feedback/FeedbackWidget.test.tsx
packages/core/test/feedback/FeedbackWidgetManager.test.tsx

This PR ensures we can track the feedback usage.
If widget only is used `MobileFeedback` integration is added.
If auto inject show is called `AutoInjectMobileFeedback` dummy integration is added.
This PR also removed the static options of the feedback integration, so users have to correctly register the integration and so we can track it.

feat(feedback): Add integrations to client to allow for usage tracking

---

CHANGELOG.md
packages/core/src/js/tracing/integrations/appStart.ts
packages/core/src/js/tracing/reactnativetracing.ts
packages/core/src/js/tracing/span.ts
packages/core/test/tracing/integrations/appStart.test.ts
packages/core/test/tracing/reactnativenavigation.test.ts
packages/core/test/tracing/reactnavigation.test.ts
packages/core/test/tracing/reactnavigation.ttid.test.tsx

Adds span thread info. This would be:
- `name: main` for UI threads
- `name: javascript` for JS threads
Ref: https://reactnative.dev/architecture/threading-model
https://github.com/getsentry/sentry-react-native/issues/4461
Manual, CI

feat: Adds span thread info

---

.github/workflows/testflight.yml

Fixes
ITMS-90725: SDK version issue - This app was built with the iOS 17.4 SDK. Starting April 24, 2025, all iOS and iPadOS apps must be built with the iOS 18 SDK or later, included in Xcode 16 or later, in order to be uploaded to App Store Connect or submitted for distribution.

ci(testflight): Upgrade to macos-15 and Xcode 16.2

---

CHANGELOG.md
packages/core/android/build.gradle

Depends on https://github.com/getsentry/sentry-react-native/pull/4490
Bumps Android SDK 8.2.0 -> 8.3.0
https://github.com/getsentry/sentry-java/releases/tag/8.3.0
Manual, CI

chore(deps): Bump Android SDK to v8.3.0

---

CHANGELOG.md
packages/core/src/js/tracing/integrations/appStart.ts
packages/core/test/profiling/integration.test.ts
packages/core/test/tracing/integrations/appStart.test.ts
packages/core/test/tracing/reactnavigation.ttid.test.tsx

Fixes the app start being attached to the first started not first processed transaction.
The first started transaction doesn't have to end first.
- fixes https://github.com/getsentry/sentry-react-native/issues/4512
unit tests + e2e test coming in follow up PR

fix(appStart): Attach App Start spans to the first created not the first processed root span

---

.github/workflows/e2e.yml

Ensures that the clean app e2e tests run with exact xcode versions.
Old RN with Xcode 14.2
Latest RN with Xcode 16.2
- verifies https://github.com/getsentry/sentry-react-native/issues/4622

ci(e2e): Use exact Xcode version (16.2) for e2e tests

---

CHANGELOG.md
packages/core/src/js/tracing/integrations/appStart.ts
packages/core/test/tracing/integrations/appStart.test.ts
packages/core/test/tracing/reactnavigation.ttid.test.tsx

It's a description, no logic should rely on it, but turned out some does. I open this PR on v7 branch since logic depends on it, I consider this a breaking change.
This PR aligns the naming to match the native SDKs.
https://github.com/getsentry/sentry-cocoa/blob/5c3fa88fefada71a9fd8c567cffd03f875dd94c7/Sources/Sentry/SentryBuildAppStartSpans.m#L40-L51
https://github.com/getsentry/sentry-java/blob/main/sentry-android-core/src/main/java/io/sentry/android/core/ActivityLifecycleIntegration.java#L767-L773
ci

Change `Cold/Warm App Start` span description to `Cold/Warm Start`

---

CHANGELOG.md
packages/core/android/build.gradle

Updates the Android SDK dependency to the latest patch version, which includes potential bug fixes and improvements for measuring cold and warm starts.

chore(android): Bump Sentry Android SDK to v7.22.1

---

samples/react-native/package.json
samples/react-native/src/App.tsx
samples/react-native/src/Screens/PerformanceScreen.tsx
samples/react-native/src/Screens/SpaceflightNewsScreen.tsx
samples/react-native/src/components/ArticleCard.tsx
samples/react-native/src/types/api.ts
yarn.lock

- Introduced a new screen for displaying spaceflight news articles using the Spaceflight News API.
- Integrated `@shopify/flash-list` for efficient rendering of articles.
- Added `ArticleCard` component for individual article display.
- Included navigation to the new screen from the Performance screen.
- Updated dependencies in package.json for `@shopify/flash-list` and `axios`.
- This will help us test and debug TTID/TTFD and Flash List related issues...
running the sample app

feat(samples): Add Spaceflight News screen with article fetching

---

CHANGELOG.md
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryReplayOptionsTests.swift
packages/core/ios/RNSentryReplay.mm
packages/core/src/js/replay/mobilereplay.ts
samples/react-native/src/App.tsx

Depends on https://github.com/getsentry/sentry-cocoa/pull/4988
Adds `enableExperimentalViewRenderer` and `enableFastViewRendering` mobile replay options from sentry-cocoa
Fixes https://github.com/getsentry/sentry-react-native/issues/4658
Sample App, CI

feat(replay): iOS: Adds `enableExperimentalViewRenderer` and `enableFastViewRendering` 

---

CHANGELOG.md
packages/core/src/js/tracing/reactnavigation.ts
packages/core/test/tracing/reactnavigation.ttid.test.tsx
samples/react-native/src/App.tsx

- Introduced `enableTimeToInitialDisplayForPreloadedRoutes` option to the React Navigation integration.
- Updated logic to measure Time to Initial Display for routes that have already been seen.
- Added tests to verify functionality for preloaded routes in the tracing module.
Depending on an application, this can improve the number of transactions with TTID measurements. 
Originally we excluded already seen routes with the idea that the seen route is already loaded.
But routes that have been seen, can on the next visit refresh their context and this PR enables users to measure the time this next visit takes to load.
integration test, manually in sample app

feat(ttid): Add support for measuring Time to Initial Display for already seen routes

---

CHANGELOG.md
packages/core/src/js/tracing/reactnavigation.ts
packages/core/src/js/tracing/timetodisplay.tsx
packages/core/test/tracing/reactnavigation.ttid.test.tsx
samples/react-native/src/App.tsx

This PR fixes an issue where the TTFD would be reported before the automatic TTID is finished. This can happen during navigation animation, as the automatic TTID waits for the navigation animation to finish, but TTFD is reported when data are available and rendered.           
The expected behavior is that TTFD reported before TTID will be adjusted to the TTID end.
sample app and added integration test

fix(ttd): Equalize TTID and TTFD duration when TTFD manual API is called and resolved before auto TTID

---

CHANGELOG.md
packages/core/src/js/integrations/appRegistry.ts
packages/core/src/js/utils/rnlibraries.ts
packages/core/test/integrations/appRegistry.test.ts

The appRegistry was not yet released.
The integration should handle web env gracefully.
sample expo app

fix(appRegistry): Handles missing global object and web environment

---

.github/workflows/e2e.yml

Skips the `react-native-build` CI job when the `auth_token_check` fails [similar to the metrics check](https://github.com/getsentry/sentry-react-native/blob/623b5b8599adf2f64a075a56dffa6f5e3c1ee8be/.github/workflows/e2e.yml#L31).
Failed `dependabot` PRs due to missing `SENTRY_AUTH_TOKEN` causing `sentry reported an error: Invalid token header. No credentials provided. (http status: 401)`:
- [bump Github/codeql-action from 3.28.12 to 3.28.13](https://github.com/getsentry/sentry-react-native/pull/4709)
- [bump reactivecircus/android-emulator-runner from 2.33.0 to 2.34.0](https://github.com/getsentry/sentry-react-native/pull/4710)
- [bump actions/create-github-app-token from 1.11.7 to 1.12.0](https://github.com/getsentry/sentry-react-native/pull/4711)
- [bump axios from 1.6.3 to …

chore(ci): Skip build when auth token is not available

---

samples/expo/app.json

This is not related to the Sentry RN SDK, it happens in app without Sentry as well.
Disabling the feature fixes https://github.com/expo/expo/issues/35224

fix(sample): Disable asyncRoutes for iOS in Expo configuration

---

CHANGELOG.md
packages/core/src/js/profiling/integration.ts
packages/core/src/js/profiling/nativeTypes.ts
packages/core/test/profiling/fixtures.ts
packages/core/test/profiling/integration.test.ts

The `debug_images` was typed incorrectly. This native field is optional.
Reading property of the undefined value caused a crash.
fixes: https://github.com/getsentry/sentry-react-native/issues/4733
unit tests

fix(profiling): Prevent crash on iOS when debug images are missing on profiling end

---

CHANGELOG.md
packages/core/src/js/tracing/integrations/appStart.ts
packages/core/test/tracing/integrations/appStart.test.ts

The app start age check, compared seconds (transaction start) with milliseconds (app start).
The test were passing because the test app start was also too long, so it was rejected by the next check in order.
unit tests

fix(app-start): Use ms to calculate app start age threshold

---

packages/core/tsconfig.build.json
packages/core/tsconfig.build.tools.json
packages/core/tsconfig.json

This flag is not necessary, we are not importing non existing default anywhere in the SDK code.

Kw-remove-sythetic-default-imports

---

packages/core/src/js/feedback/FeedbackWidget.tsx
packages/core/src/js/feedback/FeedbackWidget.types.ts
packages/core/src/js/feedback/ScreenshotButton.tsx
packages/core/src/js/feedback/defaults.ts
packages/core/test/feedback/ScreenshotButton.test.tsx

Based on https://github.com/getsentry/sentry-react-native/pull/4726
Shows an error message when screenshot capture fails
See https://github.com/getsentry/sentry-react-native/pull/4714#discussion_r2042087380
Manual with [screenshotError.patch](https://github.com/user-attachments/files/19777145/screenshotError.patch), CI

feat(feedback): Screenshot button error flow

---

CHANGELOG.md
packages/core/src/js/integrations/exports.ts
samples/react-native/src/App.tsx

Export `extraErrorDataIntegration` from '@sentry/react';
Fixes https://github.com/getsentry/sentry-react-native/issues/4758
CI, Manual

Export extraErrorDataIntegration

---

CHANGELOG.md
packages/core/src/js/tools/metroconfig.ts
packages/core/test/tools/metroconfig.test.ts

`@sentry/replay` was replaced by `@sentry-internal/replay` in version 8 of the JS core.
To avoid this in the future we should introduce more strict bundle size checks.

fix(metro): Remove sentry-internal/replay package on demand

---

CHANGELOG.md
packages/core/src/js/integrations/expocontext.ts
packages/core/test/integrations/expocontext.test.ts

In https://github.com/getsentry/relay/pull/4690 we decided to use generic context name, which can be used by other SDKs.
- https://github.com/getsentry/sentry-react-native/pull/4767
- https://github.com/getsentry/relay/pull/4690
- https://github.com/getsentry/sentry/pull/90148
- https://github.com/getsentry/sentry/pull/90162
- https://github.com/getsentry/sentry/pull/90475

fix(expo-context): Rename expo_updates to ota_updates

---

CHANGELOG.md
packages/core/RNSentryAndroidTester/app/src/test/java/io/sentry/react/utils/RNSentryActivityUtilsTest.kt
packages/core/android/src/main/java/io/sentry/react/RNSentryOnDrawReporterManager.java
packages/core/android/src/main/java/io/sentry/react/utils/RNSentryActivityUtils.java

This PR requires https://github.com/getsentry/sentry-java/pull/4337 to be back ported to `sentry-java@v7`.
This PR adds a fallback to the Sentry Global Activity holder in case the react native context is missing current activity.
unit tests

chore(ttd): Fallback to activity holder if react context activity is not available

---

CHANGELOG.md
packages/core/RNSentryAndroidTester/app/src/test/java/io/sentry/react/RNSentryModuleInitWithApplicationTest.kt
packages/core/RNSentryAndroidTester/app/src/test/java/io/sentry/react/Utils.kt
packages/core/android/src/main/java/io/sentry/react/RNSentryModuleImpl.java

This PR passes `applicationContext` to the `sentry-android` initialization function.
This PR is need for improving the current activity tracking from https://github.com/getsentry/sentry-java/pull/4337.
Passing applicationContext will cause the `CurrentActivityIntegration` to be added, which ensures that if activity changes, the global holder hast the correct reference.

fix(android): Init with ApplicationContext if available

---

CHANGELOG.md
packages/core/scripts/sentry-xcode-debug-files.sh

Once again improve monorepo experience.
Fixes: https://github.com/getsentry/sentry-react-native/issues/4790

feat(xcode): Support  `REACT_NATIVE_PATH` env variable in debug files upload scripts

---

.github/workflows/sample-application.yml
samples/react-native/e2e/captureErrorsScreenTransaction.test.ts
samples/react-native/e2e/captureSpaceflightNewsScreenTransaction.test.ts
samples/react-native/e2e/utils/mockedSentryServer.ts

This PR should improve stability of the Maestro React Native Sample E2E tests stability.
This test often fails on the macos runners, likely due to them being slower than the ubuntu counterparts.
Current iOS failure rate [is 40%](https://sentry.sentry.io/explore/discover/homepage/?dataset=transactions&field=title&field=workflow&field=failure_rate%28%29&field=failure_count%28%29&field=count%28%29&name=All%20Events&project=5899451&query=branch%3Amain%20repo%3Agetsentry%2Fsentry-react-native&queryDataset=transaction-like&sort=-workflow&statsPeriod=30d&yAxis=count%28%29)
Android only 3%.
With the updated name we can track the rate after this change.
ci runs

test(maestro-sample): Await the mocked relay start before starting the test

---

CHANGELOG.md
packages/core/src/js/feedback/FeedbackWidgetManager.tsx
packages/core/src/js/feedback/utils.ts
packages/core/test/feedback/FeedbackWidgetManager.test.tsx

Disable native driver for `backgroundColor` animation
[The 'backgroundColor' is not supported by native animations](https://github.com/facebook/react-native/issues/14178) and [causing a crash in older RN versions](https://github.com/getsentry/sentry-react-native/pull/4604#discussion_r2068706742).
<details><summary>Android crash logs</summary>
<p>
```
Error: Style property 'backgroundColor' is not supported by native animated module
This error is located at:
in c
in f
in RCTView
in Unknown
in __Sentry.TouchEventBoundary
in Unknown
in RCTView
in Unknown
in RCTView
in Unknown
in u
Error: Style property 'backgroundColor' is not supported by native animated module
This error is located at:
in c
in f
in RCTView
in Unknown
in __Sentry.TouchEventBoundary
in Unknown
in RCTView
in Unknown
in …
```

fix(feedback): Disable native driver for backgroundColor animation

---

CHANGELOG.md
packages/core/src/js/utils/rnlibraries.ts

This PR fixes change in export of RN Devlibs. The functions are now exported as default.
Changed in https://github.com/facebook/react-native/commit/e5818d92a867dbfa5f60d176b847b1f2131cb6da
Fixes: https://github.com/getsentry/sentry-react-native/issues/4798
Without the change the local symbolication doesn't work, the app doesn't crash, warning about missing functions is logged out.
sample expo app
Related PR upgrade to SDK 53: (link tba)

fix(debug-symbolicator): Use new default exports of RN 0.79

---

CHANGELOG.md
packages/core/src/js/client.ts
packages/core/src/js/integrations/expocontext.ts
packages/core/test/clientAfterInit.test.ts
packages/core/test/integrations/expocontext.test.ts
packages/core/test/mocks/client.ts

This native context would be lost as it was set before the SDK initializes.

fix(expo-context): Expo Updates context is passed to native after init

---

performance-tests/metrics-ios.yml

Increase iOS binary size diff by 100KB (to 1300 KB) to avoid failing binary size checks.
I've noticed that `metrics (new, ios)` check has [started to fail](https://github.com/getsentry/sentry-react-native/actions/runs/14878421060/job/41783636800) consistently on`main` after [bumping the iOS SDK](https://github.com/getsentry/sentry-react-native/pull/4807).
```
BinarySizeTest > app size() FAILED
java.lang.AssertionError: 1229276 should be < 1228800
at BinarySizeTest.app size(BinarySizeTest.kt:37)
```
Notes:
- [The 100kb bump (to 1300kb)](https://github.com/getsentry/sentry-react-native/pull/4784) was already needed on [the Feedback Widget feature branch](https://github.com/getsentry/sentry-react-native/pull/4726).
- We [last pumped the diff by 100kb in …

chore(ci): Fixes iOS binary size diff failure

---

CHANGELOG.md
packages/core/src/js/tracing/reactnativetracing.ts
packages/core/test/tracing/timetodisplay.test.tsx
samples/react-native/e2e/captureSpaceflightNewsScreenTransaction.test.ts
samples/react-native/package.json
samples/react-native/src/App.tsx
samples/react-native/src/Screens/SpaceflightNewsScreen.tsx
yarn.lock

RN Fetch is a polyfill using XHR under the hood. Having both Fetch and XHR tracing enables causes duplicate spans.
Open: Ideally we trace the outer most call, in this case `fetch`, but that's much complex fix.
Example before:
After:
sample app, e2e tests

fix(tracing): Avoid duplicate network requests (fetch, xhr) by default

---

samples/expo/app/(tabs)/index.tsx
samples/expo/package.json
yarn.lock

The Dev Client makes it easier to test different EAS Updates as it allows developers to loging to their EAS Account and pick an update in the Dev Menu.
https://docs.expo.dev/versions/latest/sdk/dev-client/

chore(expo-sample): Add Expo Dev Client

---

CHANGELOG.md

Merge both fixes into a single session.

(V7/Changelog) merge duplicated fixes changelog

---

CHANGELOG.md
packages/core/src/js/wrapper.ts
packages/core/test/wrapper.test.ts

CrashedLastRun had a typo so it was always returning null, this PR fixes this issue.
typeof Promise<boolean> is object so it never gets valid, but if you await you get the value (boolean) or undefined, matching the original result.
Fixes https://github.com/getsentry/sentry-react-native/issues/4630

Fix crashed last run not returning a value

---

samples/expo/app.json
samples/expo/package.json

Adds a simple script for quick access to configuring EAS Update.

chore(samples):  Add eas-update-configure script

---

CHANGELOG.md
packages/core/src/js/integrations/reactnativeerrorhandlers.ts
packages/core/src/js/utils/worldwide.ts
packages/core/test/integrations/reactnativeerrorhandlers.test.ts

- Uses Hermes's native tracker when available
- Leverages Sentry Browser SDK for React Native Web
- Falls back to existing implementation for JSC
Fixes https://github.com/getsentry/sentry-react-native/issues/3957
CI, Manual ([mobile](https://sentry-sdks.sentry.io/issues/6018946733/events/latest/?project=5428561&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=latest-event&stream_index=0), [web](https://sentry-sdks.sentry.io/issues/6604676621/events/latest/?project=5428561&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=latest-event&stream_index=0))

fix(promise): Use engine-specific promise rejection tracking

---

CHANGELOG.md
packages/core/android/build.gradle

Bumps scripts/update-android.sh from 8.11.1 to 8.12.0.
- Add new User Feedback API ([#4286](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4286))
- We now introduced Sentry.captureFeedback, which supersedes Sentry.captureUserFeedback
- Add Sentry Log Feature ([#4372](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4372))
- The feature is disabled by default and needs to be enabled by:
- `options.getLogs().setEnabled(true)` in `Sentry.init` / `SentryAndroid.init`
- `<meta-data android:name="io.sentry.logs.enabled" android:value="true" />` in `AndroidManifest.xml`
- `logs.enabled=true` in `sentry.properties`
- `sentry.logs.enabled=true` in `application.properties`
- `sentry.logs.enabled: true` in `application.yml`
- Logs can be captured using …

 chore(deps-v7): update Android SDK to v8.12.0 

---

CHANGELOG.md
packages/core/RNSentry.podspec
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryReplayOptionsTests.swift

chore(deps-v7): update Cocoa SDK to v8.51.1

---

CHANGELOG.md
packages/core/src/js/transports/encodePolyfill.ts
packages/core/src/js/utils/carrier.ts
packages/core/src/js/utils/worldwide.ts
packages/core/test/transports/encodePolyfill.test.ts

This PR uses global TextEncode when available. This change mainly improves performance of the envelope encoding before passing the envelope to the native layers. 
Since https://github.com/facebook/hermes/commit/8fb0496d426a8e50d00385148d5fb498a6daa312 Hermes for RN 0.74 includes native implementation of TextEncoder which is more performant than the JS polyfill we use at the moment.
sample apps, unit tests

chore(encoding): Use global TextEncode when available

---

CHANGELOG.md
packages/core/src/js/integrations/breadcrumbs.ts
packages/core/src/js/integrations/exports.ts
packages/core/test/integrations/breadcrumbs.test.ts

This PR fixes `window.addEventListerner` is not a function error, which was logged out on the v7 branch during the `breadcrumbsIntegration` setup.
The error was caused by the history handler which was recently refactored in the browser SDK.
This PR adds a wrapper around the browser integration changing the defaults if the SDK runs on RN and on Web.
sample apps, unit tests

feat(breadcrumbs): Add environment aware defaults for RN/Expo/Web

---

CHANGELOG.md
packages/core/android/build.gradle

- Send UI Profiling app start chunk when it finishes ([#4423](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4423))
- Republish Javadoc [#4457](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4457)
- Finalize `OkHttpEvent` even if no active span in `SentryOkHttpInterceptor` [#4469](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4469)
- Session Replay: Do not capture current replay for cached events from the past ([#4474](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4474))
- Session Replay: Correctly capture Dialogs and non full-sized windows ([#4354](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4354))
- Session Replay: Fix inconsistent `segment_id` …

chore(deps): v7: update Android SDK to v8.13.3

---

CHANGELOG.md
packages/core/android/build.gradle

- Fix Session Replay masking for newer versions of Jetpack Compose (1.8+) ([#4485](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4485))
- Add New User Feedback Widget ([#4450](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4450))
- This widget is a custom button that can be used to show the user feedback form
- Add New User Feedback form ([#4384](https://github-redirect.dependabot.com/getsentry/sentry-java/pull/4384))
- We now introduce SentryUserFeedbackDialog, which extends AlertDialog, inheriting the show() and cancel() methods, among others.
To use it, just instantiate it and call show() on the instance (Sentry must be previously initialized).
For customization options, please check the [User Feedback …

chore(deps): v7: update Android SDK to v8.14.0

---

samples/react-native/src/App.tsx

Disable fast view rendering (`enableFastViewRendering`) in the sample app since it does not work correctly on iOS making testing difficult
| [enableFastViewRendering: true](https://sentry-sdks.sentry.io/explore/replays/591fdd8a4bed4771b6d1127253892521/?project=5428561&query=&referrer=%2Fexplore%2Freplays%2F&statsPeriod=1h&yAxis=count%28%29) | [enableFastViewRendering: false](https://sentry-sdks.sentry.io/explore/replays/cf8b87d7ee00489ba3ee97995c731b86/?project=5428561&query=&referrer=%2Fexplore%2Freplays%2F&statsPeriod=1h&yAxis=count%28%29) |
|---|---|
|<img width="266" alt="Screenshot 2025-06-18 at 3 44 51 PM" src="https://github.com/user-attachments/assets/674c53ea-5c1e-4527-ab58-ef3e429b36fc" />|<img width="261" alt="Screenshot 2025-06-18 at 3 45 01 PM" …

chore(sample): Disable fast view rendering in the sample app

---

.github/workflows/skip-ci.yml

Fixes variable interpolation in skip-ci workflow
See https://linear.app/getsentry/issue/MOBILE-1001, https://linear.app/getsentry/issue/MOBILE-1002, https://linear.app/getsentry/issue/MOBILE-1003
CI

fix(ci): Fix variable interpolation in skip-ci workflow

---

packages/core/RNSentryAndroidTester/app/src/test/java/io/sentry/react/replay/RNSentryReplayMaskManagerTest.kt
packages/core/RNSentryAndroidTester/app/src/test/java/io/sentry/react/replay/RNSentryReplayUnmaskManagerTest.kt

Adds unit tests for SR mask/unmask managers
This is a follow up to https://github.com/getsentry/sentry-react-native/pull/4957 adding minimal unit tests covering the cases were the error appeared
CI
Add UI tests for masking

test: Adds unit tests for SR mask/unmask managers

---

.github/workflows/e2e-v2.yml

Bumps E2E tests to the latest RN version to verify compatibility
https://github.com/getsentry/sentry-react-native/pull/3567
CI

chore(e2e): Bump E2E tests to RN 0.80.1

---

.github/workflows/update-deps.yml
packages/core/plugin/src/withSentryAndroidGradlePlugin.ts
packages/core/test/expo-plugin/withSentryAndroidGradlePlugin.test.ts
scripts/update-sentry-android-gradle-plugin.sh

Adds Sentry Android Gradle Plugin update script in the workflow
Noticed [an outdated version hardcoded](https://github.com/getsentry/sentry-react-native/blob/d18ddb18691fd5593a768f4edf8cc7e923d5e536/packages/core/plugin/src/withSentryAndroidGradlePlugin.ts#L32) as I was investigating another issue
- [Temporarily added the PR branch in the updater](https://github.com/getsentry/sentry-react-native/pull/4970/commits/990a349568522326ab7e04e0b41d0cc7b01262a0)
- [CI Run](https://github.com/getsentry/sentry-react-native/actions/runs/16071147298/job/45355884354?pr=4970)
- [PR Opened](https://github.com/getsentry/sentry-react-native/pull/4971)

chore(ci): Add Sentry Android Gradle Plugin update script in the workflow

---

CHANGELOG.md
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryTests.mm
packages/core/ios/RNSentry.mm
packages/core/ios/RNSentryExperimentalOptions.h
packages/core/ios/RNSentryExperimentalOptions.m
packages/core/src/js/options.ts
samples/react-native/src/App.tsx

Add experimental flag `enableUnhandledCPPExceptionsV2` on iOS that provides a more reliable way to report unhandled C++ exceptions in iOS.
Fixes https://github.com/getsentry/sentry-react-native/issues/4966
Manual, CI

feat: Add experimental flag `enableUnhandledCPPExceptionsV2` on iOS

---

CHANGELOG.md
packages/core/src/js/index.ts
samples/react-native/src/App.tsx

Expose `featureFlagsIntegration` and `FeatureFlagsIntegration` type
JS Docs: https://docs.sentry.io/platforms/javascript/configuration/integrations/featureflags/
Fixes https://github.com/getsentry/sentry-react-native/issues/4983
Manual with the sample app ([example event](https://sentry-sdks.sentry.io/issues/5005275690/events/latest/?project=5428561&query=is%3Aunresolved&referrer=latest-event&stream_index=0))

feat(feature-flags): v7: Expose featureFlagsIntegration

---

samples/expo/app/_layout.tsx
samples/react-native-macos/src/App.tsx
samples/react-native/src/App.tsx

Removes `enableTracing` from sample apps since this has been removed
This option has been removed in https://github.com/getsentry/sentry-react-native/releases/tag/7.0.0-beta.1
Manual, CI
#skip-changelog since this has been communicated in https://github.com/getsentry/sentry-react-native/blob/v7/CHANGELOG.md#700-beta1

fix(samples): v7: Remove `enableTracing` from sample apps

---

CHANGELOG.md
packages/core/src/js/tracing/span.ts
packages/core/test/tracing/idleNavigationSpan.test.ts
packages/core/test/tracing/integrations/userInteraction.test.ts

Skip idle span creation when app is in background.
This is a follow up to https://github.com/getsentry/sentry-react-native/pull/3307
Client reports of transactions starting in the background resulting in (a small number of) unexplainable long transactions skewing the app statistics.
Manual, CI tests

fix(span): Skip idle span creation when app is in background

---

CHANGELOG.md
packages/core/src/js/index.ts

Export `addIntegration` from core
Note: [the docs](https://docs.sentry.io/platforms/react-native/integrations/plugin/#adding-an-integration) already mention this since version 6 that included the JS bump
Fixes https://github.com/getsentry/sentry-react-native/issues/5017
Manual with the sample app

fix(core): Export addIntegration from core

---

samples/react-native/e2e/jest.config.ios.js

Increases iOS E2E test timeout to tackle `Test ios production REV2` test flakiness 🤞 
`Test ios production REV2` seems to still be flaky and fail most of the time.
CI by re-running the multiple times (5/6 runs succeeded)
|[Test ios production REV2](https://github.com/getsentry/sentry-react-native/actions/runs/16513520521/job/46705465851?pr=5016#logs)|[Test ios production REV2](https://github.com/getsentry/sentry-react-native/actions/runs/16515668705?pr=5016) (after branch update)|
|---|---|
|<img width="380" height="266" alt="Screenshot 2025-07-25 at 9 43 43 AM" src="https://github.com/user-attachments/assets/98aa2b03-d1ce-4edd-b623-46d75326f31b" />|<img width="363" height="298" alt="Screenshot 2025-07-25 at 11 24 14 AM" src="https://github.com/user-attachments/assets/0c110330-f25b-4f59-92 …

test(e2e): Increase iOS E2E test timeout

---

CHANGELOG.md

This PR updates the changelog with the hotfix for iOS on version 6.18.1

Update CHANGELOG with 6.18.1 release

---

.github/workflows/e2e-v2.yml

Bumps E2E tests to the latest RN version to verify compatibility
https://github.com/getsentry/sentry-react-native/pull/3567
CI

chore(e2e): Bump E2E tests to RN 0.80.2

---

CONTRIBUTING.md

This is a nice to have contributing update, from time to time I have to set up the token so it's a nice to-do before trying the sample apps for the first time since this will fail the builds if not set.

Add sentry cli token mention to contributing docs.

---

CHANGELOG.md
packages/core/android/build.gradle

- Add a `isEnableSystemEventBreadcrumbsExtras` option to disable reporting system events extras for breadcrumbs ([#4625](https://github.com/getsentry/sentry-java/pull/4625))
- Session Replay: Use main thread looper to schedule replay capture ([#4542](https://github.com/getsentry/sentry-java/pull/4542))
- Use single `LifecycleObserver` and multi-cast it to the integrations interested in lifecycle states ([#4567](https://github.com/getsentry/sentry-java/pull/4567))
- Add `sentry.origin` attribute to logs ([#4618](https://github.com/getsentry/sentry-java/pull/4618))
- This helps identify which integration captured a log event
- Prewarm `SentryExecutorService` for better performance at runtime ([#4606](https://github.com/getsentry/sentry-java/pull/4606))
- Cache network capabilities and …

chore(deps): v7: update Android SDK to v8.19.0

---

CHANGELOG.md
packages/core/src/js/utils/environment.ts
packages/core/src/js/utils/worldwide.ts

During an investigation of our support of the new architecture I accidentally found that the way we detect turbo modules is outdated since `__turboModuleProxy` was removed from React Native in bridgeless mode. 
Here is where I found that: https://github.com/facebook/react-native/pull/48362
Here is more information about bridgeless mode in React Native: https://github.com/reactwg/react-native-new-architecture/discussions/154
And, finally, here is how React Native itself detects if Turbo Modules are available: https://github.com/facebook/react-native/blob/641a79dc5137b69a3c0813413b9fb82d0b9df783/packages/react-native/src/private/featureflags/ReactNativeFeatureFlagsBase.js#L110
Basically this change implements the same mechanism for detecting Turbo Modules that's already used in React Native …

fix(newArch): fixes how the availability of Turbo Modules is being detected

---

.github/workflows/e2e-v2.yml
.github/workflows/sample-application-expo.yml
.github/workflows/sample-application.yml

Temporarily downgrades the affected iOS runners to `macos-14` to handle the environment change linked below. The tooling (xcode 16.2) remained the same and there should be no effect in the validity of the CI checks/tests.
An issue was opened to revisit this: https://github.com/getsentry/sentry-react-native/issues/5082
Other solutions considered:
- Updating the projects to later iOS versions: this is not simple in all cases. E.g the [RnDiffApp is specific to the RN version](https://github.com/getsentry/sentry-react-native/blob/e2fa43d707d0eb4267bdac55de308874a6fb139e/.github/workflows/e2e-v2.yml#L270) and probably needs to be patched after download to achieve the desired.
- Installing the missing platforms with [tools like xcodes](https://github.com/XcodesOrg/xcodes?tab=readme-ov-file#insta …

chore(ci): Handle GH runner image deprecations

---

.github/workflows/e2e-v2.yml

Bumps E2E tests to the latest RN version to verify compatibility
https://github.com/facebook/react-native/releases/tag/v0.81.0
CI

chore(e2e): Bump E2E tests to RN 0.81.0

---

CHANGELOG.md
packages/core/src/js/tracing/timetodisplay.tsx
packages/core/test/tracing/timetodisplay.test.tsx

Partially fixes https://github.com/getsentry/sentry-react-native/issues/4705
1) Even though in the docs we clearly state that TTID/TTFD is not supported, apparently it works if you disable all the checks in the SDK. I suspect it works since this PR got merged: https://github.com/getsentry/sentry-react-native/pull/4669
2) However, it is NOT packed as a Turbo Module which means all the standard disadvantages like extra overhead and higher latency due to serialization/deserialization and native modules being loaded into memory during app startup.
The solution for now is the following: we can now remove the checks in the SDK and basically make it work with the new architecture. However, we will need to implement TTID/TTFD as turbo modules to make it more efficient: …

fix(tracing): Time To Initial Display / Time To Full Display: remove warning that it's unsupported

---

packages/core/plugin/src/withSentryAndroid.ts
packages/core/plugin/src/withSentryAndroidGradlePlugin.ts
packages/core/test/expo-plugin/withSentryAndroidGradlePlugin.test.ts

- Added correct types for `packages/core/plugin/src/withSentryAndroidGradlePlugin.ts`
- Adjusted function argument names to make clear distinction and not overlap
Fixes https://github.com/getsentry/sentry-react-native/issues/5097
```
npm run lint:lerna
npm run test
```
And a manual change test on my project to verify it's actually the only reason.
This probably misses the same `expect.toEqual` assertions for other branches, but overall is guaranteed by the type safety itself.

fix(core/plugin): Ensure android plugin type safety

---

CHANGELOG.md

Adding a changelog for the PR https://github.com/getsentry/sentry-react-native/pull/5098
#skip-changelog.

Fix: changelog for external contributor

---

CHANGELOG.md

Fixes changelog and adds [sendDefaultPii message](https://github.com/getsentry/sentry-javascript/pull/17364)
Changelog inconsistency
Manual

chore(changelog): v7: Update 7.0.0-rc.2 changelog

---

CHANGELOG.md

Changelogs were a bit off for version 7. Some fields got lost when bumping packages on main and then syncing into V7. This PR aims to sync the missing/incorrect updates for each V7 Release.
Items without a `from X to Y` were replaced by `to Y` only since the versions matches the latest release of V6, they were left as a reference since people could be on older versions.
#skip-changelog.

Fix changelog references to V7

---

CHANGELOG.md

Some changelogs were missing the correct format, this PR fixes the changelog references to have an accessible URL to the changes without a URL.

Fix Changelog references

---

packages/core/ios/RNSentry.mm

The latest v7 release is causing CI to break in sentry-cocoa, this should fix it

Fix: Fix compile error in v7

---

.github/workflows/e2e-v2.yml

This reverts commit 985e404d6274b44e19ed570581b52a3ce6437385.
Fixes https://github.com/getsentry/sentry-react-native/issues/5207

fix(metro): Fixes Metro 0.83.2 sentry-cli issue

---

.github/workflows/e2e-v2.yml
CHANGELOG.md
packages/core/src/js/tools/vendor/metro/utils.ts

Fixes https://github.com/getsentry/sentry-react-native/issues/5180
* Fixes baseJSBundle and bundleToString TypeErrors with Metro [`0.83.2`](https://github.com/facebook/metro/releases/tag/v0.83.2)
* Also fixes the CI E2E test build issues that started with the metro bump ([tests pass in 0.83.1](https://github.com/getsentry/sentry-react-native/pull/5204))
Breakage in metro `0.83.2`
CI, Manual

fix(metro): Fixes Metro 0.83.2 breakages

---

.github/workflows/danger.yml
.github/workflows/update-deps.yml

Reverts the changes in https://github.com/getsentry/sentry-react-native/pull/5216 due to the [introduced breakages](https://github.com/getsentry/github-workflows/releases/tag/3.0.0) preventing the flows from running correctly.
The bump will be tackled with https://github.com/getsentry/sentry-react-native/pull/5218 after the issues are fixed
CI

chore(deps): Reverts bump getsentry/github-workflows from 2 to 3

---

.github/workflows/buildandtest.yml
.github/workflows/sample-application.yml
.gitignore
CHANGELOG.md
package.json
packages/core/RNSentry.podspec
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryReplayOptionsTests.swift
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryTests.h
packages/core/RNSentryCocoaTester/RNSentryCocoaTesterTests/RNSentryTests.m
packages/core/ios/RNSentry+fetchNativeStack.m
packages/core/ios/RNSentry.h
packages/core/ios/RNSentry.mm
packages/core/scripts/expo-upload-sourcemaps.js
packages/core/src/js/tools/sentryMetroSerializer.ts
packages/core/src/js/tools/vendor/metro/countLines.ts
packages/core/src/js/tools/vendor/metro/utils.ts
performance-tests/metrics-ios.yml
samples/react-native/ios/SentryNativeInitializer.h
samples/react-native/ios/SentryNativeInitializer.m
samples/react-native/ios/sentryreactnativesample.xcodeproj/project.pbxproj
samples/react-native/ios/sentryreactnativesample/AppDelegate.mm
scripts/swiftlint.sh
yarn.lock

⚠️ **Please DO NOT MERGE since it will be merged with the release**
This version cherrypicks the following from v7
* https://github.com/getsentry/sentry-react-native/pull/5185
* https://github.com/getsentry/sentry-react-native/pull/5206
* https://github.com/getsentry/sentry-react-native/pull/5210
* Bumps Cocoa to 8.56.2 and cherrypicks the needed modifications from https://github.com/getsentry/sentry-react-native/pull/5036
* https://github.com/getsentry/sentry-react-native/pull/5215 to fix the broken linter on CI
* User requests for the fixes in v6 ([one](https://github.com/getsentry/sentry-react-native/issues/5146#issuecomment-3319212451), [two](https://github.com/getsentry/sentry-react-native/pull/5210))
* Metro breakage
CI, Manual

chore: V6: Bug Fix Release v6.22.0

---

CHANGELOG.md
packages/core/src/js/client.ts
packages/core/test/client.test.ts

 Fix the issue with changing immutable metadata structure in the contructor of `ReactNativeClient`

---

CHANGELOG.md
packages/core/src/js/playground/modal.tsx
packages/core/test/playground/__snapshots__/modal.test.tsx.snap

Fixes https://github.com/getsentry/sentry-react-native/issues/5189
Removes usage of deprecated `SafeAreaView` in the playground and replaces it by using a simple `View`. Adding `react-native-safe-area-context` as suggested by the warning would be be desirable since it would add a third party dependency in core.
Used the Expo app by uncommenting [these lines](https://github.com/getsentry/sentry-react-native/blob/170d5ea6d79574b6fbd714f6593879220b7d3380/samples/expo/app/_layout.tsx#L152) and verified that the app behavior and appearance does not change
|iOS|Android|
|---|---|
|<img width="1008" height="2244" alt="Screenshot_20251006_124952" src="https://github.com/user-attachments/assets/dbdb818f-effb-4178-b593-fa0dbc1a7cce" />|<img width="1206" height="2622" alt="Simulator Screenshot - …

fix(deps): Remove usage of deprecated SafeAreaView in the playground

---

CHANGELOG.md
packages/core/src/js/replay/mobilereplay.ts

Leaves captureReplay logic to [the native implementation](https://github.com/getsentry/sentry-react-native/pull/5243#discussion_r2410678941)
Fixes https://github.com/getsentry/sentry-react-native/issues/5074
When `replaysSessionSampleRate: 0.0`, and with the steps below, I always got no recording attached to the event though I should have given that `replaysOnErrorSampleRate: 1.0`. I wasn't able to associate this behavior with the `reactNavigationIntegration` as the above issue states but the fix seems to make the the SR recording more reliable.
1. Set `replaysSessionSampleRate: 0.0` [in the sample app](https://github.com/getsentry/sentry-react-native/blob/0b647531c13884b6be72c6f652482d79c6d2d96f/samples/react-native/src/App.tsx#L160). Leave `replaysOnErrorSampleRate: 1.0`
2. Tap the …

fix(session-replay): Leave captureReplay logic to the native implementation
